### ISSUE TITLE
isSymbolicLink is false, but it's link and it's SymbolicLink

### ISSUE THREAD

**Issue by alanhg** [theophilusx/ssh2-sftp-client#450] opened 2022-11-24 12:06 UTC
Inconsistencies returned by the two interfaces
## stat method
![image](https://user-images.githubusercontent.com/9245110/203780105-e38fcd27-fc54-4b93-891b-d49452ff930b.png)

## list method

![image](https://user-images.githubusercontent.com/9245110/203780436-1cc4e9b4-01f4-49dd-bac1-c1b7c7991096.png)

**Comment by theophilusx** [comment] 2022-11-24 13:50
I think it is correct. If you do

ln -s some-file.txt my-link.txt

and then do an ls -l on the directory with these two entries, you will
see that my-link.txt will use 'l'. Basically, 'ls' (what the list method
emulates) doesn't distnguish between symbolic links and hard links, it
just uses 'l' for both. I suspect ls does this because 's' and 'S' are
already used (for showing setuid and sticky bits).

**Comment by alanhg** [comment] 2022-11-26 08:57
like your example.

my-link.txt is SymbolicLink.

list method return it's link and stat return isSymbolicLink is false. 

Is it's a mistake?

**Comment by theophilusx** [comment] 2022-11-28 02:41
What platform/operating system is the remote server?

Pleas provide precise steps to reproduce the issue, including the exact
command you used to create the symbolic link on the remote system.

**Comment by alanhg** [comment] 2022-11-28 11:34
> What platform/operating system is the remote server? Pleas provide precise steps to reproduce the issue, including the exact command you used to create the symbolic link on the remote system.

## version info
1. CentOS 7.6 64bit
2. ln -s a.txt c.txt

**Comment by theophilusx** [comment] 2023-02-07 06:13
Now that I have time to look at this, I can see what is going on. 

When it comes to 'stating' a resource, there are in fact usually two different commands 'stat' and 'lstat'. The key difference between the two is that 'stat' will return the details on the object that the link resolves to i.e. the target while lstat will return the data on the actaul link itself. So the reason isSymbolicLink is false is because the data you are getting back is actaully the data for the target of the symbolic link. 

At this stage ssh2-sftp-client does not support lstat. I could add it, but I'm not sure if there is sufficient need for it. I don't want ot make the package larger by adding a method which is rarely used. Instead, I think I'll just clarify the documentation to make this point  clear.

**Comment by theophilusx** [comment] 2023-02-08 05:04
Found a way to add lstat with minimal additional code, so have added it to the repo and it will be in the next release.

**Closed by theophilusx** 2023-02-08 05:04 UTC
