### ISSUE TITLE
Is it normal to have no error on fastGet when a local path does not exist?

### ISSUE THREAD

**Issue by henriqueyun** [theophilusx/ssh2-sftp-client#328] opened 2021-07-05 21:14 UTC
I am using fastGet to download files from a remote SFTP. I have made some tests and unintentionally insert a non-existent path into localPath parameter.

When my code runs the path does not exist so the file was not downloaded

`client.fastGet('/server/remote-path/file.zip', '/tmp/nonexistent-local-test-path/file.zip')`

Is it ok? Could not have some kind of error or warning for the user knows that the file will not be downloaded?

**Comment by theophilusx** [comment] 2021-07-05 21:53
What version of ssh2-sftp-client?

When I do what you describe, I get a file not found error. Can you
provide some sample code which demonstrates the issue you are seeing? If
I can reproduce, I can work out what is going on.

**Comment by henriqueyun** [comment] 2021-07-07 15:19
I am using ssh2-sftp-client@7.0.0 instantiating like this, 
```
const Client = require('ssh2-sftp-client');
const sftp = new Client('SFTP Oi')
sftp.connect({
    host: '169.57.214.237',
    port: '22',
    username: 'btcc',
    password: 'LI7tglliU7'
}).then(() => {
    logger.info('Successful SFTP Connection')
})
```
and i wrote this download function to run the fastGet
```
sftp.downloadFile = async (filename) => {
    const remotePath = `/public/ICO-DEV/${filename}`
    const localPath = '~/Downloads/nonexistent-folder/file.zip'
    const fileExists = await sftp.exists(remotePath)
    if (fileExists) {
        logger.info(`File found ${remotePath}`)
        return sftp.fastGet(remotePath, localPath)                
    }
    logger.info(`File ${remotePath} not found`)
    return
}
```

**Comment by henriqueyun** [comment] 2021-07-07 15:25
I am using ssh2-sftp-client@7.0.0 instantiating like this,
```
const Client = require('ssh2-sftp-client');
const sftp = new Client('SFTP Client')
sftp.connect({
    host: process.env.HOST,
    port: process.env.PORT,
    username: process.env.USER,
    password: process.env.PASSWORD
}).then(() => {
    logger.info('Successful SFTP Connection')
})
```
and i wrote this download function to run the fastGet
```
sftp.downloadFile = async (filename) => {
    const remotePath = `/public/files/${filename}`
    const localPath = '~/Downloads/nonexistent-folder/file.zip'
    const fileExists = await sftp.exists(remotePath)
    if (fileExists) {
        logger.info(`File found ${remotePath}`)
        return sftp.fastGet(remotePath, localPath)                
    }
    logger.info(`File ${remotePath} not found`)
    return
}
```

**Comment by theophilusx** [comment] 2021-07-08 05:58
I believe there is a bug in the ssh2 module. It looks like the fastGet()
method of ssh2 just hangs if the destination path is bad. I have logged
an issue against the ssh2 module.

As it stands now, if the destination path is bad, scripts will just hang
and never exit or raise an error. There is a sample script in
example/fastget.js which demonstrates this problem. There is also a
script in validation/fastget.js which shows the same behaviour, but only
uses the ssh2 module (no ssh2-sftp-client), which is why I believe it is
a bug in ssh2.

We will have to wait for the ssh2 maintainer to respond and either get a
new version of ssh2 which fixes the problem or find a way to detect the
hanging issue.

**Comment by theophilusx** [comment] 2021-07-08 06:04
I should have also mentioned that until a fix is available from ssh2, you could add a path test and verify the destination path before calling fastGet(). If the issue cannot be resolved in the ssh2 module itself, I will likely add such a test to ssh2-sftp-client. However, I think it is better to wait and get a response from the ssh2 author before I do this.

**Comment by theophilusx** [comment] 2021-07-22 01:42
mscdex/ssh2#1034

**Comment by theophilusx** [comment] 2021-07-31 07:20
I have added some local object tests to ssh2-sftp-client master branch which should address this issue until ssh2 is updated to perform its own tests and/or throw an error when local resources is unavailable etc. Will push out new version soon (just waiting to see if ssh2 is updated with some other fixes which may occur this weekend). I will close this issue for now.

**Closed by theophilusx** 2021-07-31 07:20 UTC
Labels: external-dependency-bug
