### ISSUE TITLE
Error on a specific SFTP server when using "put" method to upload file: Error Message: No such file or directory. File does not exist

### ISSUE THREAD

**Issue by wahajahmed** [theophilusx/ssh2-sftp-client#372] opened 2021-12-21 19:29 UTC
Hi there,

we are using version "6.0.1". Below is the code we use to upload files:

```
function UploadFileToSFTPServer(localFilePath, remoteFilePath) {
  const sftp = new SFTPClient('verst-client');
  return sftp.connect(SFTP_CREDENTIALS)
    .then(() => {
      // console.debug('UploadFileToSFTPServer put', 'Uploading file...');
      return sftp.put(localFilePath, remoteFilePath);
    })
    .then(() => {
      // console.debug('UploadFileToSFTPServer end', 'Ending Connection...');
      // return true;
      return sftp.end();
    })
    .catch((err) => {
      console.error('UploadFileToSFTPServer error', err.message);
      throw err;
    });
}
```

Above code is working file for other SFTP servers and successfully uploading files but recently we got an SFTP server from CLEO where we have to upload a file on a folder name "upload" and our user has only "write" permission on that folder where we have to upload the file. We are getting no exception or any other error in above code but CLEO SFTP server tea m is telling us that they are getting following error on their side and they are not receiving any file in "upload" folder.

Error:
Response: "SSH_FXP_STATUS - No such file or directory.    /upload/940_STD_CSV_24234234.csv does not exist"

Below is the trail they provided us.
![cleo-error (1)](https://user-images.githubusercontent.com/10164383/146986509-8a09f570-a764-4687-ad34-aca8666dbc09.png)

They are saying that it looks like you are trying to perform some read operation or something similar, but as you have no read permission (only write) so server is giving this error. We asked them to provide our user "read" access on "upload" folder but they strictly refused our request.

What can we do here and what changes we need to made in our code to upload file successfully on to their SFTP machine?

Thanks.

**Comment by wahajahmed** [comment] 2021-12-21 19:37
**One observation with WinSCP Windows client:**

We were getting the same error when we were trying to upload the file using WinSCP.
![WINSCP Error](https://user-images.githubusercontent.com/10164383/146987282-71731199-08af-4f00-8409-66805ae04a2d.png)

But when we did this settiing in WinSCP:
![WINSCP Setting](https://user-images.githubusercontent.com/10164383/146987543-c6baa48f-615a-4f9e-8376-0339753d9a10.png)

"Uncheck" the "Preserve Timestamp" setting, the file started uploading successfully using WinSCP after this change.

**Comment by theophilusx** [comment] 2021-12-21 20:00
The first thing you need to do is upgrade to ssh2-sftp-client 7.2.1.
This version is based on a new version of ssh2 (complete re-write). The
version 7.2.1 also removed some of the error checking (which I suspect
is what may be causing the error).

At any rate, if this is an issue with ssh2, you won't be able to get any
action unless your running the current version, so upgrade is first
step.

**Comment by theophilusx** [comment] 2021-12-21 20:05
There are no options in ssh2-sftp-client to change this behaviour and I
don't think there is anything in the API of ssh2 either. At any rate,
first step is to see if v7.2.1 works. If it doesn't, the next step is to
see if the problem is with ssh2-sftp-client or with ssh2 itself. If it
turns out to be ssh2, then you will need to raise an issue with that
probject (you will also need to write a simple ssh2 only script to
demonstrate the issue).

**Comment by theophilusx** [comment] 2022-02-28 05:39
As there has been no further feedback on this issue and 2 releases of ssh2-sftp-client have been made since it was first raised, I'm closing this issue.

**Closed by theophilusx** 2022-02-28 05:39 UTC
