### ISSUE TITLE
Please help using await  sftp.get() hangs randomly without execution

### ISSUE THREAD

**Issue by devgk882** [theophilusx/ssh2-sftp-client#542] opened 2024-06-29 21:01 UTC
Hi,

I am using the below code 
```
const localStream = fs.createWriteStream(localFilePath);
await sftp.get(remoteFilePath, localStream)
console.log("Download completed")
```
but looks like sometimes it hangs and Download completed wont get logged and it hangs indefinitely. I am not sure what else can be done if sftp.get() doesn't get resolved or rejected and file download doesn't seem complete.

I see mostly it hangs when I trying to download big files like size of 1.5 GB

If anyone is aware of the solution for the issue please reply.

I am using Nodejs v18 and latest ssh2-sftp-client

**Comment by theophilusx** [comment] 2024-06-30 07:50
Need a lot more info in order to help diagnose the issue here. Suggest
you open the connection passing in a debug function via the debug
property of the connect config object. Then run a test script and
compare a successful debug log against one which hangs.

I suspect either one of three things are happening -

1. The remote sftp server is closing the connection without signalling
an error or close event. It would be worthwhile checking the logs of the
remote sftp serber.

2. Your network connection with the remote sftp serber is being lost and
data just stops flowing without any errors being signalled. Flaky
network issues have frequently been encountered with poorly configured
docker instances and with Windows WSL (WSL can have issues with MTU >=
1500, 1280 or less recommended)

3. An errror or close signal is not being picked up by the
ssh2-sftp-client get method. I feel this is unlikely as there would be
far more reports of this issue if it was. However, at this stage with
available info, all possibilities need to be considered. More detailed
debug logs will help

**Comment by devgk882** [comment] 2024-06-30 12:21
Ok will try to get more info

**Comment by theophilusx** [comment] 2024-07-06 03:44
The library can only respond to known errors. If the remote server does not signal an error or otherwise inform the client of an issue, the cleint obviously cannot report anything. Likewise, if your network just 'vanishes', the library doesn't necessarily know. In some cases, depending on configuration, you will get a timeout error, but in others, you won't. 

I'm fairly certain issue #538 is client error in use of pass through stream. Issue #540 is unconfirmed and I cannot reproduce it and could also be environment related (as I suspect this one is as well)

**Comment by devgk882** [comment] 2024-07-06 13:58
ok, yes sometimes I see the timeout error and we have error handling for that but sometimes it just hangs I will try to add debug to get the network logs but I don't have a timeline for it.

**Comment by devgk882** [comment] 2024-07-24 00:37
@theophilusx I have another doubt 
so I was try to use something like this
```
const localStream = fs.createWriteStream(localFilePath);
await sftp.get(remoteFilePath, localStream)
localStream.on('error', (err) => {
  console.error('Error writing to local file:', err);
});
localStream.on('close', () => {
     console.log('Completed file writing")
});
```
But what i observer is it never gets inside the 'close' event and its never logged am I doing anything wrong?

**Comment by theophilusx** [comment] 2024-07-30 07:01
you have to add the event listeners before you call await sftp.get().

When you use awsait, effectively your telling your script to wait until
the rquested operation has finished. In your script, the file is
downloaded and then you add the listeners, which never trigger because
the download has already completed.

Here is an example script which works. Note that it uses the dotenv
package to manage user credentials and in node 20+, dotenv support is
built in. 

const { join } = require('node:path');
const dotenvPath = join(__dirname, '..', '.env');
require('dotenv').config({ path: dotenvPath });
const { argv, env, exit } = require('node:process');
const Client = require('../src/index');
const { createWriteStream } = require('node:fs');

const config = {
  host: env.SFTP_SERVER,
  username: env.SFTP_USER,
  password: env.SFTP_PASSWORD,
  port: env.SFTP_PORT || 22,
};

async function main() {
  let sftp = new Client();

  try {
    if (argv.length !== 4) {
      console.log('Wrong # arguments!\n');
      console.log('Usage: node ./stream-get.js <remote file> <local file>');
      exit(1);
    }
    const srcPath = argv[2];
    const dstPath = argv[3];
    await sftp.connect(config);
    const ws = createWriteStream(dstPath);
    ws.on('error', (err) => {
      console.error(`ws error: ${err.message}`);
    });
    ws.on('close', () => {
      console.log('ws close event raiswed');
    });
    ws.on('end', () => {
      console.log('ws end event raised');
    });
    await sftp.get(srcPath, ws);
    console.log('File downloaded');
  } catch (err) {
    console.error(`main: Error ${err.message}`);
  } finally {
    await sftp.end();
  }
}

main();

**Closed** 2024-08-07 00:38 UTC
