### ISSUE TITLE
(SSH) Channel open failure: open failed

### ISSUE THREAD

**Issue by incubux** [theophilusx/ssh2-sftp-client#36] opened 2017-10-01 20:40 UTC
(SSH) Channel open failure: open failed
Why is this happening?
thanks for helping

**Comment by jyu213** [comment] 2017-10-09 09:37
sorry.. 
May be you can search https://github.com/mscdex/ssh2 for help.

**Comment by edencorbin** [comment] 2018-05-19 02:06
I get this same error. Interestingly, everything works great, and I make many uploads, but then I will get this error out of the blue. I thought it was because I wasn't closing my connections (but I put a manual close in) and still see this issue, again after days and successful uploads.... what could cause this... eventually? Why does a process restart fix it?

My general code format is as follows:

```
            return sftp.connect(sftpconfig).then(() => {
              return sftp.put(localPath, BASIC_URL + file_name).then(() => {
                  return sftp.end().then(() => { //close the connection
                    return res.redirect('/');
                  });
              });
            });
```

**Comment by theophilusx** [comment] 2019-08-22 08:23
The module has moved on a lot since this issue was logged and the API is quite different. Therefore I'm going to close this issue if there are no objections. If it is still a problem, please add a comment. Some sample code would help in reproducing the issue, plus don't forget to specify module version and node version.

**Closed** 2019-08-28 01:57 UTC
Labels: more info
