### ISSUE TITLE
4.3.1 get not work for large files 

### ISSUE THREAD

**Issue by Zendor18** [theophilusx/ssh2-sftp-client#201] opened 2020-01-09 15:07 UTC
I'm trying to use streams with get interface. But it's not working with "large" files (more then 100kB for me), promise just never resolves. For smaller files all is okay.

```javascript
// FtpClient module:
import * as SftpClient from 'ssh2-sftp-client';
import { ConnectConfig, SFTPWrapper } from 'ssh2';

export default class FtpClient extends SftpClient {
  readonly options: ConnectConfig;

  constructor(options: ConnectConfig) {
    super();
    this.options = options;
  }

  conn(): Promise<SFTPWrapper> {
    return this.connect(this.options);
  }
}

// index.js (this is how i use it in my code, this promise never resolves):
this.ftpClient.get(join(snapshotFile.path, name), new PassThrough())
```

**Comment by theophilusx** [comment] 2020-01-09 21:55
I see this is typscript, which I know nothing about!

I will see if I can reproduce, but I think it may be a local issue. I'm
using this module in a production environment where we use get and a
stream to unzip compressed files which are many megabytes (i.e. over
150Mb) in size with no issues at all. The test suite also has tests
which use get and a stream with files > 6Mb.  

>
> // index.js (this is how i use it in my code, this promise never resolves):
> this.ftpClient.get(join(snapshotFile.path, name), new PassThrough())
> ```


what is PassThrough()? 

That call looks wrong. If you have extended the SftpClient class, then
the call should be this.get(), not this.ftpClient.get(). The call you have
looks like it is directly calling the get() method of the SSH2 class,
which does not return a Promise. 
Things I would try

1. Can you download the file using get() with a destination file path
instead of a stream?

2. Can you download the dfile using fastGet()?

3. Can you download the file using CLI sftp?

Also, what version of node are you running and what platform are you
running on? (windows, mac, linux?). Finally, what do you know about the
remote sftp server? There have been issues with some SFTP servers
(i.e. BrickFTP/files.com).

-- 
Tim Cross

**Comment by Zendor18** [comment] 2020-01-10 06:05
[PassThrough()](https://nodejs.org/api/stream.html#stream_class_stream_passthrough) - duplex stream, i'm using duplex because types are outdated (they are for version 4.1), in current types version
```javascript
 get(path: string, dst?: string | NodeJS.ReadableStream, options?: ssh2Stream.TransferOptions): Promise<string | NodeJS.ReadableStream | Buffer>;
``` it saying that it receives ReadableStream but in [docs]( get(path: string, dst?: string | NodeJS.ReadableStream, options?: ssh2Stream.TransferOptions): Promise<string | NodeJS.ReadableStream | Buffer>;) you are using WritableStream. So thats why i'm using duplex stream.

I tried this way and it's works (for large files also):
```javascript
import Client from 'ssh2-sftp-client';
const client = new Client();

client.connect({//options}).then(sftp =>  sftp.createReadStream(join(snapshotFile.path, name));
```
I'm calling  this.ftpClient.get() because i have main class with composition and delegation. ftpClient is just an instance of ssh2-sftp-client. Promise returns correctly all the time, only problem it is never resolves for large files with get interface.

Answering your questions: 

1. Yes i can, it's works just fine.
2. Yes it's also works.
3. And yes it is works :)

I'm using node v12.10.0 and ubuntu 18.04.

**Comment by theophilusx** [comment] 2020-01-10 07:06
OK, that makes a little more sense to me now.

I am not familiar with Typscript and that @types/ssh2-sftp-client type
definitions file is something someone else has done. I'm not sure it is
correct or not.

The only real requirement on the stream passed into get is that it
supports pipe(). All the method really does is wrap the SSH2 get
function in a promise. It first opens up a readStream on the remote file
and then uses pipe() to pass the data to the stream passed in. The
method adds two listeners to the stream - one on error and one on the
finish event. If an error event fires, the promise is rejected and if a
finish event fires, the promise is resolved. If the promise is not
resolving, that would indicate no finish event is being fired.

The fact it works when you use get() with a destination filename and not
whenyou pass in your stream would indicate there is an issue with your
stream. When you call it with a destination filename, the function just
creates a writeable stream using fs.createWriteableStream and then just
pipes() the readable stream to it (exactly the same code except for the
stream creation step).

Try just passing in a writeable stream rather than a duplex stream and
see if that works.

Also, if interested, I'm not far off releasing versin 5.0.0, which has
seen a significant re-write of error handling and error reporting as
well as error event handling (plus some new features, like
uploadDir/downloadDir). You could try giving that version a go as
well. It can be found in the release-5.0.0 branch of the repo.

Meanwhile, I'll see if i can reproduce your issue using a duplex
stream. I have not tested with a duplex stream, so not sure if it would
make a difference (theoretically, it should be fine). Are you adding any
listeners to your duplex stream?

**Comment by Zendor18** [comment] 2020-01-10 08:54
Thanks! Problem in duplex stream, because it's not emitting 'end' event (i'm not adding any listeners to my duplex stream), so promise never resolves. It's working with writable and //@ts-ignore (because of wrong types). But now i have another problem. Please check #202

**Closed** 2020-01-10 12:01 UTC
Labels: client Error
