### ISSUE TITLE
Quota Exceeded Error on Latest version

### ISSUE THREAD

**Issue by ncipollina** [theophilusx/ssh2-sftp-client#203] opened 2020-01-10 18:00 UTC
When upgrading from version 4.3.0 to the latest version 4.3.1, I get the following error when putting a file:

```
{
  "errorType": "Error",
  "errorMessage": "sftp.put: Quota exceeded. airlinesDelta20200110175629170.csv",
  "trace": [
    "Error: sftp.put: Quota exceeded. airlinesDelta20200110175629170.csv",
    "    at Object.n [as formatError] (/var/task/src/handlers/update-airlines-handler.js:1:376108)",
    "    at ee.c.on.e (/var/task/src/handlers/update-airlines-handler.js:1:137057)",
    "    at ee.emit (events.js:198:13)",
    "    at errorOrDestroy (internal/streams/destroy.js:107:12)",
    "    at onwriteError (_stream_writable.js:436:5)",
    "    at onwrite (_stream_writable.js:461:5)",
    "    at sftp.writeData (/var/task/src/handlers/update-airlines-handler.js:1:181778)",
    "    at cb (/var/task/src/handlers/update-airlines-handler.js:1:158632)",
    "    at O._transform (/var/task/src/handlers/update-airlines-handler.js:1:153540)",
    "    at O.Transform._read (_stream_transform.js:190:10)"
  ]
}
```

My code for the put looks like this:

```
import * as Client from 'ssh2-sftp-client';

export class SftpService {
    constructor(private host: string, private port: number, private username: string, private password: string) {
    }

    public async putFile(contents: string, path: string): Promise<void> {
        const client = new Client();
        return client.connect({
            host: this.host,
            port: this.port,
            username: this.username,
            password: this.password
        }).then(() => {
            console.info('Connected to sftp server. Putting file now.');
            const buf = Buffer.from(contents);
            return client.put(buf, path);
        }).then(() => {
            console.info(`File ${path} sent. Calleng end now.`);
            return client.end();
        });
    }
}

```

Any idea what could be going on? This exact same code works just fine with version 4.3.0. Execution environment is AWS Lambda Node 10.x

**Comment by theophilusx** [comment] 2020-01-10 20:53
That is a very server specific error message. It isn't an error message
created by ssh2-sftp-client, but rather an error created by the remote
sftp server, so I would suspect it is genuine/real.

Have you verified that you have not exceeded your space/disk quota?

**Comment by ncipollina** [comment] 2020-01-10 21:19
Yes, I thought the same thing, but it only happens when I'm using the latest version of this package (4.3.1). When I downgrade to any other, this works.

**Comment by theophilusx** [comment] 2020-01-10 21:47
Well the underlying SSH2 module was updated in that version, so my guess
is that either it was an error previously just reported as 'Failure"
(there were a few ssh2 errors which only report that) or it is a new
error which ssh2 previously didn't pick up or ignored. There is nothing
in ssh2-sftp-client which generates an error with that wording. 

Have you tried sftp to the same host using same account credentials with
a CLI sftp program? I suspect you will see the same message (maybe as a
warning rather than an error) if you try to upload the same file.

You could try downgrading the ssh2 module in package.json to the same
version as in the earlier release of ssh2-sftp-client. If you then find
the message goes away, then that confirms it is due to the update to
ssh2. You can then log an issue with ssh2 maintainer if you think it is
an incorrect error.

**Comment by theophilusx** [comment] 2020-01-14 22:46
Were you able to make any progress on this issue? Did using the current version, but downgrading the ssh2 dependency make any difference?

**Comment by theophilusx** [comment] 2020-02-11 21:52
As there has been no further information and I cannot reproduce this issue, I'm closing this for now.

**Closed by theophilusx** 2020-02-11 21:52 UTC
Labels: more info
