### ISSUE TITLE
fastGet hangs after downloading few files in loop.

### ISSUE THREAD

**Issue by montumodi** [theophilusx/ssh2-sftp-client#289] opened 2020-12-14 18:25 UTC
Hi,
First of all, thank you for creating and maintaing this package. We are using this to download around 10 big files in a loop from sftp. The files are approx 900 MB each (Some are less, some are more). Not sure what is the problem but fastGet hangs randomly after downloading few files. e.g: It will work fine for first 3 files and then for 4th file it will stuck in between. Other time it will stuck at 2nd file. When I say stuck, I mean the program doesn't do anything. we have got the proper exception handling. The program doesn't terminate. It just doesn't do anyhing. I have tried it with different SFTP servers, just to rule out of it is a settings issue on the server side. Here are details

**OS**: Centos and MacOs
**Node**: 12.8.3
**ssh2-sftp-client** : Latest Version

**Sample code**

```
async function download() {
  const Client = require("ssh2-sftp-client");
  const sftp = new Client();

  await sftp.connect({
    "debug": log => console.log(log),
    "host": service.sftp.host,
    "port": service.sftp.port,
    "username": service.sftp.username,
    "password": service.sftp.password,
    "keepaliveInterval": 2000, // I added this setting after finding one link on stackoverflow.
    "keepaliveCountMax": 20
  });

  const fileList = await sftp.list("/folder");

  const path = `${__dirname}/downloaded`;

  for (const file of fileList) {
    await sftp.fastGet(`/folder/${file.name}`, `${path}/${file.name}`);
  }
  await sftp.end();
}
```

**Here is the output of the debug logs**

```
DEBUG[SFTP]: Outgoing: Writing READ
DEBUG[SFTP]: Outgoing: Writing READ
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:16156,padLen:4,remainLen:16152
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
DEBUG[SFTP]: Parser: Response: DATA
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:16156,padLen:4,remainLen:16152
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:16156,padLen:4,remainLen:16152
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
DEBUG[SFTP]: Parser: Response: DATA
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:16156,padLen:4,remainLen:16152
DEBUG[SFTP]: Outgoing: Writing READ
DEBUG[SFTP]: Outgoing: Writing READ

---------------------------------------------- // I guess after this log it stops and keeps on logging same set of logs. Probably because of keep alive setting

DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:2684,padLen:9,remainLen:2680
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
DEBUG[SFTP]: Parser: Response: DATA
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG[SFTP]: Outgoing: Writing READ
DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: REQUEST_SUCCESS
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: REQUEST_SUCCESS
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: REQUEST_SUCCESS
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
DEBUG: Parser: IN_PACKET
```

Any assistance you can provide would be greatly appreciated

Thanks,
Ashish

**Comment by theophilusx** [comment] 2020-12-14 22:30
I cannot see anything obvious in your code that might explain the issue
you are seeing. I would start by updating your node to version 12.20.0.

Please verify that you are using ssh2 0.8.9. This is the module
ssh2-sftp-client uses to perform the low level sftp protocol stuff. The
very latest github master (which will become v1.0.0 currently has a
problem with fastPut and fastGet which is the same as your error. It
would be unusual to have this installed, but as it is the same error,
best to eliminate it as a possible source.

There have been some similar reports which appear to be due to some sftp
servers dropping (closing) connections without raising an error. As the
promises rely on either an operation completing or receiving an error
(either from the callback or from an error signal), abruptly ending a
connection without raising an error can result in a hang.

To try and address this, I have made some changes in the next version
which add listeners for unexpected close and end events. It would be
worthwhile trying out this version to see if that fixes the problem.
I've not yet completed testing for this version, but it is pretty
stable. You can find it under the ssh2-sftp-client repository in the
version-6 branch.

If that still doesn't fix the problem, you can try

- converting from fastGet to just get
- Using fastGet, but set the concurrency option to 1

There does seem to be some edge cases in the ssh2 code for
fastGet/fastPut which result in the system appearing to hang for files
over a certain size. This appears to be related to the concurrency
feature of fastGet/fastPut. I've found that setting concurrency to 1
usually fixes this issue. However, having concurrency: 1 makes
fastGet/fastPut essentially the same as git/put. Some sftp servers don't
seem to handle concurrency well, so this could also be a problem
inherent to the remote sftp server, in which case using get/put will
likely be more reliable.

**Comment by montumodi** [comment] 2020-12-15 08:41
Thank you for quick reply. I will try your suggestions and update you with the results.

**Comment by montumodi** [comment] 2020-12-15 09:19
Hi @theophilusx. I have tried following workarounds

- Add concurrency to 1 for fastGet
- Use Get instead of fastGet

Unfortunately same result.

Thanks,
Ashish

**Comment by theophilusx** [comment] 2020-12-15 12:16
OK, that likely means the problem is that the remote server is abruptly
closing the connection, but not sending an error when it does so.

Try running the code in the version-6 branch of the ssh2-sftp-client
repository. It adds additional listeners for close and end events which
should pick up such unexpected termination of the connection. It won't
fix the problem if the remote server is closing the connections, but it
should prevent the script from just hanging.

**Comment by montumodi** [comment] 2020-12-15 13:11
I have tried version 6 of ssh2-sftp-client repo and behaviour is same.

**Comment by theophilusx** [comment] 2020-12-15 19:37
sorry, but I'm pretty much out of ideas and as I cannot reproduce the
issue, I cannot help much.

The only thing I can think of now is to try and reproduce the issue
using just ssh2 without any ssh2-sftp-client. If the issue persists,
then that will be confirmation the problem is in ssh2 and you will need
to work with the maintainers of ssh2 to get it resolved. If the problem
goes away, then it is an issue with ssh2-sftp-client and we will know it
is most likely something around the promise wrappers and event signals,
so I might have more of a chance to identify the problem.

The last thing you could try is to use something else, like a simple
wrapper around lftp and see if that works better or if you see the same
issue, in which case you know it is either a problem with your sftp
server or the network.

Note that I'm using this module in a couple of production systems where
it downloads multiple files, each Mb or Gb in size, using fastGet, which
run multiple times per day with very few instances of the script hanging
e.g. less than 10 times in the last 12+ months. When we first had the
script hang, I did add a lock file to the script (because our biggest
issue was if a subsequent copy of the script ran before the previous run
had exited). If the script goes to run and finds the lock file still
exists, it alerts us via email. While we have not seen any such alerts
for many months, we have left this in place. You might be able to do
something similar. In our case, the issue was caused by the remote SFTP
service being moved to a cloud based server and some initial teething
problems the maintainers were having with the new cloud service (I don't
know what cloud service they were using). Once they had these issues
sorted, we stopped having issues.

**Comment by montumodi** [comment] 2020-12-15 20:32
You are right. Problem is reproducible with ssh2 as well. I have created an issue on that repo (https://github.com/mscdex/ssh2/issues/966). Thanks for your help.

**Comment by theophilusx** [comment] 2020-12-15 20:40
I would also recommend setting up a basic shell script using lftp (or
similar), just to eliminate network/server issues as well.

**Comment by montumodi** [comment] 2020-12-15 20:52
I have tried with two sftp servers and it is same problem. But I will give it a try with lftp.

**Comment by theophilusx** [comment] 2020-12-19 08:45
As this is an issue that occurs with just ssh2, meaning either it is a bug in ssh2 or some sort of local issue, I'm going to close this issue as there is nothing we can do from the ssh2-sftp-client level.

**Closed by theophilusx** 2020-12-19 08:45 UTC
