### ISSUE TITLE
Randomly exits whole application during long puts to a slow server

### ISSUE THREAD

**Issue by karjaneth** [theophilusx/ssh2-sftp-client#49] opened 2018-02-07 17:18 UTC
While I'm having a really hard time nailing down the exact conditions under which this happens, it seems that when `put`ing a lot of large files to a fairly slow server, the application using the client will just exit with no error. No exceptions are thrown, no promises are rejected, it doesn't "crash" per-se, and the exit code is always `0`, but it does just exit with no warning.

Code following the `put` is **not** run, and the last thing I can do is see the exit code if I have a `process.on('exit')` handler. It's as if something in the library is calling `process.exit(0)` (which doesn't seem to be the case) or `unref`ing every callback (I don't know enough about node internals to know if that's possible) or something else?

Providing a `debug` function to the `connect` function seems to _sometimes_ show the server disconnecting right before the application exits, but even then it should throw an error, not silently exit the whole node process. The symptoms are similar to [this node issue](https://github.com/nodejs/node-v0.x-archive/issues/2515) from six years ago, but that has clearly been fixed.

Anyway I'm struggling to get to the bottom of this or even to reproduce it consistently; I can't see any glaring issues in the `put` implementation. If anyone else can see what the cause of this could be, maybe we can get it fixed in this library.

**Comment by karjaneth** [comment] 2018-11-30 20:14
No I never did. It got "resolved" for us when the server in question was made to be faster/more responsive, but this problem was never dealt with. If you figure it out, please share :)

**Comment by theophilusx** [comment] 2019-08-22 07:59
There have been sifnificant changes made in this module since this issue was originally raised. Is it still an issue with latest version e.g. 2.5.2? If not, I would like to close this issue. If it is, then some sample code would help me in being able to reproduce it for further investigation.

**Comment by vkarpov15** [comment] 2019-08-22 13:03
I wasn't able to consistently repro this, but it seems to have gone away after we upgraded from node 6 to node 8. No objections to closing this from me.

**Closed** 2019-08-22 23:30 UTC
Labels: more info
