### ISSUE TITLE
Error on uploading large file

### ISSUE THREAD

**Issue by edwinlxl** [theophilusx/ssh2-sftp-client#212] opened 2020-02-08 23:12 UTC
I setup my local SFTP server using OpenSSH in Windows 10. I was able to upload a small string to the SFTP server. However, as I increased the string size, repeated the same string for more than 30 times, I got a corrupted file with size of 100 KB and the following error:

```
{ Error: put: Failure I://test//testfile.zip
    at Object.formatError (I:\TestProject\node_modules\ssh2-sftp-client\src\utils.js:62:18)
    at WriteStream.stream.once.err (I:\TestProject\node_modules\ssh2-sftp-client\src\index.js:628:26)       
    at Object.onceWrapper (events.js:273:13)
    at WriteStream.emit (events.js:182:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at sftp.writeData (I:\TestProject\node_modules\ssh2-streams\lib\sftp.js:3057:14)
    at cb (I:\TestProject\node_modules\ssh2-streams\lib\sftp.js:969:15)
    at SFTPStream._transform (I:\TestProject\node_modules\ssh2-streams\lib\sftp.js:417:17)
    at SFTPStream.Transform._read (_stream_transform.js:190:10) code: 'ERR_GENERIC_CLIENT', custom: true } 
```

I am able to copy the large file to the SFTP server by using WinSCP, so I think ssh2-sftp-client has problem with the Windows SFTP server.

**Comment by theophilusx** [comment] 2020-02-10 08:36
That error message indicates the error is occuring within the ssh2 module. Unfortunately, it is not a very helpful error message. 

I have seen this error when client code exits before the transfer has completed. this can occur when using async/await and you have a missing await or when using traditional Promises and you con't have a .then or .catch clause (your scirpt exits before the transfer finishes). 

If you can provide a minimal script which reproduces the error, I can investigate further. Also need to know what version of node you are running. I don't use the windows platform and if you are able to assist in debugging the issue, that would really help.

**Comment by edwinlxl** [comment] 2020-02-11 22:57
I can solved the issue by splitting the string into small chucks of Buffer:
https://github.com/boo1ean/buffer-chunks/blob/master/index.js

`const readStream = Readable.from(chunks(content, 1024));`

Below is the code to reproduce the issue:
`  let remote = 'I://test//testfile.txt';
  sftp.connect({
    host: '127.0.0.1',
    port: '22',
    username: 'test',
    password: 'test111'
  }).then(() => {
    let sampleStr = 'test data 0 test data 1 test data 2 test data 3 test data 4 test data 5 test data 6 test data 7 test data 8 test data 9';
    console.log(sampleStr.length);
    let content = '';
   //working when i<850;
    for(let i=0; i<900; i++){
      content += sampleStr;
    }
    console.log(content.length);
  
    return sftp.put(
      Buffer.from(content),
      remote);
  })
  .then(() => {
    console.log('uploaded');
    return sftp.end();
  })
  .then(()=>{
    res.json({message: 'OK'});
  })
  .catch(err => {
    console.log(err);
    res.status(500).json({message: err.message});
  });`

**Comment by theophilusx** [comment] 2020-02-16 18:54
Using a slightly modified version of your script, I cannot reproduce the error you have been seeing. The correct amount of data is uploaded regardless of input buffer size. 

````
'use strict';

const path = require('path');
const dotenvPath = path.join(__dirname, '..', '.env');
require('dotenv').config({path: dotenvPath});
const Client = require('../src/index');

const config = {
  host: process.env.SFTP_SERVER,
  username: process.env.SFTP_USER,
  password: process.env.SFTP_PASSWORD,
  port: process.env.SFTP_PORT || 22
};

const sftp = new Client();

let remote = process.argv[2];
let debug = process.argv[3];

if (debug) {
  config.debug = msg => {
    console.error(msg);
  };
}

sftp
  .connect(config)
  .then(() => {
    let sampleStr =
      'test data 0 test data 1 test data 2 test data 3 test data 4 test data 5 test data 6 test data 7 test data 8 test data 9';
    console.log(`Sample length: ${sampleStr.length}`);
    let content = '';
    //working when i<850;
    for (let i = 0; i < 1000; i++) {
      content += sampleStr;
    }
    console.log(`Content length: ${content.length}`);
    return sftp.put(Buffer.from(content), remote);
  })
  .then(() => {
    console.log('uploaded');
    return sftp.stat(remote);
  })
  .then(stats => {
    console.log(`Remote Size: ${stats.size}`);
    return sftp.end();
  })
  .catch(err => {
    console.log(err.message);
  });
````

I suspect the issue is with your remote sftp server or the platform you are running on. I have added the above script to the master branch of the git repository. Can you checkout that branch and run the script as follows 

````
node example/buffer-put.js /path/to/remote/file debug
````

and send me the output. This will provide additional information which might help identify why you are seeing the error you are getting. Meanwhile, I will write a low  level version of the script which only uses the ssh2/ssh2-streams modules. If we see the same error using the low level script, then we will know the issue is with the ssh2/ssh2-streams modules and you will need to log an issue with the maintainer of those modules. 

Note that you must run the script from within the master branch repository as the master branch now includes additional debugging functionality which is not yet in the production release version.

**Comment by theophilusx** [comment] 2020-03-01 23:43
Is there any further update for this issue?

As I cannot reproduce this issue from any platform, unless there is more info I cannot provide any further assistance and will therefore close this issue.

**Comment by theophilusx** [comment] 2020-03-16 20:13
As there has been no further update on this issue and a new version has been released, I'm closing this issue. If the issue still exists, we can re-open it once new information is provided.

**Closed by theophilusx** 2020-03-16 20:13 UTC
Labels: more info

**Comment by Esya** [comment] 2020-06-15 11:03
We're having this issue too when using an OpenSSH Server running on Windows. Uploading the same file through Filezilla or just scp works fine. Uploading on any openssh linux server runs fine too.

**Comment by theophilusx** [comment] 2020-06-15 11:49
Can you provide the following

- node version
- ssh2-sftp-client version
- minimal scirpt to reproduce the error

The revious reports of this issue could not be reporduced and I did not recieve the additional info required to debug further. I cannot reproduce this with windows, Linux or macOS using node v12 and latest ssh2-sftp-client.

**Comment by Esya** [comment] 2020-06-15 12:54
@theophilusx Absolutely, 

Node version : v12.13.0
ssh2-sftp-client version : 5.1.2

Code : 

```typescript
import sftp from 'ssh2-sftp-client'

(async() => {
  console.log("Version ", process.version)
  const client = new sftp()
  await client.connect({
    host: 'REDACTED',
    username: 'Administrator',
    password: 'REDACTED,
    port: 22,
    // debug: console.log
  })

  // This works
  await client.put(Buffer.alloc(1024 * 99), "C:/works.txt")
  console.log("99kb file uploaded")

  // This does not
  await client.put(Buffer.alloc(1024 * 101), "C:/doesnotwork.txt")
  console.log("The one above should have failed")

  await client.end()
})();
```

Gives the following output : 

```
99kb file uploaded
(node:14667) UnhandledPromiseRejectionWarning: Error: put: Failure C:/doesnotwork.txt
    at Object.formatError (node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at WriteStream.<anonymous> (node_modules/ssh2-sftp-client/src/index.js:677:24)
    at Object.onceWrapper (events.js:300:26)
    at WriteStream.emit (events.js:210:5)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:452:5)
    at onwrite (_stream_writable.js:473:5)
    at node_modules/ssh2-streams/lib/sftp.js:3057:14
    at cb (node_modules/ssh2-streams/lib/sftp.js:969:15)
    at SFTPStream._transform (node_modules/ssh2-streams/lib/sftp.js:417:17)
```

**Comment by theophilusx** [comment] 2020-06-16 00:13
So you are uploading to a windows based sftp server? Do you know the
remote server type and version (there has been known issues with some
windows based sftp servers).

Is the remote server within the same network segment as the client?
There has been problems in the past where firewalls cause this type of
error - especially firewalls like Palo Alto which do deep packet
inspection. Because these firewalls need to collect a certain number of
packets in order to do the inspection and make the decision to allow or
block, smaller files can often get through when bigger ones cannot.

To help isolate the problem, can you write a very simple script which
only uses the ssh2 module (see the lowlevel-*.js scripts in the tools
directory of the repo to get an idea of how to do this). This will tell
us if the problem is with ssh2-sftp-client or with the underlying ssh2
module.

Meanwhile, I will see if I can reproduce using your script.

**Comment by theophilusx** [comment] 2020-06-22 06:57
I have tried to reproduce your error, but cannot. However, I cannot precisely reproduce your upload path as my server uses a configuration where you cannot write to the root directory vai sftp, you have to write to a directory configured as the upload home. (different home for each sftp user). I'm not a windows user, so my knowledge on a windows platform is limited and I'm not sure how you configure sftpd to allow writing to the root directory as you appear to be doing. I have attached a script I've been using for testing. It takes 2 arguments - first is the size i.e. 99 or 101 for buffer of 99 or 101 kb and the second argument is the directory to upload the files into. for example /incoming. The script is designed to run from the example directory of the repository and uses the dotenv module to manage login credentials. This was tested using the current master branch of the repository, which does have some minor fixes, but none which I think would affect this issue. You may need to modify slightly if you don't want to use dotenv or run it relative to the repository sources. Example command

node ./buffer-test.js 101 /incoming

[buffer-test.js.txt](https://github.com/theophilusx/ssh2-sftp-client/files/4811619/buffer-test.js.txt)
