### ISSUE TITLE
Node can crash while doing a put because of missing 'error' handler

### ISSUE THREAD

**Issue by AndrewLane** [theophilusx/ssh2-sftp-client#175] opened 2019-10-14 20:56 UTC
Hello,

We are seeing the possibility for a crash of node when doing a put.

Here is the stack trace:

```
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
...
Emitted 'error' event at:
    at Socket.<anonymous> (/usr/src/app/node_modules/ssh2/lib/client.js:307:10)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
...
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
error Command failed.
Exit code: 1
```

In terms of things we have looked at, we see that the SFTPWrapper will emit an error:
https://github.com/mscdex/ssh2/blob/master/lib/SFTPWrapper.js#L15-L16

Do we need to add an error handler to the sftp object here in addition to the stream?

https://github.com/theophilusx/ssh2-sftp-client/blob/master/src/index.js#L449-L453

**Comment by theophilusx** [comment] 2019-10-14 21:21
Can you confirm which version of ssh2-sftp-client you are using? 

Adding an additional error listener is certainly a work-around, but I don't think it should be necessary. 

Are you calling client.put() in a promise .then() chain with a .catch() or using await inside a try/catch?

**Comment by AndrewLane** [comment] 2019-10-15 01:42
@theophilusx we recently upgraded from `3.1.0` to `4.2.0` so we could take advantage of the built-in retries.  The function that is experiencing the crash is below.

```
  async transferFile(params, fileName, path, fileContents) {
    const sftp = new SFTPClient();
    try {
      this.addRetryParams(params);
      await sftp.connect(params);
      const destinationFolder = trimstart(`${trimend(path, '/')}/`, '/');
      const completeDestinationPath = `${destinationFolder}${fileName}`;
      await sftp.put(Buffer.from(fileContents), completeDestinationPath);
    } finally {
      sftp.end();
    }
  }
```

We are pretty confident that we can rule out the call to `connect` as the issue.

**Comment by theophilusx** [comment] 2019-10-15 02:41
Thanks for the sample code - it really helps. 

I think the problem is you don't have a catch clause in that try block. As a result, any errors or rejected promises are bubbling up to the top level and then your script exits. You need to do something like

```
  async transferFile(params, fileName, path, fileContents) {
    const sftp = new SFTPClient();
    try {
      this.addRetryParams(params);
      await sftp.connect(params);
      const destinationFolder = trimstart(`${trimend(path, '/')}/`, '/');
      const completeDestinationPath = `${destinationFolder}${fileName}`;
      await sftp.put(Buffer.from(fileContents), completeDestinationPath);
    } catch (err) {
       console.log(err.message);
      // take error recovery actions/logging/reporting etc
    } finally {
      sftp.end();
    }
  }

```

Based on the error message, it looks like the remote server is resetting the connection. This is most often seen during the connect stage, but in your case, it looks like it might be occurring while the data is being written tot the writeStream. It may be worthwhile checking the remote sftp logs (if you have access) to see if that gives some clue as to why the connection is being reset. I have seen this occur when the remote server does some sort of rate limiting or connection limiting, but you would only see that if your making lots of separate connections over a short interval.  It may also be useful to try uploading the files manually using CLI sftp client. 

BTW if all your doing is reading files in and then uploading them (i.e. not doing any processing of the data in your script), you are far better off using fastPut() rather than put() as it is a lot faster.

**Comment by theophilusx** [comment] 2019-10-15 02:43
Also meant to mention that a simple console.log() statement after the call to connect() will confirm weather the connect is successful or not. If not, the line won't be processed and no message will be printed.

**Comment by AndrewLane** [comment] 2019-10-15 11:44
Sorry, I should have included more code earlier.  I'm calling that `transferFile` method this way:

```
  try {
    log.info(`Transferring ${fileName}...`);
    await transferFile(connectionParams, fileName, sftpPath, file);
    log.info(`Successfully transferred ${fileName}.`);
    // ...
  } catch (err) {
    log.error(`Failure transferring ${fileName}: ${err.message}`);
    // ...
  }
```

And what we are seeing during the crash is that the first `Transferring...` log is output, but then nothing (we see evidence of a crash right afterwards).  We don't see the log that indicates a success, nor do we see the log that indicates a failure.

**Comment by AndrewLane** [comment] 2019-10-15 14:39
FYI we got another crash last night, this time in a different path:

```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at SSH2Stream.ondata (_stream_readable.js:709:20)
    at SSH2Stream.emit (events.js:198:13)
    at SSH2Stream.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at SSH2Stream.Readable.push (_stream_readable.js:224:10)
    at SSH2Stream.Transform.push (_stream_transform.js:151:32)
    at SSH2Stream.push (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:257:18)
    at send_ (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:5211:16)
    at send (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:5117:12)
    at /usr/src/app/node_modules/ssh2-streams/lib/ssh.js:4779:5
    at AsyncWrap.retry (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:5240:11)
    ...
Emitted 'error' event at:
    at Socket.<anonymous> (/usr/src/app/node_modules/ssh2/lib/client.js:307:10)
    at Socket.emit (events.js:203:15)
    at Socket.EventEmitter.emit (domain.js:448:20)
    ...
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at doWrite (_stream_writable.js:411:11)
    at writeOrBuffer (_stream_writable.js:399:5)
    [... lines matching original stack trace ...]
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8)
error Command failed with exit code 1.
error Command failed.
Exit code: 1
Command: /usr/bin/node
```

**Comment by theophilusx** [comment] 2019-10-15 22:18
OK, let me have a closer look. There is a default error listener, so it should be catching these errors, but all it does is listen for the error event and throws an error when one occurs.  I have my suspicion on what might be going on, but need to experiment to confirm.

Can you tell me

1. What platform is the client running on?
2. What platform is the sftp server running on
3. What software is the remote sftp server

One thing to watch out for in scripts is the number of connections you are making to the remote sftp server.  I have found it is very easy to run into sftp server limit settings if you are creating separate connections for each transfer rather than one connection for multiple transfers. In particular, the maxStartups setting can come into play because the script is running faster than the remote server is able to authenticate connections. The default setting for maxStartups is 10:30:60, which means after reaching 10 unauthenticated sessions (i.e. ssh authentication handshake has not completed), start dropping 30% of connections. If we reach 60 such connections, drop all. 

Two ways to prevent this. You can use one connection for multiple transfers or put a delay between each connection call to allow time for sftp to complete the authentication handshake e.g. 500ms. 

This may not be related to your current issue, but based on the snippets of code, if your making more than 10 connections, it is an issue you are very likely to run into at some point and the fact you have seen errors in a different part of the process is a symptom of this type of error.

**Comment by theophilusx** [comment] 2019-10-16 03:20
No matter what I try, I cannot reproduce this error (or anything similar). I have been writing an sftp server in order to have something I can use to help generate difficult errors to assist with debugging this sort of problem, but it is a way off yet. 

To get to the bottom of this, I will need your assistance. I have created a branch called error-handling and have added a new error listener to the sftp object. I don't know if this will achieve anything or not and cannot generate the error to test it. 

Would it be possible for you to run this branch and see if the errors are handled better?

**Comment by theophilusx** [comment] 2019-10-16 21:08
OK, I understand. If you can run the error-handling branch in your prod system, that would at least tell us if the added handler improves the situation. Make sure to grab the most recent version as I did make some changes after my original post yesterday. 

As I cannot reproduce the issue, there is not much more I can do. Note that I will be releasing a new version of the module to npmjs.com today which fixes some path issues when running on mixed environments (client linux and server windows or client windows and server linux). These fixes are already in the error-handling branch.

**Comment by theophilusx** [comment] 2019-10-16 21:30
Forgot to mention that if you are able to make any progress, I am more than happy to accept pull requests which address the issue.

**Comment by theophilusx** [comment] 2019-11-10 07:17
Any progress on this issue? Wondering if the added handler made any difference?

**Comment by AndrewLane** [comment] 2019-11-10 12:27
Thanks for checking in.  Unfortunately, the only environment we've seen this in is PROD and we have no ability "experiment" in that environment.  We actually ran into an issue where just doing a "connect" for a certain SFTP server would crash node!  I did a little bit of work trying to reproduce that (I thought it would be easy!) but alas, I could not repro anything.  We ended up rolling back to `3.1.0` and probably won't roll forward again unless something is found on this issue.  Thanks for your efforts.

**Comment by theophilusx** [comment] 2019-11-10 21:21
OK, but I must stress that the version 3.x of ssh2-sftp-client is
extremely high risk. In fact, the 3.x version was released and withdrawn
almost immediately due to the problems it had. This was before my
involvement in the project, so I don't have full details. All I can say
is that it was almost immediately deprecated. (I would remove it from
npmjs.com, but there doesn't seem to be a mechanism to remove packages
once published).

It would be my recommendation to use a different package before
resorting to using any 3.x version. You might do better with something
like the ftps (https://www.npmjs.com/package/ftps), a wrapper around
lftp. I used this previously when I found problems I could not resolve
with ssh2-sftp-client (was actually the main reason I ended up as
maintainer for this package). While it doesn't provide the same level of
integration and error handling, it is reasonably robust. It was trivial
to put a wrapper around it so that it was largely a drop-in replacement
for ssh2-sftp-client.


Andrew Lane <notifications@github.com> writes:

> Thanks for checking in.  Unfortunately, the only environment we've seen this in is PROD and we have no ability "experiment" in that environment.  We actually ran into an issue where just doing a "connect" for a certain SFTP server would crash node!  I did a little bit of work trying to reproduce that (I thought it would be easy!) but alas, I could not repro anything.  We ended up rolling back to `3.1.0` and probably won't roll forward again unless something is found on this issue.  Thanks for your efforts.


-- 
Tim Cross

**Comment by AndrewLane** [comment] 2019-11-11 19:52
Wow, we've been using `3.1.0` for a little over a year and I was not aware of this.  I tried to google for the issues that you are referencing, but I couldn't find any.  I also scrolled through past issues on this repo and couldn't find anything of note (maybe the wrong repo?).

**Comment by theophilusx** [comment] 2019-11-11 21:20
As I was only involved on the periphery at the time, I'm not sure. What
I do recall was problems with Promises not being resolved (resulting in
hangs) and I think there was some data loss issues with node >=
10.x. The original author and maintainer of the package did attempt to
fix the issues, but found significant design flaws that resulted in that
version being deprecated. Versions 2.4.x and 2.5.x were actually
released after 3.x. It is one of the reasons why I jumped to version 4.x
once I took over maintenance. 


Andrew Lane <notifications@github.com> writes:

> Wow, we've been using `3.1.0` for a little over a year and I was not aware of this.  I tried to google for the issues that you are referencing, but I couldn't find any.  I also scrolled through past issues on this repo and couldn't find anything of note (maybe the wrong repo?).


-- 
Tim Cross

**Comment by theophilusx** [comment] 2019-11-24 00:10
As we cannot reproduce this issue and it is only being encountered at one site and the site reporting the issue is not in a position to test possible fixes or run additional diagnostic scripts, I'm going to close this issue. If anyone else encounters the same issue, we can reopen it if necessary.

**Closed by theophilusx** 2019-11-24 00:10 UTC
Labels: help wanted, more info
