### ISSUE TITLE
I can't perform a second get using the same write stream

### ISSUE THREAD

**Issue by posti85** [theophilusx/ssh2-sftp-client#307] opened 2021-03-30 18:09 UTC
The most basic example to reproduce the issue it's just trying to concat the content of two existing files:
```js
const writeStream = fs.createWriteStream('./concat-result');
await sftp.get('remote/file0', writeStream);
await sftp.get('remote/file1', writeStream);
```
The execution hangs in the file1 call, and the contact-result file only contains the content of the file0 file. Using `{ autoClose: false }` in the first call didn't work. Maybe a lack of knowledge, but I really don't know what I'm doing wrong!

Thank you very much!

**Comment by theophilusx** [comment] 2021-03-30 20:46
What versions of ssh2-sftp-cleint and node?

What platform are you on (Linux, Mac, Windows)?

Is the remote sftp server just a regular sftp server or something
running in one of the 'cloud' providers (Azure, Google, AWS)?

The get/put methods use pipe() to transfer the data and I would have
expected opening the stream with

const writeStream = fs.createWriteStream('./concat-result', {autoClose: false } );

*should* probably work, but to be honest, I've never tried. I'm assuming
you have verified it isn't something else, like an issue with file1, by
reversing the calls etc?

There is nothing in ssh2-sftp-cleint which explicitly closes the streams
- it just does a basic open remote read stream and pipes that to the
stream you pass in. The pipe would normally result in the stream being
closed, but autoClose: false should stop that.

I will try to investigate later this week and see what I find out. In
the meantime, perhaps do some interrogation of the write stream object
and see what state it has after the call to the first get() and perhaps
turn on debugging and see if that gives more info to work with.


-- 
Tim Cross

**Comment by theophilusx** [comment] 2021-03-31 08:19
OK, unfortunately, I have some bad news.

Due to issues in node v14, the underlying ssh2 module does not work
correctly/reliably with that version of node. This is due to a change in
node introduced in v14. That change was rolled back in node v15.3. So
either you need to use a node version before v14 or a version > 15.3. I
would recommend node v12 if that is possible. You could use node v15.3+,
but the issue is that while the networking changes in node v14 which
have caused problems have been rolled back, they did have significant
performance improvements in most other use cases. Therefore, I suspect
this change will be re-iintroduced in some future version.

The ssh2 maintainer is doing a complete re-write of ssh2, partly to fix
this issue and partly to improve the underlying design and add support
for more encryption types. Unfortunately, that re-write is not yet ready
for production use.

The reason your second file is not being piped to the writeable is
because, by default, the readable in a pipe sends an 'end' event to the
destination stream on completion, which means the stream can no longer
be written to. Currently, there is no mechanism to pass the option {
end: false } to the pipe() call. This effectively means you cannot use
the same writeable for both calls. You will need to create one for the
first call, then create a second one using { flags: "a" } to create a
second writestream which is opened in 'append' mode on the file returned by the first call.

Another alternative would be to create a 'master' write stream locally
and pipe the streams you create for each get() to that master writeable
(where you can set the { end: false} option. Not sure if the added
complexity is worth it though.

I will give some thought as to how easily I could add support for
passing in options to the pipe() call. Not sure how easily I can do this
without adding too much extra complexity and API confusion. 

BTW accessing gzipped files remotely and uncompressing them 'on the fly'
works well. I've used this ability quite a bit when retrieving remote
gzipped files I want to process immediately i.e. piping the uncompressed
data stream into another stream which consumes and processes the data as
it comes down.


-- 
Tim Cross

**Comment by posti85** [comment] 2021-03-31 08:35
Thank you very much for the details Tim :).

**Comment by theophilusx** [comment] 2021-05-11 07:34
I have made some changes to the current master HEAD in the repository which should now allow you to do multiple get() calls using the same destination stream. You will need to pass the options parameter with an end property of false for this to work. e.g. sftp.get(''./somefile.txt', dest, { end: false }); Try it out and if it works, let me know and I'll release a new minor version.

**Comment by posti85** [comment] 2021-05-22 09:39
Thank you very much @theophilusx. Using the current code in `main` branch, it still doesn't work:
```js
const writeStream = fs.createWriteStream('./concat-result');
await sftp.get('remote/file0', writeStream, { end: false });
await sftp.get('remote/file1', writeStream);
```
throws:
```
(node:13580) UnhandledPromiseRejectionWarning: ReferenceError: ERR_INVALID_ARG_TYPE is not defined
    at validateNumber (...\sftp-append\node_modules\ssh2-streams\lib\node-fs-compat.js:123:5)
    at checkPosition (...\sftp-append\node_modules\ssh2-streams\lib\sftp.js:2702:5)
    at new ReadStream (...\sftp-append\node_modules\ssh2-streams\lib\sftp.js:2758:5)
    at SFTPStream.createReadStream (...\sftp-append\node_modules\ssh2-streams\lib\sftp.js:760:10)
    at SFTPWrapper.createReadStream (...\sftp-append\node_modules\ssh2\lib\SFTPWrapper.js:33:23)
```

**Comment by theophilusx** [comment] 2021-05-23 06:15
OK, I think I know what the problem is. However, the new version of ssh2
is likely to be released in the next few days, so I will wait until that
occurs, test against the new ssh2 version and then apply a fix to enable
re-use of streams and then release a new ssh2-sftp-client version
(version 7).

**Comment by theophilusx** [comment] 2021-06-04 07:52
I have re-factored the option handling for both get() and put() which should now work. The options argument is now an object with properties for readStreamOptions, writeStreamOptions and pipeOptions. Each property should be an object containing the options to apply to any read or write streams created by the method or the pipe() call. In your use case, you want to set the options.pipeOptions.end = false to stop the mthod from sending an 'end' event to the write stream. It may also be necessary to turn write stream autoClose off with options.writeStreamOptions.autoClose = false (but not 100% sure on that). 

The current master branch is now based on the new ssh2 v1.1.0 module. I will be releasing a new ssh2-sftp-client version in about a week.

**Comment by theophilusx** [comment] 2021-06-18 04:45
New version 7.0.0 of ssh2-sftp-client has been pushed to npmjs.com. This version includes changes to get()/put() option handling to support re-use of streams (as well as other things). See updated manual entry for details of new option format.

**Closed by theophilusx** 2021-06-18 04:45 UTC
Labels: enhancement
