### ISSUE TITLE
Provide read timeout for "SftpClient.list" and similar methods

### ISSUE THREAD

**Issue by dvlato** [theophilusx/ssh2-sftp-client#151] opened 2019-06-25 13:25 UTC
In some cases, the SftpClient.list never returns a resolution or a rejection as the readdir callback never gets executed.

This happens for me when the connection was successfully established but then gets lost (e.g., when you plug the network cable - even if you reconnect it again).

It seems to me we need some way to specify a read timeout so we won't block forever waiting for SftpClient.list() to return. The same could be said about 'fastGet' and most likely 'get' (I haven't checked this one).

**Comment by dvlato** [comment] 2019-06-27 13:52
Hi,
I see this issue was fixed in the following PR: https://github.com/jyu213/ssh2-sftp-client/pull/66/files . However those changes are not present in the 2.5.0 version:  https://github.com/jyu213/ssh2-sftp-client/blob/2.5.0/src/index.js#L29 ; could you possible generate a release with this change?

**Comment by theophilusx** [comment] 2019-06-27 16:02
I'm, not sure that analysis is correct. The return undefined does nothing and is never executed. The function returns a promise and a promise can only return resolved or rejected. Those return udnefined were added just to shut up the linter.  If you are finding that the promise is resolving to a value of undefined, then that must be the value being returned in the resolve statement, but I cannot see how that is possible. 

When we have encountered timeout or errors, the details are returned in the reject statement. We have not seen any 'undefined' in the catch, so I would be interested to see how you are getting them (sample code?)

I would have expected the ssh2 library which implements the underlying methods to throw an error if there is an error in the connection (see for example the call to readdir and its callback. If it doesn't, then, we will need to look at how to handle this in a clean way. 

I don't think that PR you reference is correct. It is adding on error handlers and never removing them. This will almost certainly bring back the maxListeners issue that existed befiore. I also suspect the issue you are seeing might be something more subtle than simply timeout or stalled processes. We don't see this problem and we are using this library extensively. We recently had network problems, we did get timeout errors as would be expected. We have had 2 instances of the scripts 'hanging', but as yet, have not been able to reproduce reliably in order to find a workable solution (we are using the library to download about 30Gb of data per day in multiple connections with multiple files). 

If it is necessary to have some sort of error handler associated with the connection, then another approach is required - simply adding on error listeners in every function will just result in memory leaks or in a library where you need to create a new connection for every command. 

From memory, we do set the timeout parameter when creating the sftp connection (see ssh2 docs). If your not, perhaps trhe ssh2 library disables timeout and is causing your problem?

**Comment by dvlato** [comment] 2019-06-27 17:17
Hi, 
I have edited the comment so we won't get distracted with details. The problem for me is that the connection gets dropped and we never get notified. 
 I have tested that scenario just unplugging the network cable / disabling the WiFi adapter when  in the middle of a download or list() and I don't get any errors whatsoever unless I specify an error handler.  Please note that someone has commented on your ticket saying they had to timeout() all the function calls in the library. Do you get any different behaviour? Can you post a code sample where this issue does not appear?  As long as we keep using the same connection, unplugging before a list() should also cause the issue mentioned.

The timeout you mention, I believe, is "readyTimeout()". If you check the code, you will see that the timeout is removed once the authentication succeeds, so it doesn't seem too useful here. In any case, as the docs state it is a timeout with a default value of 20.000 and related to the handshake.  Were you talking about any other

**Comment by theophilusx** [comment] 2019-06-27 22:06
It is probably the readyTimeout I was talking about. I don't think there
is any other.

I am wondering why the underlying functions e.g. readdir, don't
generate/throw the error. I use the library in very similar way to how
it is used in the tests. When we have encountered timeouts they have
been caught in the catch block of the promise chain.

We are using the library mainly to download files (about 30Gb per
day). Some downloads use fastGet and others use get, passing in a
writeable stream pipeline which streams the data through a zlib gunzip
object to the writeable stream which creates the local file.

Recently, we had VMWare issues in our virtual environment that caused
network (and other problems) and had frequent failures where the error
was either timeout or lost connection errors, so in at least some cases,
we do see these errors being caught and presented in a manner where they
can be managed.

Would it be possible to see some code so I can see how your using the
library and maybe help me generate a repeatable test case?

David Latorre <notifications@github.com> writes:

> Hi,
> I have edited the comment so we won't get distracted with details. The problem for me is that the connection gets dropped and we never get notified.
>  I have tested that scenario just unplugging the network cable / disabling the WiFi adapter when  in the middle of a download or list() and I don't get any errors whatsoever unless I specify an error handler.  Please note that someone has commented on your ticket saying they had to timeout() all the function calls in the library. Do you get any different behaviour? Can you post a code sample where this issue does not appear?  As long as we keep using the same connection, unplugging before a list() should also cause the issue mentioned.
>
> The timeout you mention, I believe, is "readyTimeout()". If you check the code, you will see that the timeout is removed once the authentication succeeds, so it doesn't seem too useful here. In any case, as the docs state it is a timeout with a default value of 20.000 and related to the handshake.  Were you talking about any other


--
Tim Cross

**Comment by theophilusx** [comment] 2019-09-04 02:08
I've looked into the tiimeout approach. It is quite difficult to implement in a clean manner when it comes to Promises, especailly as it will need to be controlled from the client layer. There are some libraries which may help, but more research needed first. 

In the meantime, there has been some changes to how the module handles events like 'end' 'error' and 'close', which I think have improved matters a lot. I find that if I 'unplug' the network during execution of the test cases that you now get an error and they do not hang. So the immediate issue seems to be resolved to some degree. For additional control, you can also add your own listener using the on() method - for example, on the 'close' event, allowing client code to respond appropriately. 

I will add a feature issue to add timeouts as an additional feature.

**Closed by theophilusx** 2019-09-04 02:08 UTC
Labels: enhancement
