### ISSUE TITLE
Issues downloading file from specific directory on remote

### ISSUE THREAD

**Issue by chaitanyawagle** [theophilusx/ssh2-sftp-client#490] opened 2023-06-28 23:10 UTC
Hi, I am using `downloadDir()` to download a complete remote directory. I get this error message for specific sub directory - 
```
Error: get: The requested operation cannot be performed because there is a file transfer in progress. /config//Test/test-file.yml
    at SftpClient.fmtError (/usr/src/app/node_modules/ssh2-sftp-client/src/index.js:82:22)
    at ReadStream.<anonymous> (/usr/src/app/node_modules/ssh2-sftp-client/src/index.js:500:23)
    at Object.onceWrapper (events.js:520:26)
    at ReadStream.emit (events.js:400:28)
    at Object.cb (/usr/src/app/node_modules/ssh2/lib/protocol/SFTP.js:3710:12)
    at 101 (/usr/src/app/node_modules/ssh2/lib/protocol/SFTP.js:2858:11)
    at SFTP.push (/usr/src/app/node_modules/ssh2/lib/protocol/SFTP.js:278:11)
    at CHANNEL_DATA (/usr/src/app/node_modules/ssh2/lib/client.js:587:23)
    at 94 (/usr/src/app/node_modules/ssh2/lib/protocol/handlers.misc.js:930:16)
    at Protocol.onPayload (/usr/src/app/node_modules/ssh2/lib/protocol/Protocol.js:2052:10)
    at AESGCMDecipherBinding.decrypt (/usr/src/app/node_modules/ssh2/lib/protocol/crypto.js:1086:26)
    at Protocol.parsePacket [as _parse] (/usr/src/app/node_modules/ssh2/lib/protocol/Protocol.js:2021:25)
    at Protocol.parse (/usr/src/app/node_modules/ssh2/lib/protocol/Protocol.js:306:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/ssh2/lib/client.js:775:21)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12) {
  code: 3,
  custom: true
}
```

Here is the code - 
```
async function sync() {
    const client = new SftpClient();
    await client.connect(sftpConfig);
    try{
        results = await client.downloadDir(sftpConfig.remoteDir, sftpConfig.localDir);
        return results
    } catch (error) {
        console.log(error)
    } finally {
        client.end();
    }
}
```
I have tried deleting the folder and adding to SFTP server but still get the same message and all other subdirectories are getting downloaded normally. When I use `client.get(remoteFile, local)` on file in that sub directory, file is getting dowloaded.

**Comment by theophilusx** [comment] 2023-06-29 01:26
I have no idea what the cause could be. You will need to debug it as I
cannot reproduce the issue based on provided details. 

It is possible that if you have a large number of files, some sort of
resource limitation is coming into play. I'm not very happy with the
downloadDir/uploadDir functionality and regret adding it. It really
needs a complete redesign. Part of the problem is I merged in some
contributions to increase performance by using
Promise.all. Unfortunately, while this works well on small/medium sized
directories, it fails on larger ones because node runs out of
resources. It needs a limit added. In hindsight, I should have rejected
the contribution. 

My recommendation would be to not use it and write your own using the
basic get() functionality. It is simple to do, especially if you don't
need a generalised solution and just need one specific to a particular
use case.

I do plan to re-design uploadDir/downloadDir, but will not be able to
look at this until after September.

**Comment by theophilusx** [comment] 2023-10-13 22:21
Closing this issue as the main component i.e. add support to limit concurrent promises in directory upload/download is already covered in another issue. Suspect this is really just a duplicate issue.

**Closed by theophilusx** 2023-10-13 22:21 UTC
