### ISSUE TITLE
What would be scenario where sftp.get call would return the actual data or an stream object ?

### ISSUE THREAD

**Issue by apasrini** [theophilusx/ssh2-sftp-client#164] opened 2019-09-16 12:09 UTC
In my sample program i get an object as output but when i try in my actual application i get out a ReadStream object ?
I have same type of input for get in both 

For example from the below snippet,
 return sftp.get('/s/shipping.jpg');
}).then((data) => {
        console.log('data', data)
        var buffer = new Buffer(data).toString('base64');
        console.log('the data info', buffer);
}).catch((err) => {
        console.log(err, 'catch error');
})}
name();

 console.log('data', data) -- gives me the actual content but the application gives out a readstream function obj

**Comment by apasrini** [comment] 2019-09-16 12:09
ReadStream {
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 65536,
     buffer: BufferList { head: [Object], tail: [Object], length: 1 },
     length: 5610,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: true,
     readableListening: true,
     resumeScheduled: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: 
      StringDecoder {
        encoding: 'utf8',
        fillLast: [Function: utf8FillLast],
        lastNeed: 1,
        lastTotal: 2,
        lastChar: <Buffer d9 00 00 00> },
     encoding: 'utf8' },
  readable: true,
  domain: 
   Domain {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     members: [ [IncomingMessage], [ServerResponse] ],
     oldBind: [Function],
     bind: [Function] },
  _events: { end: [Function], error: [Function], readable: [Function] },
  _eventsCount: 3,
  _maxListeners: undefined,
  path: '/apar5.jpg',
  handle: <Buffer 00 00 00 00>,
  flags: 'r',
  mode: 438,
  start: undefined,
  end: undefined,
  autoClose: true,
  pos: 131072,
  sftp: 
   SFTPStream {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 32768,
        buffer: [BufferList],
        length: 0,
        pipes: [Channel],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: 
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [Array],
        oldBind: [Function],
        bind: [Function] },
     _events: 
      { end: [Array],
        prefinish: [Array],
        finish: [Array],
        error: [Array],
        close: [Array],
        data: [Function: ondata],
        unpipe: [Function: onunpipe],
        drain: [Function],
        continue: [Function] },
     _eventsCount: 9,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 32768,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: true,
     _transformState: 
      { afterTransform: [Function: bound afterTransform],
        needTransform: true,
        transforming: false,
        writecb: null,
        writechunk: null,
        writeencoding: 'buffer' },
     debug: [Function: DEBUG_NOOP],
     server: false,
     _isOpenSSH: true,
     _needContinue: false,
     _state: 
      { status: 'packet_header',
        writeReqid: 9,
        pktLeft: 0,
        pktHdrBuf: <Buffer 00 00 00 00 00 00 17 1d 67>,
        pktBuf: undefined,
        pktType: 103,
        version: 3,
        extensions: [Object],
        maxDataLen: 260096,
        requests: [Object] } } }

**Comment by theophilusx** [comment] 2019-09-16 12:30
If get() is called with only a source path, it will return a Buffer object. If you call get() with a second argument, it must be either a string, which will be interpreted as a path to store the retrieved file or it must be a writeStream, which will be used in a pipe to send the data retrieved from the remote server. Not sure whoat or how you are getting a readStream, but I cannot reproduce that. Post a full reproducible test case and Ill have a look.

**Comment by apasrini** [comment] 2019-09-17 09:43
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:226:9)
    at new Buffer (buffer.js:174:17)
    at sftp.connect.then.then.then (/Users/apasrini/Desktop/sc/s.js:21:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) 'catch error' 

I am getting the above error. I am in a older version of the node module and this is a critical fix needed for our client and we are not in a position to update the node module to latest version. Could you please let me know when this issue was resolved in which version ?

**Comment by theophilusx** [comment] 2019-09-17 12:39
I need to know what version of the module you are currently using, what version of node you are running and what platform are you on.

**Comment by apasrini** [comment] 2019-09-19 16:58
node version v9.2.0 
MAC OS
2.1.0 is the version

**Comment by theophilusx** [comment] 2019-09-19 23:55
Given you are on Node 9.x, you really need to update to the latest version of the module (4.1.x). There are problems due to changes in node with versions < 2.4.x on node > 8.x. There has also been problems in SSH2 which are only fixed with later versions of that module. Version 2.4.x of the module was the first attempt to fix the main issues. However, it is a breaking change and should have been released as 4.x, but wasn't. The mount of change you will need to perform to update to a working module is going to be the same regardless of the version, so you may as well update to 4.1.x

**Closed by theophilusx** 2019-09-19 23:55 UTC
Labels: more info, question
