### ISSUE TITLE
CLIENT[sftp]: Global: Handling unexpected end event

### ISSUE THREAD

**Issue by KshamaShrey** [theophilusx/ssh2-sftp-client#464] opened 2023-03-06 04:11 UTC
Hi Team,

I am using ssh2-sftp-client in one of my code. I am trying to check whether file is received in one of the sftp folders. I am getting the following error after 10 minutes of waitinng.
Inbound: Received DISCONNECT (11, "Manually close SSH session.")
Socket ended
CLIENT[sftp]: Global: Handling unexpected end event
Socket closed
CLIENT[sftp]: Global: Handling unexpected close event
enters if initially file is not found in sftp
CLIENT[sftp]: list: list: No SFTP connection available

Thanks

**Comment by theophilusx** [comment] 2023-03-06 05:11
You need to provide sample code which reproduces the issue in order to
provide any assistance. There is insufficient information to provide any
additional assistance at this point. In addition to sample code which
reproduces the system, please also indicate

- ssh2-sftp-client version
- node version
- client platform (Linux, Mac, Windows)

**Comment by anibejai** [comment] 2023-03-06 05:45
Hi Team,

Please find the details below:

ssh2-sftp-client version -> 9.0.4
node version -> 16.17.1
client platform -> Windows

Sample code

try {
    await sftp.connect({
        host: hostname,
        port: port,
        username: username,
        password: password,
        retries: 2,
        debug: console.log,
    });
    const data;
    const remote = filePath + "/" + fileName;
    await sftp.put(data, remote);
    await getFilesFromSftp();
} catch (e) {
    console.error(e.message);
} finally {
    await sftp.end();
}
async function getFilesFromSftp() {
    let filefound = false;
    let elapsedTime = 0;
    while (!filefound && elapsedTime < 1500000) {
        const files = await sftp.list(path);
        if (files.length > 0) {
            filefound = true;
            //other logic
        } else {
            await new Promise((resolve) => setTimeout(resolve, 120000));
            elapsedTime += 120000;
        }
    }
}
}

**Comment by KshamaShrey** [comment] 2023-03-06 16:12
`Hi Team,

Please find the details below:

ssh2-sftp-client version -> 9.0.4
node version -> 16.17.1
client platform -> Windows

Sample code

try {
await sftp.connect({
host: hostname,
port: port,
username: username,
password: password,
retries: 2,
debug: console.log,
});
const data;
const remote = filePath + "/" + fileName;
await sftp.put(data, remote);
await getFilesFromSftp();
} catch (e) {
console.error(e.message);
} finally {
await sftp.end();
}
async function getFilesFromSftp() {
let filefound = false;
let elapsedTime = 0;
while (!filefound && elapsedTime < 1500000) {
const files = await sftp.list(path);
if (files.length > 0) {
filefound = true;
//other logic
} else {
await new Promise((resolve) => setTimeout(resolve, 120000));
elapsedTime += 120000;
}
}
}
}`

**Comment by theophilusx** [comment] 2023-03-06 20:36
That cannot be your exact code or an actual working code example. I need
the precise code to run in order to reproduce the issue you are
seeing. AS there are variables in that code snippet, I'm guessing you
have just done a basic cut and paste from your prod code, but not run it
as actual code. I need a minimal example code which reproduces the
issue. Please make a simple script which is complete and both runs and
shows the issue you are seeing. 

Also, please include a debug log from the same bit of code. I will need
to run the code in the testing environments in order to reproduce your
issue. If I cannot reproduce your issue, I cannot help. This is why I
need actual working code which I can run and which I know is precisely
the same code you are running.

Is the sftp server you are accessing also running on Windows?

**Comment by theophilusx** [comment] 2023-04-19 12:42
Unless there is some further updates for this issue, I'm going to close it as I don't see anything further that can be done based on current details.

**Comment by theophilusx** [comment] 2023-04-19 19:01
BTW given the error message and looking at your code, I notice two things 

1. The error message is telling you that your connection has been closed by the remote server. It is also telling you it is a deliberate close i.e. not one caused by error. So the remote server is closing your connection for some reason. My guess, it is timing out because you have gone two long between sending commands. 
2. There is at least one bug I can see in your code. You have the following lines

```js
const data;
const remote = filePath + "/" + fileName;
await sftp.put(data, remote);
```

This will be equivalent to 

```js
await sftp.put(undefined, remote);
```

The supported input for the put() operation is a string, which will be interpreted as a file path, a Buffer or a readable stream. The value 'data' is just an undefined constant. This will likely be a 'noop' and nothing will happen - the function will just return immediately. If you just want to create a test file on the remote server, you could do something like 

```js
await sftp.put(Buffer.from('this is test data'), remtoe);
```

I cannot do more with the provided information. The code provided is not a complete working example - for example, the function getFileFromSftp() references a variable 'path' which is not defined. For all I know, this could be looking in a different directory and as it never finds any files, it just keeps increasing the sleep time until the remote server closes the connection due to inactivity. Note that the keepAliveInterval and keepAliveMax settings won't prevent this - these settings work at the TCP layer and it is likely the timeout and closing of the connection is being managed at the application layer. I would add both debugging which shows what remote directory you are polling and I would add logic to stop after reaching a certain timeout - how long are you willing to wait before giving up? (I'm assuming your doing this because files are being uplaoded from some other application - it doesn't make any sense to do it in your own app if your also doing the file upload).

At any rate, as there has been no updates on this for nearly 2 months, I'm going to close this issue. Added the above info just so it is on the record. If you are still not able to get things working, provide an actual working script which can just be run with `noden <script-name>` and I'll have another look.

**Closed by theophilusx** 2023-04-19 19:01 UTC
