### ISSUE TITLE
downloadDir regex filter doesn't work

### ISSUE THREAD

**Issue by efratha94** [theophilusx/ssh2-sftp-client#319] opened 2021-05-23 08:33 UTC
Hi,
I'm trying to download a directory recursively, using the downloadDir method and the filter option, however, nothing happens at all.
I'm trying to get only csv/html files, that are found in specific directories.

This is my invocation:
`let downDir = await client.downloadDir('/path/to/dir', '/path/to/localDir', /(.+(directoryRegex).+)(.+(\.csv|.html)$)/ )`

And nothing happens.
If I remove the regex filter completely, then everything downloads.

When I hover over the method, it also doesn't show the filter option:
![image](https://user-images.githubusercontent.com/57014350/119253592-a0bd3e00-bbba-11eb-970a-6cf8acb3d5fe.png)

Thanks

**Comment by AndrewLane** [comment] 2021-05-25 11:13
Have you tested your regex in isolation?  Are you sure it's just not matching anything and therefore does "nothing"?

**Comment by efratha94** [comment] 2021-05-25 11:15
Yeah, I'm using it in a process in Nifi which does that exactly, it's the same regex. Also checked with regexr and it's definitely correct.

**Comment by AndrewLane** [comment] 2021-05-25 11:18
Looks like there's some debug functionality that you can turn on with flags.  Have you tried that just as a sanity check?  https://github.com/theophilusx/ssh2-sftp-client/blob/master/src/index.js#L332

**Comment by theophilusx** [comment] 2021-05-25 23:01
I suspect the problem is that your filter regexp is expecting a full
path to match on. This is not how the code works. It uses the list()
method to filter out entries from each directory level. At each level,
you get a list of directory entries, which are either directory names or
file names. It does not see a full path name. Therefore your filter
needs to match either a directory name or a file name e.g.
/(directoryRegex | (\.csv$ | \.html$)) or similar.

**Comment by efratha94** [comment] 2021-05-26 05:33
So basically I need to give it a relative path instead of a full path?

**Comment by theophilusx** [comment] 2021-05-26 06:06
You give a relative or full path to the initial directory. The function
will then read that directory to get a listing of contents. It will
apply the filter to each item in that listing (which is either a
directory or file name). If the entry is a filename and it matches the
filter, it will download that file. If the entry is a directory and
matches the filter, it will append it to the original path, get a
listing and repeat the process, recursing down into the directories
which match the filter. The function will create the directory locally
so that the basic 'shape' of what is downloaded is maintained (keeping
in mind that the filter might adjust that shape by excluding some directories/files).

The original path you specify can be absolute or it can be relative to
whatever the current working directory of the connection is. i.e. if
when you login to the sftp server, the 'home' directory is /home/user
and the root of the directory tree you want to download from is in a
subdirectory call target, you could specify the path as
'/home/user/target' or you could specify it as './target' (because the
current remote working directory is already /home/user.

The key point is that your regexp should not be defined to match the
full remote path. It is only matched against entries in each directory
starting at the directory you specify in the call to the function.

**Comment by theophilusx** [comment] 2021-06-04 07:54
I am releasing a new version of ssh2-sftp-client in about a week or so. The new version is based on the new ssh2 v1.1.0 module. I am therefore going to close this issue. 

If you still have problems, please try using the master branch and see if that makes any difference. We can open a new issue against the new version if necessary.

**Closed by theophilusx** 2021-06-04 07:54 UTC
