### ISSUE TITLE
Version 8.0.0

### ISSUE THREAD

**Issue by obrhaberer** [theophilusx/ssh2-sftp-client#402] opened 2022-04-06 13:19 UTC
I use this package inside a github-action runner (ubuntu latest). The new version takes longer to upload than before (In my usecase 1:40min to 2:30min). Also new warnings are shown:

(node:2056) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2056) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(node:2056) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Client]. Use emitter.setMaxListeners() to increase limit

**Comment by theophilusx** [comment] 2022-04-07 00:30
Hmm, I replied to this message via email, which use to add my reply to the issue, but it does not seem to have done so this time. I'll update now so that it is recorded on the issue. 

Thanks for the issue report. However, there is nowhere near sufficient information in your report to enable me to do anything. To address this issue, I first need to be able to reproduce it.  Things which would help

- What node version?
- What version of ssh2-sftp-client were you running previously?
- Do you have any custom on() handlers defined? 
- What methods are you calling (uploadDir(), put()? etc). I have no idea what you are trying to do. Just telling me your running this as part of a github aciton tells me nothing. 
- If using uploadDir()/downloadDir(), did you update your code to work with the changed method signature? Are you using a predicate filter function? 
- If not using uploadDir()/downloadDir(), are you using put()/get() or fastPut()/fastGet()? If put()/get(), what parameters are you using (string paths, buffers, streams)? 
- Can you provide a debug log which might help narrow down the issue?

Ideally, a minimal recipe/script to reproduce the issue is necessary for me to address it. If I cannot reproduce it I cannot fix it. The module has nearly 300 unit tests, which are all passing. This means that either the issue is due to a bug in your script or there is something specific in your environment which I have not covered in my tests. 

The only changes in v8.0.0 from v7.2.3 were in rmdir() and uploadDir()/downloadDIr(), which might help you narrow down where the issue is triggered. 

Ideally, a minimal script which reproduces the issue (possibly with a description of the size/type of data) will help ensure this issue is resolved quickly.

**Comment by obrhaberer** [comment] 2022-04-07 15:33
So basically this is the script:

    await client.connect(config)
    client.on('upload', info => console.log(`Listener: Uploaded ${info.source}`))
    client.on('error', info => console.error(`Listener: Error ${info}`))
    client.on('end', () => console.log(`client disconnected`))
    await client.rmdir(dstDir, true)
    const res = await client.uploadDir(srcDir, dstDir)

previously it was v7.2.3 running - node version 16

**Comment by theophilusx** [comment] 2022-04-07 22:34
thanks. Nothing obvious jumps out from the script. The error handler you have added should not be necessary, but it should do no harm as well.  Do you know if the warnings about listeners are being raised during the rmdir() or uploadDir() calls? Can you first run your scirpt with uploadDir() commented out and then run it a second time with rmdir() commented out and uploadDir() uncommented. Also, can you turn on debugging by adding a debug function to the config object. 

Can you also provide some details regarding the size/shape of the directory tree being deleted and the one being uploaded? My suspicion is that the problem is with the changes to rmdir() and the number of promises being created is too high. This could result in too many listeners being added (the default limit is 11) and I guess, if the number is excessive, degrade speed (though that is a little odd. All the tests on large directory trees showed a large improvement i.e. drop from 12 minutes to around 1 minute). 

Are you in a position to help debug this? I suspect the issue is very specific to your environment and it will be difficult for me to reproduce.

**Comment by obrhaberer** [comment] 2022-04-08 14:38
The warnings come from the rmdir() function, but as you said, this one has improved from your update ragarding to performance.

As for the upload it's about 35 MB in total for 130 objects (biggest file is 26 MB) which takes up to 1 minute longer than with the previous version.

What are you looking for in the debugging, as I am not able to share from an ip-perspective?

**Comment by theophilusx** [comment] 2022-04-08 22:12
OK, that seems in-line with what I suspected. Can you provide some details on the shape of the directory tree you are removing with rmdir() i.e. how many directories deep, how wise (i.e. how many items in each directory). I need to create a similar shape tree to mimic the recursive and async calls to help track down where the listener 'leak' is occurring. 

The slower upload speed is odd. The only change to uploadDir/downloadDir functionality was to replace the 3rd argument with a function rather than a regular expression. In fact, if your not providing a 3rd argument, no calls to filter happen at all (previously, a call to filter always happened, but the default regexp was to match everything). The only other change was to go from ssh2 1.8.0 to ssh2 1.9.0.  It wold be interesting if you were to change the dependency in ssh2-sftp-client's package.json to use ssh2 1.8.0 and run it again to see if it is faster. 

> What are you looking for in the debugging, as I am not able to share  from an ip-perspective?

What I am looking for is assistance in tracking down, testing and resolving this issue. I really don't care about IP issues. In fact, I would argue that if your employer wants to use open source software to benefit their IP, they have a moral responsibility to contribute back.  Regardless, the bottom line is that if I cannot reproduce the issue you are seeing, it makes it very difficult to fix and impossible to know when I have. If you are the only one who can reproduce the issue, essentially, you are the only one who can effectively debug it. 

At this point, the main focus is on the rmdir() method. I doubt there is much I can do about the uploadDir() performance. One thing which would be good is a debug log from the rmdir() call. It is fine if you have to 'mask' file/directory names in some manner. It will also probably be necessary to run this many times as I will likely need to add additional debugging/logging information (you will have to run from the github repo rather than the npmjs package when I do make changes).

**Comment by obrhaberer** [comment] 2022-04-08 22:42
Nested directory - depth 5, max filecount 59

The change to ssh2 1.8.0 has not changed performance.
For now I stick with version 7.2.3.

**Comment by obrhaberer** [comment] 2022-04-08 22:52
I have to apologize - the slower performance was first noticed in 7.2.2 which makes sense because you have changed the usage of eg fastPut. Is there a flag one can set to activate again?

So as for 8.0.0 it is just the Possible EventEmitter memory leak.

**Comment by theophilusx** [comment] 2022-04-08 23:31
OK, that now makes more sense. No, there is no switch to select fastPut instead of put. Unfortunately, there were just too many sftp servers which did not support fastPut to keep it as the default. I do have a note to add a switch which would allow fastPut, but not sure when I will get to that.

**Comment by theophilusx** [comment] 2022-04-08 23:37
> Nested directory - depth 5, max filecount 59

Thanks, that helps. Do any/many of the sub-directories contain other directories? I think I know where the problem is. However, might be a little tricky to find a solution which also protects against too many asynchronous calls at a time.

**Comment by theophilusx** [comment] 2022-04-09 03:02
I have made a small change to rmdir() which I think should address the max listeners warning. Can you try running the master branch from the github repository?

**Comment by theophilusx** [comment] 2022-05-17 08:50
Have pushed out version 8.1.0 which incorporates the small change to `rmdir()` so that it only does asynch calls for file deletion and not recursive directories. I believe this fixes the observed issue, so closing this issue now.

**Closed by theophilusx** 2022-05-17 08:50 UTC
