### ISSUE TITLE
Filter callback for directory upload / download

### ISSUE THREAD

**Issue by Jaaahn** [theophilusx/ssh2-sftp-client#352] opened 2021-09-21 19:42 UTC
The filtering of which files to exclude from uploading using a regular expression is a great idea. But I think that it would be better if one could also pass a callback as a filter in order to write their own filtering code.

Therefore, what about changing these lines
https://github.com/theophilusx/ssh2-sftp-client/blob/1d3b7e35586e367190a7d21ed9989b09513f9d68/src/index.js#L1094-L1098
into something like
```js
let dirEntries = fs.readdirSync(srcDir, { 
   encoding: 'utf8', 
   withFileTypes: true, 
 }); 

if(typeof filter == "function") {
  dirEntries = dirEntries.filter(filter);
} else {
  dirEntries = dirEntries.filter((item) => filter.test(item.name)); 
}
```
(would also need to be done in the `downloadDir` method).

If you want, I could try to implement this in a PR but since I'm somewhat new to open source and I doubt I fully understand how this repo works, I wanted to ask you first.

**Comment by theophilusx** [comment] 2021-09-22 02:26
I guess this could be useful if you wanted to filter on something other
than filename. My reservation is whether this addition will cause any
API confusion and lead to increased issues being raised. For example,
not all platforms can provide group/other access mode information (e.g.
windows sftp servers) and someone trying to filter on access modes and
not getting the right result will likely log an issue, which I then have
to dig into only to find the problem is because the server they are
accessing is on a different platform.

I tend to be very conservative with respect to adding new features. In
addition to making maintenance more complex, by far the majority of
issues I need to resolve are due to API misuse by clients. Therefore,
keeping the API as simple as possible is important and I tend to only
add features when either they are very straight-forward or there is a
demonstrated demand for them. I also don't want to add too many 'high
level' features - uploadDir/downloadDir was one I was hesitant to add
because it was easy to implement in client code. However, enough people
asked for this feature, so I added it.

Your the first to ask for a filter function and while modifying the code
to support it isn't complicated, it will require adding quite a few
additional tests and it all adds to maintenance overhead.

I'm on the fence with this one. Need some time to consider it.

**Comment by theophilusx** [comment] 2022-03-28 05:34
I have reworked the updloadDir and downloadDir methods so taht now they take an optional filter function. The function will be called with two arguments - the first is the full path of the 'object' to be uploaded/downloaded and the second is a boolean, which will be true if the target is a directory. 

The filter function should return true if the object is to be included in the upload/download and false otherwise. 

This new version will be in the next release (v8.0.0). Just waiting on some other people doing tests on other changes for v8.0.0 before pushing out the new version. 

Going to close this issue now.

**Closed by theophilusx** 2022-03-28 05:34 UTC
Labels: enhancement
