### ISSUE TITLE
Error: connect->getConnection: Unexpected end event raised 

### ISSUE THREAD

**Issue by NTPac** [theophilusx/ssh2-sftp-client#429] opened 2022-08-14 01:34 UTC
hi ad, my batch had error like this:
![image](https://user-images.githubusercontent.com/54607973/184518752-2ae90802-0317-4333-99c9-339783300edd.png)
my version sftp is     "ssh2-sftp-client": "^7.2.0",
my node version in image docker is "node:alpine3.14"

my source code:
try {
    await sftp.connect(config);
  } catch (error) {
    console.log('[export] Error: ', error.message);
  } finally {
    try {
      if (sftp) {
        await sftp.end();
        logger.info(SourceName, ProcedureName, ' ', 'sftp end');
      }
      logger.info(SourceName, ProcedureName, ' ', 'finally');
    }
    catch (error) {
      logger.err(SourceName, ProcedureName, error.code, '[export] Error: ' + error.message + '\t' + error.stack);
    }
  }
  
 thank you!

**Comment by theophilusx** [comment] 2022-08-14 02:16
You first need to update to ssh2-sftp-client 9.0.3. 

Not sure what version of node you are running there "node:alpine3.14" is not a standard node version name - I'm guessing it is node v14. There has been a number of fixes in ssh2 since the release of v7.2.0. If the error persists after upgrading, I will need a small script which is able to reproduce the problem in order to diagnose further. 

Note that in all other issues reported involving docker, the problems were due to underlying problems with the docker networking stack. I would also test using something like openSSH sftp CLI under load to see if the issue also occurs when using the CLI. If possible, running your batch script outside of docker may also be informative.

**Comment by theophilusx** [comment] 2022-09-04 21:38
As there has been no follow up on this issue for 3 weeks and a new version of the module has been released, I am closing it for now. Suspect it was a local issue as unable to reproduce in test environment.

**Closed by theophilusx** 2022-09-04 21:38 UTC
