### ISSUE TITLE
fastGet: Invalid HMAC

### ISSUE THREAD

**Issue by saurabhsinghhauhan** [theophilusx/ssh2-sftp-client#241] opened 2020-06-06 16:29 UTC
I'm using ssh2-sftp-client and trying to download a file of 15MB from server by following code.

 **ssh2-sftp-client "^5.1.2" 
 node 13.3.0**

```
let Client = require('ssh2-sftp-client');
let sftp = new Client();

await sftp.connect({
    host: '***',
    port: '***',
    username: '***',
    password: '***',
    debug: function (str) {
        console.log(str)
    }
})

await sftp.fastGet('Source', 'Target');
```

But after 2-3MB I'm getting following error

```
{
"code":"ERR_GENERIC_CLIENT",
"custom":true,
message:"fastGet: Invalid HMAC"
stack:"Error: fastGet: Invalid HMAC
    at formatError (/home/saurabhsinghchauhan/Downloads/creditro/phoneservice/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at Client.<anonymous> (/home/saurabhsinghchauhan/Downloads/creditro/phoneservice/node_modules/ssh2-sftp-client/src/utils.js:116:12)
    at Client.emit (events.js:219:5)
    at SSH2Stream.<anonymous> (/home/saurabhsinghchauhan/Downloads/creditro/phoneservice/node_modules/ssh2/lib/client.js:359:10)
    at SSH2Stream.emit (events.js:224:7)
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at onwriteError (_stream_writable.js:470:3)
    at processTicksAndRejections (internal/process/task_queues.js:86:21)
}
```

Is there a way to overcome this issue?

**Comment by theophilusx** [comment] 2020-06-07 01:10
That error is from the ssh2/ssh2-streams modules. It is odd you are
getting that part way through a download. You would typically see that
error when first attempting to connect.

I would suggest upgrading your node version to a more current 13.x. The
13.x is a development branch and that version is quite old. Current v13
is 13.14.0. Ideally, I wold use v12.x (LTS version). I have been testing
14.x and found some issues due (I think) to changes in the node streams
libs (see below). I did test against 13.14.0 a week or so ago and all
tests passed.

Here is what I would do

1. Use openssh sftp to download the file multiple times to eliminate any
lower level network issues. Use the verbose debugging flags to see
exactly what ciphers and key exchange algorithms are being used.

2. Run ssh2-sftp-client script with the debug option (as you have been
doing) and note what cipher, key exchange and hmac algorithms are being
used. If they are different to the ones being used by openssh, you may
need to configure them to be the same using the algorithms property of
the connect options object (see the ssh2 documentation for details).
Note that the names used y node and openssh for the various algorithms
are slightly different, but you will see how they map easily.

3. If that still doesn't work, write a very simple script that only uses
ssh2 and ssh2-streams. See the tools directory in the github repo for
ssh2-sftp-client. There is a script called lowlevel-fastget.js you can
start with. If you still get the error, then you know the problem is
with either the ssh2 or ssh2-streams module. This will enable you to log
a job with the maintainer of that module (who is far more knowledgeable
about ssh2 and ssh2-streams than me).

4. Try modifying your script to use get() instead of fastGet(). I was
recently testing ssh2-sftp-client against node 14.2 and found a problem
with fastGet/fastPut in the ssh2-streams library (I have logged a job
with the maintainer of that module). I found get() worked fine. While
the error did not happen with the node 13.14 version I was running,
there is a chance your older version of 13.x has issues.

It would also be worthwhile checking the issue logs for the ssh2 module.
It is possible others have encountered a similar problem. These issues
hold a wealth of information I've found useful.

**Comment by theophilusx** [comment] 2020-06-22 06:59
Have you been able to make any progress on this issue?

**Comment by theophilusx** [comment] 2020-07-07 00:27
As I cannot reproduce this issue and there has been no feedback for over 2 weeks, I'm closing it for now

**Closed by theophilusx** 2020-07-07 00:27 UTC
Labels: more info
