### ISSUE TITLE
Unable to get a binary file

### ISSUE THREAD

**Issue by vumaasha** [theophilusx/ssh2-sftp-client#116] opened 2019-01-26 06:27 UTC
I am trying to download (get) a file (size of 16MB) from sftp server using ssh2-sftp-client, the program does not terminate and hangs even after the events end, close is triggered on the ReadableStream and the events finish and close are triggered on the WriteableStream. Below is the program and it's output. There are no errors as well, how do I debug?
```

const Promise = require("bluebird");
const fs = require("fs");
const Client = require("ssh2-sftp-client");
const util = require("util");


const sftp = new Client();
const path = require("path");
const openpgp = require("openpgp"); // use as CommonJS, AMD, ES6 module or via window.openpgp

openpgp.initWorker({
    path: "openpgp.worker.js"
}); // set the relative web worker path

const config = {
    host: 'xxxx',
    port: '1111',
    username: 'xxxx',
    password: 'xxxx'
};

function getFileFromSFTP() {
    console.log("Program Execution started");
    /* get files from SFTP */
    const remotePath = "remoteFile";
    const localPath = "localFile"
    sftp.connect(config).then(() => {
        sftp.get(remotePath, true, null).then((data) => {
            data.on('error', (e) => {
                console.log(e);
            });
            data.on('end', () => {
                console.log("rs end");
            });
            data.on('close', () => {
                console.log("rs closed");
            });
            data.pipe(fs.createWriteStream(localPath).on('error', (e) => {
                console.log(e);
            }).on('finish', () => {
                console.log("ws finish");
            }).on('close', () => {
                console.log("ws close");
            }));
        });
    });
}

function init() {
    getFileFromSFTP();
}

init();
```

# output
> node index.js

Program Execution started
rs end
ws finish
ws close
rs closed

**Comment by rkaw92** [comment] 2019-01-29 23:09
Hi, you're still connected to the server, so Node will not exit. This is expected behavior. Your file should still be OK.
If you need to do a single-run transfer and exit the program, consider using `sftp.end()` or `process.exit()`.

**Comment by jeffrson** [comment] 2019-02-20 14:45
I came here because downloading doesn't work for me at all.

The example above simply shows "Program Execution started", then the script hangs. Actually it connects, because console.log inside .then is shown. But the stream isn't read.

data.isPaused() stays true.

**Comment by theophilusx** [comment] 2019-03-03 23:11
Likely duplicate of #106 

Seems there is an incompatibility with Node 10.x and stream handling. I think this is fixed in my fork at https://github.com/theophilusx/ssh2-sftp-client. I will do a PR once I'm happy with the changes. Note that the changes are breaking changes which alter the API.

**Comment by theophilusx** [comment] 2019-03-11 04:31
This issue is resolved with the new version and therefore can be closed.

**Closed** 2019-08-22 07:02 UTC
