### ISSUE TITLE
Get method called with relative path

### ISSUE THREAD

**Issue by VandalSausage** [theophilusx/ssh2-sftp-client#381] opened 2022-01-14 09:41 UTC
Heya,

Love this library, I've been using it at work for ages and it's saved me hours of pain.

I've enountered an issue in v7 with relative paths. 

When the `exists` method on the Client class is called it uses the `normalizeRemotePath` util before handing the path to the server and checking whether the file/directory exists. 

When the get method is called it hands the relative path directly to the server without calling the util `normalizeRemotePath`.

We check for a file using the `exists` and then retrieve it using the `get`.

For a small subset of clients (and I'm struggling to get concrete specifications for their servers), the `exists` method will return `true` but the `get` method will reject because the server cannot process the relative path.

On my end i'm just going to import `normalizeRemotePath` from utils and call it before I use `get` - but my question is: is there any reason that doesn't happen already internally?

Let me know if you need any code snippets - I'd also be very happy to make a small PR to this effect if that's the right course of action.

**Comment by theophilusx** [comment] 2022-01-14 21:33
Can you confirm exactly which version of ssh2-sftp-client you are using?

There were some path check changes in v7 intended to improve
performance. The challenge is in getting the balance correct so that as
few as possible requests are made, but the client also gets informative
error messages that help pinpoint problems accurately (some ssh2
operations result in very terse and unhelpful error messages). It is
possible I've been a little too zealous and taken out checks I should
have left in. A couple of other small path related issues have already
been patched (why it is important I know exact version you are using). 

A simple script which reproduces the issue would help a lot as it will
ensure I've got a full picture and I should be able to adapt it to add a
new test.

Would also be good to know what platform your running the client on (as
well as the remote server platform if you know it).

**Comment by VandalSausage** [comment] 2022-01-28 18:21
Hey, sorry was off sick.

Code is fairly simple - 

(if you imagine in this example we're connecting to a server which by default lands the connection in user/home/

```javascript
const sftp = new Client (options)

await sftp.connect()

const relativeFilePath = "./path/to/file.csv"

const exists = !!sftp.exists(relativeFilePath)

// debugger logs: exists -> /user/home/path/to/file.csv

if(exists){
sftp.get(relativePath, writeStream)
}

// debugger logs: get-> ./path/to/file.csv

```

this will occasionally will throw an error where the server cannot parse the given path on the get call, because it's not converted to an absolute path.

we've accounted for this by transforming the path before the call, but it seems odd for these two methods to hand different paths to the server.

we're running this on a node 12 (I know) ubuntu container.

version is 7.0.0 although I can reproduce on 7.2.1

it's been basically impossible to get through the wall of consultants to anyone that could give me remote server specs

**Comment by theophilusx** [comment] 2022-01-29 01:14
Firstly, please ensure you are using 7.2.1. There are definite bugs in
versions prior to 7.2.1 (in both ssh2-sftp-client and in the underlying
ssh2 version it uses).

Note that your example has a bug. I'm guessing it isn't your 'real'
code. The line

> const exists = !!sftp.exists(relativeFilePath)

assigns the promise returned from the exists call, not the fulfilled
value of the promise. It needs an await. I would also not do the !!.
Instead, I would test the return value is '-' (your code willl assume a
'true' value is a path to a file - it could be a path to a directory, in
which case, get() will fail.

> we've accounted for this by transforming the path before the call, but it seems odd for these two methods to hand different paths
> to the server.

They don't. How they are processed by the remote server is different.

When you call exists(), the path you send is 'normalised' using a call
to realPath() on the remote server. The value from that call is then
used in a call to stat() (using the absolute path returned from
realPath()) to determine the type of remote object (file, directory,
link).

When you call get(), passing in a relative path, it is the server which
converts the relative path to an absolute path and returns the read
stream used to get the data.

If it sometimes works and sometimes fails, I would be looking for a
missing await or similar. This has tyhpically been the symptom of an
error in client code. While it could be a problem with the remote
server, this is rare. The somtimes works and sometimes fails is often a
symptom of an async timing issue. When it works, you were 'lucky' and
when it fails, it is due to some part of your code trying to access data
before it is available. 

To diagnose further, I need to see the exact error being thrown. A full
debug log would also help as would actual working code being used.

You may also find some of the scripts in the validate directory of the
ssh2-sftp-client repository useful. These scripts implement basic
functions using just ssh2 (no ssh2-sftp-client) and can be useful in
identifying where the error migh be (i.e. in ssh2 or ssh2-sftp-client).

Make sure you are using at least node v12.22.9. A more recent version
would be better, but if your stuck on v12, at least ensure it is the
current version of v12.

You might also want to see if you can reproduce the issue using the
current HEAD of the ssh2-sftp-client repository. There are some bug
fixes I've been waiting to release (expecting a new version of ssh2,
addressing some other issues).

In general, I think it is always better to use absolute paths if you
can. Some servers can do some unexpected things with relative paths,
plus absolute paths are more efficient as it avoids the need to
normalise the path in every call. I will often start with a call to
realPath('.') to get the path root and prepend that to all the get/put
calls I then make so that your passing in absolute paths.

**Comment by theophilusx** [comment] 2022-01-31 07:26
I'm pushing out a new 7.2.2 version, which is based on an updated ssh2 version (1.6.0). Please test and see if your issue still exists with the new version.

**Comment by theophilusx** [comment] 2022-02-28 05:32
As there has been no further feedback on this issue and new versions of both ssh2 and ssh2-sftp-client have been released since it was first raised, I'm closing this issue for now.

**Closed by theophilusx** 2022-02-28 05:32 UTC
