### ISSUE TITLE
Folder not found, when It is there when remote platform is windows

### ISSUE THREAD

**Issue by mfatima21** [theophilusx/ssh2-sftp-client#374] opened 2021-12-26 12:27 UTC
Node version: v10.22.1
Version of ssh2-sftp-client: "^7.0.0"
Platform your client is running on: Windows
Platform and software for the remote SFTP server: Unix

### Issue:

The remote platform where the client upload its files is Windows. The server for the sftp service is running on linux.

The whole file transfer works fine when the remote platform is also unix. But the issue occurs when the remote platform is windows. The package does not pick the remote platform correctly. Hence the following issue occurs.

```
Error while listening to Digicust Error: list: Folder not found: out/ out 
at readableAddChunk (internal/streams/readable.js:267:9)
at addChunk (internal/streams/readable.js:293:12)
at Socket.emit (events.js:400:28)
at Socket. (/usr/src/app/node_modules/ssh2/lib/client.js:713:21)
at Protocol.parse (/usr/src/app/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
at Protocol.parsePacket [as _parse] (/usr/src/app/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
at GenericDecipherBinding.decrypt (/usr/src/app/node_modules/ssh2/lib/protocol/crypto.js:1418:26)
at Protocol.onPayload (/usr/src/app/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
at 94 (/usr/src/app/node_modules/ssh2/lib/protocol/handlers.misc.js:859:16)
at CHANNEL_DATA (/usr/src/app/node_modules/ssh2/lib/client.js:525:23)
at SFTP.push (/usr/src/app/node_modules/ssh2/lib/protocol/SFTP.js:278:11)
at 101 (/usr/src/app/node_modules/ssh2/lib/protocol/SFTP.js:2622:11)
at Object.reread [as cb] (/usr/src/app/node_modules/ssh2/lib/protocol/SFTP.js:888:18)
at /usr/src/app/node_modules/digicust_helpers/node_modules/ssh2-sftp-client/src/index.js:405:20
at fmtError (/usr/src/app/node_modules/digicust_helpers/node_modules/ssh2-sftp-client/src/utils.js:55:18)

at Socket.Readable.push (internal/streams/readable.js:206:10) {
  code: 4,
  custom: true
}
Finished SFTP Listening
```
I am mentioning the code here as well.

### Client connection:

```
import Client from "ssh2-sftp-client"

  private async reinitializeClient() {
    this.client = new Client()
    console.log("client reinitilization")
    await this.client.connect({
      host: this.sftpDnsName,
      port: Number(this.sftpPort),
      username: this.sftpLoginName,
      password: this.sftpPassword,
      remotePathSep: this.remotePathSep,
      remotePlatform: this.remotePlatform,
      // @ts-ignore
      algorithms: {
        serverHostKey: [
          "ssh-rsa",
          "ssh-dss",
          "ssh-ed25519",
          "ecdsa-sha2-nistp256",
          "ecdsa-sha2-nistp384",
          "ecdsa-sha2-nistp521",
          "rsa-sha2-512",
          "rsa-sha2-256",
        ],
      },
    })
  }
```

### Config for connection
The config that is being passed for client connection is as follows:

```
{
        "sftpPassword": <password>,
        "sftpLoginName": <login name>,
        "sftpPort": "22",
        "sftpDnsName": <Dns name>,
        "sftpInboundPath": "out",
        "sftpOutboundPath": "out",
        "remotePathSep": "\,
         "remotePlatform": "windows",
}
```

### Reading from the client's folder 

```
  public async readFromOutbound(configuration?: {
    deleteAfterRead?: boolean
  }): Promise<
    { content: string | Buffer | NodeJS.WritableStream; filename: string }[]
  > {
    const files: {
      content: string | Buffer | NodeJS.WritableStream
      filename: string
    }[] = []
    console.log("reinitilizing client")
    await this.reinitializeClient()
    console.log("list", await this.client.list(`${this.outboundPath}`))
    await asyncForEach(
      await this.client.list(`${this.outboundPath}`),
      async (file: Client.FileInfo) => {
        if (!file?.name?.startsWith(".") && file?.type !== "d") {
          console.log(`New file found: ${file.name}`)
          const remoteFilePath = `${this.outboundPath}${this.remotePathSep}${file?.name}`
          console.log(remoteFilePath)
          files.push({
            content: await await this.client.get(remoteFilePath),
            filename: file.name,
          })
          if (configuration?.deleteAfterRead) {
            await this.client.delete(remoteFilePath)
          }
        }
      }
    )
    return files
  }
```

Also, I found this line in the package where we are assigning the remote path and platform to unix by default.
https://github.com/theophilusx/ssh2-sftp-client/blob/684eb5f31a695b7592f8cb7357701fee7a48646b/src/index.js#L34

What should I do to read from a windows machine. 
Thanks.

**Comment by theophilusx** [comment] 2021-12-26 14:01
The first thing you need to do is update ssh2-sftp-client to 7.2.1

The 7.0.0 version was the first version released using the new 1.x
version of ssh2. Both ssh2 and ssh2-sftp-client had some bugs which have
been fixed in later versions. Therefore, you need to start with that
version and see if you can reproduce the issue.

I would also strongly recommend updating node to at least v12. Node v10
has been end of life for some time now (even v12 is end of life at the
end of next April).

Once you have upgraded ssh2-sftp-client to 7.2.1, if your issue still
occurs, please post a debug log and I'll have a look. A minimal script
which reproduces the issue is also helpful.

Looking at the errors you have, they appear to be from ssh2. If this
turns out to be the case, it will be necessary to log an issue with the
ssh2 project. This will also require a script which demonstrates the
problem, but which only uses ssh2 and not ssh2-sftp-client. There are
some example scripts in the validate directory of the ssh2-sftp-client
repository which only use ssh2 and which you should be able to adapt to
reproduce the issue.

If the issue cannot be reproduced with ssh2, then it is likely the issue
is with ssh2-sftp-client and I'll need to dig deeper. However, based on
what I can see from the data you provided, I think that is unlikely.

**Comment by mfatima21** [comment] 2021-12-27 07:44
Thank you for your quick response. I'll try the changes that you have suggested and update you again soon.
Thanks again.

**Comment by mfatima21** [comment] 2021-12-27 10:53
Your suggestions worked for me. Thanks again!

**Closed** 2022-01-20 05:51 UTC
