### ISSUE TITLE
Infinite loop creating a folder without permission

### ISSUE THREAD

**Issue by MeloJR** [theophilusx/ssh2-sftp-client#213] opened 2020-02-11 10:03 UTC
Hi!
I have found a problem when I try to create a directory in a destination without permission to write directories. I have encountered this problem with `uploadDir` and `mkdir` methods. Here is a stack of the debug messages.

```
DEBUG: Parser: pktLen:60,padLen:17,remainLen:48
Folder.js:34
DEBUG: Parser: IN_PACKETDATA
Folder.js:34
DEBUG: Parser: Decrypting
Folder.js:34
DEBUG: Parser: HMAC size:32
Folder.js:34
DEBUG: Parser: IN_PACKETDATAVERIFY
Folder.js:34
DEBUG: Parser: Verifying MAC
Folder.js:34
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
Folder.js:34
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
Folder.js:34
DEBUG[SFTP]: Parser: Response: STATUS
Folder.js:34
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
Folder.js:34
DEBUG[SFTP]: Outgoing: Writing STAT
Folder.js:34
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
Folder.js:34
DEBUG: Parser: IN_PACKET
Folder.js:34
DEBUG: Parser: Decrypting
Folder.js:34
DEBUG: Parser: pktLen:60,padLen:17,remainLen:48
Folder.js:34
DEBUG: Parser: IN_PACKETDATA
Folder.js:34
DEBUG: Parser: Decrypting
Folder.js:34
DEBUG: Parser: HMAC size:32
```

I don't know how to stop this loop. Is there any solution?

**Comment by theophilusx** [comment] 2020-02-11 12:55
Can you provide -

- node version
- ssh2-sftp-client version
- platform your running node on
- remote sftp server platform (if known)

As uploadDir uses mkdir() under the hood, I suspect the issue is with
mkdir()

It is likely an issue with not picking up the error correctly, so
promise is not rejected - though this seems odd.

I will try to reproduce. If you can provide a minimal code example that
reproduces the issue using mkdir() that would be great. Really help if
you can provide details regarding the file/directory hierarchy and what
permissions the directories do have so I can reproduce something
similar.


In the meantime, you can possibly use stat() and exists() to identify
which directories you don't have necessary write permissions on and then
try using chmod() to set them or throw your own error and avoid trying
to upload data if you don't have necessary permissions.

**Comment by MeloJR** [comment] 2020-02-11 13:58
**Node version:** v11.12.0
**ssh2-sftp-client:** 5.0.2
**Platform:** Windows 10
**Remote server platform:** Ubuntu 18.04.2 LTS (Bionic Beaver)

The hierarchy of directories is simple, we have a folder per client, and when we enter with a user-password he only has access to his folder. We need to check the permissions of the user in order to solve de problem, but I think it will be a good idea to post the issue here.

Thank you for the solution with `stat()` and `exists()`.

Here is the code:
```
const client = new SFTP();
try {
    await client.connect({
      host,
      port,
      user,
      password
    });
    await client.mkdir(pathname, true);
} catch (err) {
    console.log(err)
    throw err;
}
client.close()
```

**Comment by theophilusx** [comment] 2020-02-11 19:24
OK, that info helps a lot.

One more questions. Are the remote pathnames absolute or relative?

thanks.

**Comment by theophilusx** [comment] 2020-02-11 21:35
Tried many different combinations of path and cannot reproduce the issue when going from linux to linux using same node version. Looks like it might be something specific to Windows 10 platform?

**Comment by theophilusx** [comment] 2020-02-11 22:16
I cannot reproduce this going from windows 10 to Ubuntu either. No matter what combination of permissions, existing and non-existing directories and permissions I try, whenever there is a lack of permission, I get a bad permission error and no infinite loop. If I cannot reproduce, I cannot debug. 

In the example dirctory of the repo is a script called mkdir.js. Can you try using that script and see if you can reproduce the same infinite loop. 

Also, what are you using as the sftp server on the ubuntu system? Openssh or something else?

**Comment by MeloJR** [comment] 2020-02-13 16:31
I will do the test tomorrow with the script mkdir.js. Can I activate some kind of debug option in order to give you more information?

**Comment by theophilusx** [comment] 2020-02-13 23:28
Currently it is just a simple example script and the same as the one I
use for testing, but without any debug option. That is a good idea. I
will add a debug flag with some additional debugging output.

**Comment by theophilusx** [comment] 2020-02-15 08:36
OK, please use the add-debug branch of the repo. You can call the mkdir.js script with an additional argument 'debug' e.g.

`node mkdir.js /path/to/create/dir debug`

and it will produce lots of debugging info.

**Comment by theophilusx** [comment] 2020-02-16 18:56
Note that the additional debugging support is now part of the master branch, so just checkout master and run the scirpt and send me the output.

**Comment by theophilusx** [comment] 2020-03-01 23:40
Is there any update for this issue?

As I cannot reproduce it, unless there is more info to work with I cannot provide any more assistance and will therefore close this issue.

**Comment by MeloJR** [comment] 2020-03-02 10:19
I'm sorry but I didn't have time. Today I have made this execution: `node mkdir.js test debug` and it enters in infinite loop. I attach the log
[log.txt](https://github.com/theophilusx/ssh2-sftp-client/files/4274744/log.txt)

I did another execution changing the path to an absolute path: `node mkdir.js /test debug` and it fails with Permission denied. The same with `node mkdir.js ./test debug`. 

Maybe our problem with permissions is similar to one described here: https://serverfault.com/questions/917042/sftp-client-cant-write-to-own-home-directory-when-chrooted-there
because we can create directories inside another directories but not in the root.

**Comment by theophilusx** [comment] 2020-03-02 16:52
OK, I think I may know what the problem is. You cannot just put 'test' as a path. The sftp server needs to know what the directory is relative to. Either you need to use ./test or ../test or /absolute/path/to/test or ./relative/path/to/test or ../relative/to/parent/test etc. 

I will try and update the section on paths in the README to make this clearer. I'll also see how hard it will be to add a test to prevent the infinite loop when someone uses a bad path specification. However, this is tricky as different platforms use different path formats and it is difficult to come up with something which works reliable on all systems (the main ones are fairly obvious, but there are some more obscure ones, some of which I  probably don't know). 

BTW I think that SO article you linked to has more misleading/bad information in it than good. It isn't clear exactly what the OP was trying to do, but if you want a chroot'd SFTP server, you need to setup a dedicated sftp module (for open SSH like gesftpserver) or a dedicated SFTP server software. You then also need to configure and manage users (unlike just using ssh built-in sftp service for home directories).

**Comment by theophilusx** [comment] 2020-03-02 18:07
OK, I think I've fixed this issue now. If an invalid path is specified (ie one where we cannot determine parent directory), an error is now raised rather than an infinite loop. I have also updated the README to make it clearer what is required in a path. 

Please test using the current master branch of the repository and see if this has resolved your issue.

**Comment by MeloJR** [comment] 2020-03-03 10:46
Yes, the current master branch does not enter into an infinite loop. That's great!

**Comment by theophilusx** [comment] 2020-03-03 22:03
New version v5.1.0 published with this fix.

**Closed by theophilusx** 2020-03-03 22:03 UTC
Labels: bug, documentation, more info, test
