### ISSUE TITLE
Recursive mkdir not working correctly

### ISSUE THREAD

**Issue by martinglover** [theophilusx/ssh2-sftp-client#88] opened 2018-09-05 18:04 UTC
When trying to do a recursive mkdir the path does not seem to be maintaining the root path

Example
`client.mkdir('./folder/sub-folder/sub-sub-folder', true)`

The first 2 folders are attempted correctly but when attempting to create `sub-sub-folder` it's attempting to create `./folder/sub-folder/folder/sub-folder/sub-sub-folder`
The path being passed to stfp.mkdir(p, ()) is correct it's beyond this point it goes wrong

**Comment by joelharkes** [comment] 2018-10-05 20:14
You could create a PR if you want but i think it might be done on purpose: It thinks the stuff after last slash iss your file name and shouldn't be created.

see code here: https://github.com/jyu213/ssh2-sftp-client/blob/edfac498c662e608008d8157262612d3d851d013/src/index.js#L258-L262

it on purposely? ignores last segment (token length is 0 so it returns.

try: `./folder/sub-folder/sub-sub-folder/` that should work

**Comment by orblazer** [comment] 2019-05-28 22:09
Hello,
I up this issue because this problem still present with last version.
In my case i use absolute path like `/public_html/assets/css`

The line cause problem : https://github.com/jyu213/ssh2-sftp-client/blob/9c33e604d89c91fb378eec80eeadde1952794521/src/index.js#L382
I have debug that method and the problem is because when check if path `/` is present that is return false.

Thanks.

**Comment by theophilusx** [comment] 2019-08-26 08:17
Testing with current development version and I cannot reproduce this issue. The code has changed to use cleaner async/await and I think this issue is now resolved. Fix is in release-4.0.0 branch.

**Closed by theophilusx** 2019-08-26 08:17 UTC
Labels: bug
