### ISSUE TITLE
get data with empty

### ISSUE THREAD

**Issue by j1151300783** [theophilusx/ssh2-sftp-client#106] opened 2018-11-26 11:28 UTC
I try to download file from remote server.
i can download by use "fastGet".
but when i use "get", the local file is empty.

Success：
```
sftpSource.connect({
    host: host,
    port: port,
    username: username,
    password: password
}).then(() => {
    return sftpSource.fastGet('/path/to/test.txt','123.txt');
}).then(()=>{
    sftpSource.end();
}).catch((err) => {
    console.log(err, 'catch error');
});
```

Fail(only download the file with no content)
```
sftpSource.connect({
    host: host,
    port: port,
    username: username,
    password: password
}).then(() => {
    return sftpSource.get('/path/to/test.txt');
}).then((stream)=>{
    stream.on('close', function() {sftpSource.end(); });
    stream.pipe(fs.createWriteStream('test123.txt'));
}).catch((err) => {
    console.log(err, 'catch error');
});
```

Shouldn't them generate the same result??
Sorry for my poor English...

**Comment by Patricknew** [comment] 2018-12-10 21:04
I have encountered the same issue. When using `get`, the stream it returns is empty and just hangs there without closing or throwing an error. @j1151300783 's workaround works for me as well.

Any idea why this is happening?

**Comment by theophilusx** [comment] 2018-12-20 21:42
What version of node are you using? I seem to see this problem with node 10.x, but not with node 8.x. I am suspicious the issue is related to the underlying ssh2 library.

**Comment by j1151300783** [comment] 2019-01-08 08:42
you're right, my version is v10.x

**Comment by theophilusx** [comment] 2019-02-28 06:00
I think I may have worked out what the problem is here and why the workaround posted by @j1151300783  works. The issue seems to be that the stream returned by ssh2 is paused. If you put a stream.resume() call before trying to use the stream it seems to work. What I don't understand is why it is paused. Here is the test I've been using to, which seems to work

````
  it('get large file using stream', function() {
    let localFile = path.join(LOCAL_URL, 'local-large-file.txt');
    let wtr = fs.createWriteStream(localFile, {encoding: 'utf8'});
    return sftp
      .get(path.join(SFTP_URL, 'large-file1.txt'))
      .then(rdr => {
        rdr.resume();
        return rdr.pipe(wtr);
      })
      .then(() => {
        return fs.statSync(localFile);
      })
      .then(stats => {
        return expect(stats.size).to.equal(6973257);
      });
  });
````

**Comment by theophilusx** [comment] 2019-02-28 06:56
To Fast he yells! OK, not solved, but getting closer to working out why this isn't working. The problem is with the resolving of the promise inside the on('readable', ....) event.  If I just return the read stream, it works fine. Need to dig deeper.

**Comment by theophilusx** [comment] 2019-02-28 23:43
OK, so think I've sorted the issue now. The problem is that adding a 'readable' event handler causes a stream to switch into paused mode. You then have to add a data handler (or pipe) etc to switch it back into flow mode or use read() to access the data. The function was doing 

````
stream.on('readable', () => {
  return resolve(stream);
});
````

to resolve the promise, which effectively returned a stream in paused mode, which probably isn't what most users expected..  

I've also found some inconsistencies with how the module is handling options (not consistent with underlying ssh2-streams module), so am going to try and re-work the method to make it work a bit better in a 'promise' style API. Thinking it wold be better to allow the get method to accept a destination argument, which is either a filename, a buffer or a stream and handle everything inside the promise, returning the thing passed in as the return value from the resolve() call on success and an error otherwise. To me, this seems a little cleaner than having a promise which returns a stream and leaves you with the situation where you then need to decide what to do with the stream and clean it up (possibly having to wrap it in another promise).  This would be a breaking change, so if others have better ideas, please chime in!

**Comment by theophilusx** [comment] 2019-03-01 05:22
I've made some changes in my fork of the module which I think fix this issue and make the get() method a little more usable. Note that these are breaking changes as the method's arguments have changed. Also, I have cleaned up option handling a bit and made it default to the same defaults as the underlying ssh2 and ssh2-streams modules. In particular, encoding now defaults to null rather than utf8 and I removed the separate option arguments (you now pass an object with all options you want to set as properties). 

Anyway, still needs more testing and I've not yet addressed some of the issues with the put() method. However, if anyone wants to try it out you can find it at https://github.co/theophilusx/ssh2-sftp-client

**Comment by theophilusx** [comment] 2019-03-11 04:34
This issue has been resolved in the most recent version, therefore this issue could be closed.

**Closed** 2019-08-22 07:19 UTC
