### ISSUE TITLE
How to validate/check the connection that is already created.

### ISSUE THREAD

**Issue by akdixit1** [theophilusx/ssh2-sftp-client#54] opened 2018-03-14 11:12 UTC
In my use-case, I create a connection instance and use the same for performing multiple operations.
I have observed that if you are performing these operations (like list, get, etc) and the sftp server goes down, the methods (eg. .list) does not return anything, in fact it seems to hang or wait indefinitely.
Is there a way to check the connection instance before perform the operations??

**Comment by jyu213** [comment] 2018-04-02 18:04
I can provide Client Event like `end` and `error` to handle it.

**Comment by rkaw92** [comment] 2018-07-30 12:13
Hi. Just tested the connection going down and indeed, the callbacks do hang. The way we solve it is to wrap the promises in timeouts (using `when.js` and its timeout feature), but it's important for user (actually, developer) experience in the long term that all Promises eventually fulfill or reject, not exist in an unresolved state forever. This library should be tracking and rejecting all outstanding promises when the connection fails.

**Comment by theophilusx** [comment] 2019-09-03 23:21
The problem with a timeout approach is deciding what is a reasonable timeout. I think a better approach is to add a listener for the 'close' event. This event is fired when the connection is closed and passes a Boolean to the listener which is true if the connection was closed due to errors, false if the connection was closed due to a client request (i.e. end()). The module does have an on() method to add lisnters - the events of interest would be 'end', 'error' and 'close'.

The module has also been updated in version 4.x to set the sftp stream to undefined if the connection ends. This should result in methods returning an error if there is no active connection. This prevents methods from hanging because there is no active connection and having a listener allows the client to take appropriate action if the connection is lost during processing of a request.

My tests seem to indicate this works, but it is difficult to ensure all cases have been tested adequately. However, the hanging behaviour I was able to reproduce previously does not seem to occur now. 

Closing this issue as I can no longer reproduce it with the current version. If problems with hanging continue, please open another issue and if possible, provide example code I can use to help in reproduction of the issue for testing.

**Closed by theophilusx** 2019-09-03 23:21 UTC
Labels: feature
