### ISSUE TITLE
SSH_FXP_FSETSTAT not permitted. Can it be avoided?

### ISSUE THREAD

**Issue by ianbale** [theophilusx/ssh2-sftp-client#330] opened 2021-07-07 16:57 UTC
I have been using v 3.1.0 for some time (old system left untouched)...

Recently I brought all libraries up to date and have used v6.0.1

Since doing that our SFTP puts have failed.

I have tracked that down to the clients sending an **SSH_FXP_FSETSTAT** after connection.

The SFTP server in question does not support this and returns an error. 

It then tries **SSH_FXP_SETSTAT** which is similarly unsupported.

At this point the client terminates the connection (I can see this from the SFTP server logs), but reports that the file was successfully sent, even though it has not been.

So I see two issues here:

1. Is there an option to not send these commands before sending the file?
2. Why does the client cut the connection
3. Why does it report that the file has been sent rather than reporting an error?

I have looked, but cannot find any config options to prevent the newer versions from sending **SSH_FXP_FSETSTAT / SSH_FXP_SETSTAT** after connection. Is there something I have missed? 

It would be good to stay up to date with the latest versions rather than be stuck on such an old version.

```
      let sftp = new SftpClient()

      sftp.connect(connectionConfig)
      .then(() => {
        console.log("SFTP connected. Sending file",filename,data)
        return sftp.put(Buffer.from(data),filename) // return send the result to .then ...
      })
      .then((x) => {
        console.log("File sent",x)
        sftp.end()
        resolve()
      })
      .catch((err) => {
        Utils.logToConsole(err)
        sftp.end()
        reject(err)
      })
```

**Comment by theophilusx** [comment] 2021-07-07 23:09
I don't believe this is caused by ssh2-sftp-client. There is no code in
the ssh2-sftp-client module which requests any state update of remote
file attributes unless the client calls one of the attribute changing
commands, like chmod. The ssh2-sftp-client is really just a wrapper
around the ssh2 module which provides a higher level Promise
based API. Any commands sent to the remote server are either triggered
by client code requests or are part of the operation of the underlying
ssh2 module. It does seem unusual for ssh2 to be sending remote file
attribute set commands which are not requested by client code. 


The first thing you should do is upgrade to ssh2-sftp-client version
7.0.0. This version is based on a new ssh2 version which is a complete
re-write of the original ssh2 code base. The re-write was done to
address some underlying design limitations and changes in the node
networking stack in node v14 which were not compatible with ssh2.

If the problem exists in the new version, it will be necessary to verify
it is not due to something in ssh2-sftp-client in order to log an issue
with the ssh2 maintainer and ensure it is not dismissed as a problem
with ssh2-sftp-client. In the validations directory of the
ssh2-sftp-client repository, there are some scripts which perform basic
sftp operations but which only use the ssh2 module. Use one of these
scripts (or adapt one for your own specific environment) and test to see
if you see the same issue. If you do, then it will be necessary to log
the issue with the ssh2 project.

Note that you can add a debug function by passing in a function
associated with the 'debug' property in the connection options object.
This will create lots of debugging data which might help and will
provide some useful data when you log the issue.

Make sure you also include details regarding node version, client
platform and any information you have about the remote sftp server.

If you are unable to reproduce the issue using just ssh2, please come
back and let me know. This would indicate I need to look more closely at
why the issue only exists with the ssh2-sftp-client code. A small sample
script which reproduces the problem would be really helpful as I cannot
debug an issue I cannot reproduce.

**Comment by ianbale** [comment] 2021-07-08 13:33
Thanks for the quick response and suggestions.

I've had a go with v7.0.0 and got some odd results.

I'm using Node v14 on AWS Lambda. I cannot run this locally since the server I am sending to is secured by IP. I'm on a dynamic one, so even if I ask them to whitelist mine it'll only work temporarily.

The send works sporadically with v7.0.0, but mostly fails to send the file despite the debug logs showing that it has sent it.
With v3.1.0 it works every time without fail.

I've asked for copies of the server logs for the test Is ran today. I'm waiting for those to come back before doing anything else.

**Comment by ianbale** [comment] 2021-07-08 14:55
I've just received the server logs.

Very frustratingly they show the exact same entires whether the upload was successful or not.

The same is true of the client logs my end.

I can also see that other clients sending data do not send the FSETSTAT / SETSTAT commands when they connect.
They may be a red herring as the client logs shows that v3.1.0 is also sending them, but they are the only difference in the logs between my clients connections and other users clients.

I'll have a go with the ssh2 scripts you suggested and get back to you.

**Comment by ianbale** [comment] 2021-07-08 16:57
I had to change const Client = require('ssh2') to const { Client } = require('ssh2')

The original worked fine running locally, but gave me a "Client is not a constructor" error when run on AWS Lambda. I am unsure why there should be a difference.

The results are the same though. It still sends the FSETSTAT and SETSTAT for some reason.
AWS Cloudwatch logs below.

Also, whilst it always says the file has been uploaded, it is only received sporadically. Most times the server never receives the file I am sending.

I have rolled back to 3.1.0 and everything is working fine again.

                                                                                                                                                                                             |
| 1625760949440 | 2021-07-08T16:15:49.439Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO connectionConfig {   "host": "sftplivetest.atocrsp.org",   "port": 22,   "readyTimeout": 15000,   "username": "snipped",   "password": "snipped" }                                                                                                                                                                            |
| 1625760949459 | 2021-07-08T16:15:49.458Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Custom crypto binding not available                                                                                                                                                                                                                                                                                                |
| 1625760949459 | 2021-07-08T16:15:49.459Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Client: Trying sftplivetest.atocrsp.org on port 22 ...                                                                                                                                                                                                                                                                             |
| 1625760949477 | 2021-07-08T16:15:49.477Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Local ident: 'SSH-2.0-ssh2js1.1.0'                                                                                                                                                                                                                                                                                                 |
| 1625760949487 | 2021-07-08T16:15:49.486Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Socket connected                                                                                                                                                                                                                                                                                                                   |
| 1625760949488 | 2021-07-08T16:15:49.488Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Remote ident: 'SSH-2.0-SSHD-CORE-1.6.0'                                                                                                                                                                                                                                                                                            |
| 1625760949489 | 2021-07-08T16:15:49.489Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending KEXINIT                                                                                                                                                                                                                                                                                                          |
| 1625760949500 | 2021-07-08T16:15:49.498Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: Handshake in progress                                                                                                                                                                                                                                                                                                     |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512  |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1                                                                                                                                                                                                |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256                                                                                                                                                                                                                                                                     |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa                                                                                                                                                                                      |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (remote) Host key format: ssh-rsa                                                                                                                                                                                                                                                                                       |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: Host key format: ssh-rsa                                                                                                                                                                                                                                                                                                |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (local) C->S cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com                                                                                                                                                                 |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (remote) C->S cipher: aes256-ctr                                                                                                                                                                                                                                                                                        |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: C->S Cipher: aes256-ctr                                                                                                                                                                                                                                                                                                 |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (local) S->C cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com                                                                                                                                                                 |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (remote) S->C cipher: aes256-ctr                                                                                                                                                                                                                                                                                        |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: S->C cipher: aes256-ctr                                                                                                                                                                                                                                                                                                 |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1                                                                                                                                                                           |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (remote) C->S MAC: hmac-sha2-256,hmac-sha1,hmac-sha1-96                                                                                                                                                                                                                                                                 |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: C->S MAC: hmac-sha2-256                                                                                                                                                                                                                                                                                                 |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1                                                                                                                                                                           |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (remote) S->C MAC: hmac-sha2-256,hmac-sha1,hmac-sha1-96                                                                                                                                                                                                                                                                 |
| 1625760949500 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: S->C MAC: hmac-sha2-256                                                                                                                                                                                                                                                                                                 |
| 1625760949516 | 2021-07-08T16:15:49.500Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (local) C->S compression: none,zlib@openssh.com,zlib                                                                                                                                                                                                                                                                    |
| 1625760949517 | 2021-07-08T16:15:49.516Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (remote) C->S compression: none,zlib,zlib@openssh.com                                                                                                                                                                                                                                                                   |
| 1625760949517 | 2021-07-08T16:15:49.517Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: C->S compression: none                                                                                                                                                                                                                                                                                                  |
| 1625760949517 | 2021-07-08T16:15:49.517Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (local) S->C compression: none,zlib@openssh.com,zlib                                                                                                                                                                                                                                                                    |
| 1625760949517 | 2021-07-08T16:15:49.517Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: (remote) S->C compression: none,zlib,zlib@openssh.com                                                                                                                                                                                                                                                                   |
| 1625760949517 | 2021-07-08T16:15:49.517Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake: S->C compression: none                                                                                                                                                                                                                                                                                                  |
| 1625760949517 | 2021-07-08T16:15:49.517Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending KEXDH_GEX_REQUEST                                                                                                                                                                                                                                                                                                |
| 1625760949573 | 2021-07-08T16:15:49.573Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Received DH GEX Group                                                                                                                                                                                                                                                                                                              |
| 1625760952517 | 2021-07-08T16:15:52.517Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending KEXDH_GEX_INIT                                                                                                                                                                                                                                                                                                   |
| 1625760952550 | 2021-07-08T16:15:52.550Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Received DH GEX Reply                                                                                                                                                                                                                                                                                                              |
| 1625760952551 | 2021-07-08T16:15:52.551Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Received DH Reply                                                                                                                                                                                                                                                                                                                  |
| 1625760952551 | 2021-07-08T16:15:52.551Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Host accepted by default (no verification)                                                                                                                                                                                                                                                                                         |
| 1625760952551 | 2021-07-08T16:15:52.551Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Host accepted (verified)                                                                                                                                                                                                                                                                                                           |
| 1625760952559 | 2021-07-08T16:15:52.559Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: NEWKEYS                                                                                                                                                                                                                                                                                                                   |
| 1625760952577 | 2021-07-08T16:15:52.577Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Verifying signature ...                                                                                                                                                                                                                                                                                                            |
| 1625760952578 | 2021-07-08T16:15:52.577Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Verified signature                                                                                                                                                                                                                                                                                                                 |
| 1625760952578 | 2021-07-08T16:15:52.578Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending NEWKEYS                                                                                                                                                                                                                                                                                                          |
| 1625760952579 | 2021-07-08T16:15:52.579Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Handshake completed                                                                                                                                                                                                                                                                                                                |
| 1625760952579 | 2021-07-08T16:15:52.579Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending SERVICE_REQUEST (ssh-userauth)                                                                                                                                                                                                                                                                                   |
| 1625760952617 | 2021-07-08T16:15:52.617Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: Received SERVICE_ACCEPT (ssh-userauth)                                                                                                                                                                                                                                                                                    |
| 1625760952618 | 2021-07-08T16:15:52.618Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending USERAUTH_REQUEST (none)                                                                                                                                                                                                                                                                                          |
| 1625760952620 | 2021-07-08T16:15:52.619Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: Received USERAUTH_FAILURE (password,keyboard-interactive,publickey)                                                                                                                                                                                                                                                       |
| 1625760952620 | 2021-07-08T16:15:52.620Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Client: none auth failed                                                                                                                                                                                                                                                                                                           |
| 1625760952620 | 2021-07-08T16:15:52.620Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending USERAUTH_REQUEST (password)                                                                                                                                                                                                                                                                                      |
| 1625760953431 | 2021-07-08T16:15:53.430Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: Received USERAUTH_SUCCESS                                                                                                                                                                                                                                                                                                 |
| 1625760953431 | 2021-07-08T16:15:53.431Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending CHANNEL_OPEN (r:0, session)                                                                                                                                                                                                                                                                                      |
| 1625760953433 | 2021-07-08T16:15:53.433Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)                                                                                                                                                                                                                                                                                      |
| 1625760953433 | 2021-07-08T16:15:53.433Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)                                                                                                                                                                                                                                                                           |
| 1625760953435 | 2021-07-08T16:15:53.435Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: CHANNEL_SUCCESS (r:0)                                                                                                                                                                                                                                                                                                     |
| 1625760953435 | 2021-07-08T16:15:53.435Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending CHANNEL_DATA (r:0, 9)                                                                                                                                                                                                                                                                                            |
| 1625760953437 | 2021-07-08T16:15:53.437Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: CHANNEL_DATA (r:0, 549)                                                                                                                                                                                                                                                                                                   |
| 1625760953437 | 2021-07-08T16:15:53.437Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO SFTP: Inbound: Received VERSION (v3, exts:versions,newline,vendor-id,fsync@openssh.com,hardlink@openssh.com,acl-supported,supported,supported2)                                                                                                                                                                                    |
| 1625760953438 | 2021-07-08T16:15:53.438Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Sending Buffer Data to LNHF010010NNNN_20151537_895801.SDCIPLUS.TEST                                                                                                                                                                                                                                                        |
| 1625760953438 | 2021-07-08T16:15:53.438Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending CHANNEL_DATA (r:0, 69)                                                                                                                                                                                                                                                                                           |
| 1625760953439 | 2021-07-08T16:15:53.438Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO SFTP: Outbound: Buffered OPEN                                                                                                                                                                                                                                                                                                      |
| 1625760953509 | 2021-07-08T16:15:53.509Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: CHANNEL_DATA (r:0, 45)                                                                                                                                                                                                                                                                                                    |
| 1625760953509 | 2021-07-08T16:15:53.509Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO SFTP: Inbound: Received HANDLE (id:0)                                                                                                                                                                                                                                                                                              |
| 1625760953510 | 2021-07-08T16:15:53.510Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending CHANNEL_DATA (r:0, 53)                                                                                                                                                                                                                                                                                           |
| 1625760953510 | 2021-07-08T16:15:53.510Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO SFTP: Outbound: Buffered FSETSTAT                                                                                                                                                                                                                                                                                                  |
| 1625760953512 | 2021-07-08T16:15:53.511Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: CHANNEL_DATA (r:0, 60)                                                                                                                                                                                                                                                                                                    |
| 1625760953512 | 2021-07-08T16:15:53.512Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO SFTP: Inbound: Received STATUS (id:1, 8, "Command SSH_FXP_FSETSTAT is unsupported")                                                                                                                                                                                                                                                |
| 1625760953512 | 2021-07-08T16:15:53.512Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending CHANNEL_DATA (r:0, 65)                                                                                                                                                                                                                                                                                           |
| 1625760953512 | 2021-07-08T16:15:53.512Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO SFTP: Outbound: Buffered SETSTAT                                                                                                                                                                                                                                                                                                   |
| 1625760953514 | 2021-07-08T16:15:53.514Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: CHANNEL_DATA (r:0, 59)                                                                                                                                                                                                                                                                                                    |
| 1625760953516 | 2021-07-08T16:15:53.514Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO SFTP: Inbound: Received STATUS (id:2, 8, "Command SSH_FXP_SETSTAT is unsupported")                                                                                                                                                                                                                                                 |
| 1625760953517 | 2021-07-08T16:15:53.517Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending CHANNEL_DATA (r:0, 399)                                                                                                                                                                                                                                                                                          |
| 1625760953517 | 2021-07-08T16:15:53.517Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO SFTP: Outbound: Sent WRITE (id:3)                                                                                                                                                                                                                                                                                                  |
| 1625760953518 | 2021-07-08T16:15:53.518Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Inbound: CHANNEL_DATA (r:0, 21)                                                                                                                                                                                                                                                                                                    |
| 1625760953518 | 2021-07-08T16:15:53.518Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO SFTP: Inbound: Received STATUS (id:3, 0, "")                                                                                                                                                                                                                                                                                       |
| 1625760953520 | 2021-07-08T16:15:53.520Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending CHANNEL_DATA (r:0, 45)                                                                                                                                                                                                                                                                                           |
| 1625760953520 | 2021-07-08T16:15:53.520Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO SFTP: Outbound: Buffered CLOSE                                                                                                                                                                                                                                                                                                     |
| 1625760953520 | 2021-07-08T16:15:53.520Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO File successfully uploaded to LNHF010010NNNN_20151537_895801.SDCIPLUS.TEST                                                                                                                                                                                                                                                         |
| 1625760953537 | 2021-07-08T16:15:53.537Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Outbound: Sending DISCONNECT (11)                                                                                                                                                                                                                                                                                                  |
| 1625760953539 | 2021-07-08T16:15:53.539Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Socket ended                                                                                                                                                                                                                                                                                                                       |
| 1625760953539 | 2021-07-08T16:15:53.539Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Socket closed                                                                                                                                                                                                                                                                                                                      |
| 1625760953557 | 2021-07-08T16:15:53.557Z 941a59ce-d7ce-48e5-b98e-422cf78a09c9 INFO Stream Error: No response from server                                                                                                                                                                                                                                                                                              |

**Comment by theophilusx** [comment] 2021-07-08 19:23
The fact you observe the exact same issue with just ssh2 pretty much
confirms the problem is with ssh2. You will need to log an issue with
that project as there is nothing I can do from the ssh2-sftp-client
level.

It is interesting that it works with version 3.1.0 as I think that
version is based on ssh2 0.8.x, which has known problems with node v14.
The new ssh2 1.1.0, which is a complete re-write of ssh2 (and what
ssh2-sftp-client 7.0.0 is based on) was done partly because of problems
ssh2 had with node v14 due to changes in node's networking stack. These
changes were rolled back in node 15.3, but as they did result in
significant network performance improvements, I think there is a good
chance they will be re-introduced at some future date. 

At this stage, I guess all you can do is log an issue with the ssh2
maintainers and wait to see what response you get.

**Comment by ianbale** [comment] 2021-07-09 08:19
Will do that. Thanks for your help.

**Comment by theophilusx** [comment] 2021-08-04 10:41
A new version of ssh2 was recently released and I've pushed a new version of ssh2-sftp-client (v7.0.1). It would be wroth checking to see if the issue you had has been resolved in the new ssh2 version.

**Closed** 2021-08-18 01:32 UTC
Labels: external-dependency-bug
