### ISSUE TITLE
Upload files on parallel in uploadDir method

### ISSUE THREAD

**Issue by hsh2001** [theophilusx/ssh2-sftp-client#233] opened 2020-05-19 06:40 UTC
The upload speed is SO slow for now. We need parallel upload.

e.g.:
```js
const fileList = await fs.readDir(targetDir);
const promises = fileList.map(async (filePath) => {
  await client.upload(filePath);
});
await Promise.all(promises);
```
It's just a code for example, not good for performance. If you are adding `parallel` option, you will have to split the promises. Because if there are too many files in the folder, client make that many requests at once.

**Comment by hsh2001** [comment] 2020-05-19 06:43
`downloadDir` method would be the same.

**Comment by theophilusx** [comment] 2020-05-19 07:26
The problem is it isn't that straight-forward. The underlying ssh2 and
ssh2-stream libraries don't handle multiplexing of the ssh/sftp
connection. This means you would have to create multiple
ssh2-sftp-client objects, each with their own connection to the remote
server. Then you would also need some decision point to decide when to
use multiple connections and when to just use one because if you make
multiple connections, but the number or size of the underlying files are
small, the overhead of establishing each connection will likely exceed
the speedup provided by doing downloads in parallel. There are also a
number of race conditions we would need to deal with if we have multiple
connections.

The upload/download directory functions use fastGet/fastPut to transfer
the files. These functions actually do the download/upload in parallel
by breaking the file up into separate chunks. So there is already some
parallelism being applied. How effective this is really depends on the
size of the files your uploading/downloading. Smaller files are
unlikely to benefit (in fact, if there are lots of small files, it may
be slower due to the overhead associated with breaking into chunks and
re-assembling). Some sftp servers don't support this chunking and
parallel upload/download, so the fastGet/fastPut benefits are not always
available, depending on the remote server. 

To make matters worse, there appears to be an issue with ssh-streams
module and node v14.2.0 (I have logged an issue with the upstream
maintainer of that module). There is an intermittent failure with that
version of node where downloads/uploads just hang with no errors
generated.

There are some things I can probably do to improve speed. For example,
there are a number of path verification checks the mmodule performs
which can impact performance, especially if there are lots of small
files. These checks were added to provide better error messages (source
of many issues). Might be able to provide a switch to disable that level
of checking. This would provide some speed improvement, but at the cost
of less informative errors when errors occur.

Simply adding a set number of promises and doing something like
Promise.all() to run them in parallel is not going to work. A lot more
work would be required to deal with the limitations of the underlying
ssh-streams module, so I cannot see this feature being added for a while
(possibly not at all) as I just don't have the time right now. 

What platform are you running on?
What version of node are you using?
What is the number and average size of the files being transferred?
What sort of times are you seeing? How do those times compare with just
transferring the files using CLI sftp i.e. scp?

I'm using this module to download quite a lot of files each day. They
are large files (multiple Gb) and while it is slower than using
something like lftp, it isn't that much slower. It could be that your
experiencing slow speeds because you are dealing with lots of small
files or that the bottleneck is in another part of the lib other than
the actual transfer stage. Knowing a bit more about your environment
would allow me to try and test with something similar.

Note that when doing any comparisons, be careful about what other tool
you use. Some of the 'smart' sftp clients do things a bit like rsync and
will only actually copy files up/down if they are different and may
report much faster speeds if not all the data changes as it is only
transferring files that are different rather than just transferring all
files requested regardless. 

As a work-around, you can also consider using something like one of the
wrappers for programs like lftp. At one point, I had a wrapper around
the lftp module, which is a wrapper around the lftp CLI program. The
wrapper I used just provided an API the same as ssh2-sftp-client, so it
could be a drop-in replacement. The downside is that because it isn't a
'real' node program, you have additional dependencies and don't have the
same level of control/integration. However, if your requirements are
simple, it might be a viable alternative if ssh2-sftp-client is simply
too slow.

-- 
Tim Cross

**Comment by hsh2001** [comment] 2020-05-19 07:51
Thank you for reply and advice. I don't know about `ssh2`. I just need `sftp` while I don't know what is `ssh2` and I saw the files uploaded in order. So I thought it would be better to upload files in parallel and I mistaken this feature would be added simply. I don't know what `ssh2` is, so I don't expect this feature to be added for now.

Thank you for good package to let me use `sftp` while I don't know about `ssh2`!

**Closed** 2020-05-19 07:51 UTC

**Comment by theophilusx** [comment] 2020-05-19 08:16
All OK.

FYI ssh2 is just version 2 of ssh which is the underlying
protocol sftp uses. When you use ssh to connect to a remote server, you
would be using ssh v2 a.k.a ssh2. So ssh2-sftp-client is based on two
key packages ssh2 and ssh2-streams, two pure javascript modules which
implement the ssh v2 protocol. The ssh2 module handles the initial
connection handshake, key exchange and negotiation of encryption
protocols. The ssh2-streams library handles the basic commands to do
things like transfer data, execute commands on remote system and the
basic 'ftp' operations. 

-- 
Tim Cross

**Comment by hsh2001** [comment] 2020-05-19 08:19
Thank you for the good explanation. Have a nice day 👍
