### ISSUE TITLE
downloadDir not creating required files locally

### ISSUE THREAD

**Issue by BCurrell** [theophilusx/ssh2-sftp-client#207] opened 2020-01-21 10:25 UTC
Node Version: v12.14.1 (installed with NVM-Windows)
NPM Version: 6.13.4
ssh2-sftp-client Version: 5.0.1

Stacktrace:
```
PS X:\evolving-networks\nexus-network-management> node .\testing.js
connected
{ path: 'storage\\configs\\download\\', valid: true }
{
  valid: false,
  msg: 'No such file: storage\\configs\\download\\.gitkeep',
  code: 'ENOENT',
  parentMsg: 'No such file: ',
}
[Error: ENOENT: no such file or directory, stat ''] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: ''
}
X:\evolving-networks\nexus-network-management\node_modules\ssh2-sftp-client\src\utils.js:155
      if (stats.isDirectory()) {
                ^

TypeError: Cannot read property 'isDirectory' of undefined
    at X:\evolving-networks\nexus-network-management\node_modules\ssh2-sftp-client\src\utils.js:155:17
    at FSReqCallback.oncomplete (fs.js:158:21)
```

Description:

When uploading a directory to a remote endpoint, it works as expected, creates all subdirectories and files, fills the files with their contents, nice and easy to do. However when downloading a directory, it doesn't create anything that is missing. I'm not too sure what is going wrong. I added console.log to the checkLocalPath function to see where the check was failing, but I can't work it out. If I download a remote directory over an existing local copy of that directory, the download works as expected.

Anything you can do to help run this down?

**Comment by theophilusx** [comment] 2020-01-21 10:56
thanks for the report. As this is new functionality, it is quite likely
there is a bug there.

Could you provide a minimal script which reproduces/demonstrates the
issue? I can then use this on my windows test system to try and
reproduce the problem locally, which will allow me to fix the issue. It
will likely be something trivial. 

I suspect your on the right path and it will be an issue with
checkLocalPath. This is new functionality and this level of checking is
difficult to get right because of the possible platform combinations and
different ways they handle paths and file permissions etc. Once I can
reproduce it, fixing it will likely be easy.

**Comment by BCurrell** [comment] 2020-01-21 11:08
No problem, thanks for the quick response.

Below is the script I was using with my variables stripped out:

```
const SFTP = require("ssh2-sftp-client");

const USERNAME = "";
const PASSWORD = "";

const HOST = "";

const LOCAL = "";
const REMOTE = "";

const connection = new SFTP();

connection
  .connect({
    host: HOST,
    username: USERNAME,
    password: PASSWORD
  })
  .then(() => {
    console.log("connected");

    return connection.downloadDir(REMOTE, LOCAL);
  })
  .then(result => {
    console.log(result);

    return connection.end();
  })
  .then(console.log)
  .catch(err => {
    console.error(err);

    connection.end();
  });
```

**Comment by theophilusx** [comment] 2020-01-21 11:33
OK, thanks. It is late here, so I'll look at this tomorrow.

**Comment by theophilusx** [comment] 2020-01-22 00:04
There is definitely an issue here, but looks like it only impacts the Windows platform. Working on diagnosing the issue now.

**Comment by theophilusx** [comment] 2020-01-22 10:42
OK, I think I found the issue. It was related tot he path.posix.parse() method, which behaves differently under windows compared to *nix. If you would like to try out the code in the check-path-fix branch of the repository and see if it fixes your issue that would be great.

**Comment by BCurrell** [comment] 2020-01-22 13:15
If the local directory exists, it fails with an undefined error, but if I remove it it downloads fine. Not yet tested other features but no reason to believe they won't work.

```
PS X:\evolving-networks\nexus-network-management> node .\testing.js
connected
Error: downloadDir: Undefined error - probably a bug!
    at Object.formatError (X:\evolving-networks\nexus-network-management\node_modules\ssh2-sftp-client\src\utils.js:62:18)
    at SftpClient.downloadDir (X:\evolving-networks\nexus-network-management\node_modules\ssh2-sftp-client\src\index.js:1126:23) {
  code: 'ERR_GENERIC_CLIENT',
  custom: true
}
PS X:\evolving-networks\nexus-network-management> node .\testing.js
connected
/home/brandon/upload/ downloaded to storage\configs\download\
true
```

**Comment by BCurrell** [comment] 2020-01-22 13:17
uploadDir is working perfectly for my use case as well

**Comment by theophilusx** [comment] 2020-01-23 03:13
Sorry, my bad for the download - had a missing await. Fixed now. Should work correctly. Please try and let me know.

**Comment by BCurrell** [comment] 2020-01-23 09:03
Quick test this morning, looks like its working perfectly.

Thanks for getting this done so quick. I'll keep an eye on the npm page for the release rather than using the git branch.

**Comment by theophilusx** [comment] 2020-01-23 11:11
OK v5.0.2 published to npmjs.com just now. Closing this issue.

**Closed by theophilusx** 2020-01-23 11:11 UTC
Labels: bug, test
