### ISSUE TITLE
Cannot gracefully handle request to change password

### ISSUE THREAD

**Issue by mathiasm74** [theophilusx/ssh2-sftp-client#272] opened 2020-10-12 15:16 UTC
I'm connecting daily to a server that once monthly will require a new password be set. I.e. after successful login, the server will send another prompt to the client asking for a new password to be set (see screenshot of Filezilla dialog).

Unfortunately ssh2-sftp-client handles this as if the connection attempt just failed, and there seems to be no way to distinguish this case from other failure modes. What I want is to catch this case so I can send an SMS message to myself informing of the need to change password.

![image](https://user-images.githubusercontent.com/917776/95763149-f63d7e00-0cae-11eb-9b09-bb3d7666c574.png)

**Comment by mathiasm74** [comment] 2020-10-12 15:48
My best attempt so far is to enable 'keyboard-interactive' login (setting options.tryKeyboard: true, and implementing a client.on('keyboard-interactive', ...) where i call finish(the_password). My hope was to check the 'prompt' argument, but it's 'Password:' even after the initial attempt to log in (was hoping it would change to 'Enter new password [...]').

**Comment by theophilusx** [comment] 2020-10-12 21:45
This is a tricky one. The behaviour you are describing is not part of
the standard ftp protocol and there is nothing 'built-in' in the
ssh2/ssh2-streams modules that ssh2-sftp-client uses to support this.

Sadly, this is yet another example of poor security architecture. The
objective is to make things more secure, but will likely result in
reduced security. NIST and other bodies have already flagged that the
'old' idea of forcing a change in password on a regular basis was a bad
idea (along with forcing people to have specific characters in their
passwords). The smarter way to deal with security for ssh and sftp is to
use keys and prevent the use of passwords.

The first thing I would do is see if using a key is possible and if that
would bypass the monthly password change fiasco. Sometimes, the password
change routines are not triggered if you don't use password
authentication. Using an ssh key would be more secure and would avoid
the whole need for monthly manual intervention.

If this is not possible, all I can suggest is that you experiment just
using the ssh2 and ssh2-streams modules and see if you can come up with
a recipie which works. Once we have that, I can probably port it to
ssh2-sftp-client. Unfortunately, as I don't have access to a server with
this broken behaviour, there is not a lot I can do to assist. The fact
the prompt is the same for the initial password and for entering the new
password certainly does not help matters.

**Comment by mathiasm74** [comment] 2020-10-18 13:00
This server requires both a key and a password, and it belongs to a major insurance company so there's nothing I can do to change that.

Did you see my UPDATE 2 above?

**Comment by theophilusx** [comment] 2020-10-18 22:13
No, I hadn't seen your update. Seems github only sends a notification
for new comments, not for editing/updated ones on issues.

Password and key - belt and braces. Bureaucratic security policies will
be the death of us all! It is when I see nonsense like this I remember
why, after 10 years, I left the security sector!

Let me have a think and I'll see if we can add support for the
'USERAUTH_PASSWD_CHANGEREQ' signal. Adding it shouldn't be too hard, but
deciding on what is the best action may be a little harder - probably
just throw an error with a specific error message stating server is
requesting a password change as opposed to more sophisticated handling
of the error.

Will probably need your help to test the changes. Would that be possible?

**Comment by mathiasm74** [comment] 2020-10-19 20:57
> Will probably need your help to test the changes. Would that be possible?

Of course! This situation recurs every month afaik.

**Comment by theophilusx** [comment] 2020-10-24 23:48
The ssh2 module is currently being re-written and the ssh2-streams module it used is being deprecated due to problems the library has with v14+ of node. This means ssh2-sftp-client will need to be updated to use the new ssh2 module. As there are a number of changes planned for the new ssh2 module, it is also likely that some desing changes will be required for ssh2-sftp-client. Therefore, this feature request will be factored into this new version rather than trying to add it to the current version which is now end-of-life.

**Comment by yairzahavi** [comment] 2021-03-10 11:57
> My best attempt so far is to enable 'keyboard-interactive' login (setting options.tryKeyboard: true, and implementing a client.on('keyboard-interactive', ...) where i call finish(the_password). My hope was to check the 'prompt' argument, but it's 'Password:' even after the initial attempt to log in (was hoping it would change to 'Enter new password [...]').
> 
> UPDATE: Realising it's probably the 'instructions' argument I should check, not 'prompt', but it's 'Enter password for [name of my account]' every time. Starting to think the 'keyboard-interactive' login attempt is actually failing, perhaps because of the privateKey that the server is also requiring (this all works in my original setup, as long as the password doesn't need to be changed).on
> 
> UPDATE2: So, relying on 'keyboard-interactive' seems to have been a red herring. Ended up hooking into the ssh2 stream to detect USERAUTH_PASSWD_CHANGEREQ event. This is reaching into the private implementation so not the ideal solution, but good enough for my case.
> 
> ```
> // Hook into the data stream to detect when the SFTP server is asking to set a new password
> sftp.client._sshstream.on('USERAUTH_PASSWD_CHANGEREQ', () => {
>   console.log("USERAUTH_PASSWD_CHANGEREQ");
>   callback(  // Do nothing before noon
>     moment().hour() < 12 ? NoErr : "SFTP server is asking for new password"
>   );
> });
> ```

hi how did you use it in the end?
I need the same solution but i did not understand where the callback came from..

**Comment by theophilusx** [comment] 2021-03-10 19:26
I have not tried to use this functionality. The below is based on
information from the ssh2 docs. You may find more information looking at
those docs and the issues logged against the ssh2 module.

When you create a new sftpClient object, it creates an underlying
ssh2 client which is stored in the this.client property of the object.
When you call sftpClient.connect(), it first creates the ssh2 client and
asks for a connection. When the ssh2 client has established the
connection, it emits a 'ready' event. The sftpClient then asks for an
sftp connection and stores that in the this.sftp property of the
sftpClient object. This all occurs as part of the sftpClient.connect()
method call.

In the case where the remote server is asking for a password change, the
ssh2 client will emit a 'change password' event. To do something wiht
this event, you need to add a change password event handler. The handler
can do whatever you need to do to obtain a new password e.g. ask the
user, generate a password using some algorithm or lookup etc. Your
change password handler then needs to call the 'done' callback function
passed in as one of the arguments when your listener is called,

The "change password" event will call your listener with 3 arguments, a
message from the server, a language string and a 'done' callback
function.

The sftpClient object has an 'on()' method, which will add a listener to
the ssh2 client. So to attach your listener, you would do something like

const myClient = new SftpClient();

myClient.on("change password", (msg, lang, done) => {
  console.log(msg);
  let newPwd = getNewPassword() // whatever you need to do to get a new pwd
  done(newPwd);
);

**Comment by mathiasm74** [comment] 2021-03-11 01:47
You can ignore the callback call in my example. It’s defined outside the code snippet I shared and is only relevant for my implementation. Do whatever you want in the method called by the on() event function.

**Comment by yairzahavi** [comment] 2021-03-11 13:04
well this event didnt work for the latest version.

> myClient.on("change password", (msg, lang, done) => { console.log(msg); let newPwd = getNewPassword() // whatever you need to do to get a new pwd done(newPwd); );


what i did is as following.
i downgraded to version 5.3.2
and added the following code from newer versions of ssh2.


```
const SSH2Stream = require("ssh2-streams").SSH2Stream;
const send = SSH2Stream._send;

const MESSAGE = {
  // Transport layer protocol -- generic (1-19)
  DISCONNECT: 1,
  IGNORE: 2,
  UNIMPLEMENTED: 3,
  DEBUG: 4,
  SERVICE_REQUEST: 5,
  SERVICE_ACCEPT: 6,

  // Transport layer protocol -- algorithm negotiation (20-29)
  KEXINIT: 20,
  NEWKEYS: 21,

  // Transport layer protocol -- key exchange method-specific (30-49)
  KEXDH_INIT: 30,
  KEXDH_REPLY: 31,

  KEXDH_GEX_GROUP: 31,
  KEXDH_GEX_INIT: 32,
  KEXDH_GEX_REPLY: 33,
  KEXDH_GEX_REQUEST: 34,

  KEXECDH_INIT: 30,
  KEXECDH_REPLY: 31,

  // User auth protocol -- generic (50-59)
  USERAUTH_REQUEST: 50,
  USERAUTH_FAILURE: 51,
  USERAUTH_SUCCESS: 52,
  USERAUTH_BANNER: 53,

  // User auth protocol -- user auth method-specific (60-79)
  USERAUTH_PASSWD_CHANGEREQ: 60,

  USERAUTH_PK_OK: 60,

  USERAUTH_INFO_REQUEST: 60,
  USERAUTH_INFO_RESPONSE: 61,

  // Connection protocol -- generic (80-89)
  GLOBAL_REQUEST: 80,
  REQUEST_SUCCESS: 81,
  REQUEST_FAILURE: 82,

  // Connection protocol -- channel-related (90-127)
  CHANNEL_OPEN: 90,
  CHANNEL_OPEN_CONFIRMATION: 91,
  CHANNEL_OPEN_FAILURE: 92,
  CHANNEL_WINDOW_ADJUST: 93,
  CHANNEL_DATA: 94,
  CHANNEL_EXTENDED_DATA: 95,
  CHANNEL_EOF: 96,
  CHANNEL_CLOSE: 97,
  CHANNEL_REQUEST: 98,
  CHANNEL_SUCCESS: 99,
  CHANNEL_FAILURE: 100,

  // Reserved for client protocols (128-191)

  // Local extensions (192-155)
};

function writeUInt32BE(buf, value, offset) {
  buf[offset++] = value >>> 24;
  buf[offset++] = value >>> 16;
  buf[offset++] = value >>> 8;
  buf[offset++] = value;
  return offset;
}

SSH2Stream.prototype.authPassword = function (username, password, newPassword) {
  if (this._server) throw new Error("Client-only method called in server mode");

  const userLen = Buffer.byteLength(username);
  const passLen = Buffer.byteLength(password);
  const newPassLen = newPassword ? Buffer.byteLength(newPassword) : 0;
  let p = 0;
  const packet = Buffer.allocUnsafe(
    1 +
      4 +
      userLen +
      4 +
      14 +
      4 +
      8 +
      1 +
      4 +
      passLen +
      (newPassword ? 4 + newPassLen : 0)
  );

  packet[p] = MESSAGE.USERAUTH_REQUEST;

  writeUInt32BE(packet, userLen, ++p);
  packet.utf8Write(username, (p += 4), userLen);

  writeUInt32BE(packet, 14, (p += userLen));
  packet.utf8Write("ssh-connection", (p += 4), 14);

  writeUInt32BE(packet, 8, (p += 14));
  packet.utf8Write("password", (p += 4), 8);

  packet[(p += 8)] = newPassword ? 1 : 0;

  writeUInt32BE(packet, passLen, ++p);
  packet.utf8Write(password, (p += 4), passLen);

  if (newPassword) {
    writeUInt32BE(packet, newPassLen, (p += passLen));
    packet.utf8Write(newPassword, (p += 4), newPassLen);
    this._debug &&
      this._debug("Outbound: Sending USERAUTH_REQUEST (changed password)");
  } else {
    this._debug && this._debug("Outbound: Sending USERAUTH_REQUEST (password)");
  }

  this._state.authsQueue.push("password");
  this.debug("DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)");
  return send(this, packet);
};
```


then using the event as in @mathiasm74  example 

```
sftp.client._sshstream.on("USERAUTH_PASSWD_CHANGEREQ", async () => {
    const newPassword = await passwordManager.resetPassword();
    sftp.client._sshstream.authPassword(
      config.LAB_VAULT_USERNAME,
      oldPassword,
      newPassword
    );
  });
```

**Comment by theophilusx** [comment] 2021-03-11 16:05
Not sure why you downgraded to 5.3.2. That version has known issues.

When you say the latest ssh2 code, be aware that the latest ssh2 code is
a complete re-write. I have been testing against that code and it has
some major problems and is not ready for production use.

My recommendation would be to see if you can get the change password
functionality working using ONLY ssh2 v0.8.x. If you cannot get that to
work, then log an issue with the ssh2 maintainer. If you can get it to
work, then the issue is definitely with ssh2-sftp-client. If that is the
case, please let me know with a sample script which I can use to try and
reproduce the issue and from there debug it.

When you say the first attempt did not work, can you provide more
details. Did the event not fire or did the event fire, but the password
was not changed or did something else fail?

If you instead plan to just continue with the version you have modified,
my suggestion would be to make a fork and use it. I cannot help with
your modified version as the changes are too extensive.

**Comment by theophilusx** [comment] 2021-06-04 07:43
A new version of ssh2 has been relased and I have updated the ssh2-sftp-client code to use that version. I will release version 7.0.0 of ssh2-sftp-client in about a week or so. 

As the new version of ssh2 now supports the 'change password' event, it should now be possible to just add a listener for this event using the on() method to handle password changes. I will therefore close this issue for now.

If using the change password event does not work with verison 7.x of ssh2-sftp-cleint, let me know and I will re-open the issue (or open a new one).

**Closed by theophilusx** 2021-06-04 07:43 UTC
Labels: feature

**Comment by mathiasm74** [comment] 2021-06-04 14:22
Excellent! Thanks!

**Comment by yairzahavi** [comment] 2021-06-05 05:28
Thank you!
