### ISSUE TITLE
Received more data than requested

### ISSUE THREAD

**Issue by Zendor18** [theophilusx/ssh2-sftp-client#202] opened 2020-01-10 08:54 UTC
I have a problem when i'm trying to add multiple files (not at once, but quick) to the ftp server. I get the error:
```javascript
/usr/src/app/node_modules/ssh2-streams/lib/sftp.js:901
        return cb(new Error('Received more data than requested'));
                  ^
Error: Received more data than requested
    at cb (/usr/src/app/node_modules/ssh2-streams/lib/sftp.js:901:19)
    at SFTPStream._transform (/usr/src/app/node_modules/ssh2-streams/lib/sftp.js:444:17)
    at SFTPStream.Transform._read (_stream_transform.js:189:10)
    at SFTPStream._read (/usr/src/app/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at SFTPStream.Writable.write (_stream_writable.js:305:11)
    at Channel.ondata (_stream_readable.js:727:22)
    at Channel.emit (events.js:210:5)

```

I realize that it may be the problem with [csv-parse](https://www.npmjs.com/package/csv-parse), or in the way that i'm using it. My code:

```javascript
const remoteFileWatcher = new RemoteFileWatcher('/');

const output = [];

remoteFileWatcher.on('added', e => {
  const p = e.stream.pipe(
    csvParser({
      delimiter: ',',
      relax_column_count: true,
    }),
  );

  p.on('end', () => {
    app.log.debug(output.length);
  });

  p.on('readable', () => {
    let record;
    while ((record = p.read())) {
      output.push(record);
    }
  });

  p.on('error', err => {
    app.log.error(err);
  });
});
```

**remoteFileWatcher** is my custom class that emitting event's on changes in fs through sftp. In event object (e) im passing stream property with readable stream like this:
```javascript
this.ftpClient.connection.createReadStream(join(snapshotFile.path, name));
//this.ftpClient.connection === await sftp.connect(this.options);
```
 There is no problem with stream itself, promise resolves correctly every time, but i got this error. For example adding file around 4mbytes to the ftp, next second another file with the ~same size.

**Comment by theophilusx** [comment] 2020-01-10 09:33
It isn't clear to me how you are ensuring that the upload of the first
file has completed before you start the upload of the next file.

I don't think what you are attempting to do really fits with the promise
based API provided by ssh2-sftp-client. You would probably be far better
off just using SSH2 directly (you are already having to handle all the
events etc and it looks like your already using low level ssh2 functions
directly and mixing up the two is a recipe for problems).

You probably need at least 2 separate ssh2-sftp-client connections - one
which is used for the file watcher functionality and the other used for
downloading and processing the files. I would really need to see your
custom watcher code to understand how your using the module and
controlling the data so that things don't get mixed up.

**Comment by Zendor18** [comment] 2020-01-10 10:00
Sorry for the possible misleading, and my English. My remoteFileWatcher watches for changes, especially when new file was added to the ftp, then it's emit event 'added', and attach stream to event object directly (without promise, my mistake). So when i'm adding file to my ftp, manually by myself via ubuntu file interface, remoteFileWatcher takes snapshot and emits events if there was changes.
[repository](https://github.com/Zendor18/remoteFileWatcher/tree/master/RemoteFileWatcher).
And can you please explain why do i need multiple connections?

**Comment by theophilusx** [comment] 2020-01-10 11:06
I had a very quick look at your repository. I'm not very familiar with
Typscript, but from what I can see, I think you have both implementation
and design problems. I also think your approach is far more complicated
than it needs to be.

One thing I noticed is that you are using 'await' in lots of places
where it isn't necessary. You only need to use await if your calling a
function which returns a Promise i.e. something which either does return
new Promise() or calls a function defined with async. I also notice that
some of the Promises look like they are defined to return void. This is
a code smell - promises should always return something

the second problem I see is a design problem. The SSH2 library can only
deal with 1 thing at a time. If your code is reading data from the
stream returned by your watcher, you cannot perform any other
interaction over the ssh connection until that stream has been read and
closed. It looks to me that if your file watcher found (for example) to
modified files, it would trigger two modified events, returning two read
streams for the modified files. These could be open at the same time and
that is going to cause problems. I suspect the SSH2 mdule will not
handle multiple open streams at the same time. 

My suggestion regarding two connections was to have one connection which
just monitors for file changes and when it finds one, return the name of
the file which has been modified (no stream). Then in your local code,
collect these files via the event listener and push them onto some sort
of queue. Then have a second mdule which reads the file names out of
that queue and downloads them (or does whatever you need to do to
process them) using the second connection - ensure you finish each file
processing before starting the next one.

A lot depends on how responsive your system needs to be. It could be
easier to just have one connection and just do

- await sftp connect
- loop
  - current_list = await getFiles()
    - if last_list is empty
      - last_list = current_list
      - continue
    - if last_list not empty
      - diff_list = getDiff(last_list, current_list);
      - if diff_list is not empty
        - for each file in diff_list
          - await process file
        - last_list = current_list
        - continue
  - if end_flag is true
    - await end connection
    - exit
- end loop

You would probably need to put some additional logic into the loop to
stop it from looping too fast when there are no file changes. The main
point is that you can guarantee that only one 'task' is being dealt with
over the sftp connection at a time.

For the process file step, you can use client.get() with the second
argument being a writeable stream. This could be the CSV parsing stream
if, for example, you wanted to extract the data as records and do
something else with them.

**Comment by Zendor18** [comment] 2020-01-10 11:26
Promise<void> its return type of the async function that have no return value. I checked all the await statements they are all awaiting a promises. For example i have a start method which is async function.
I'm awaiting for ssh connection then start cron job, which is lists all directories and takes a snapshot.
So this function itself has no return value, that is why i'm using Promise<void>. Maybe there is a better approach. I really thankful for your detailed answer! I'm going to improve my implementation with all your advises. Thanks a lot!

**Comment by Zendor18** [comment] 2020-01-10 13:42
Seems it's not working for me. I'm tried upload multiple files with new instance of sftp each and also tried wait for end event of prev stream (file processing) before moving on next one, still same error.
So i tried like this:
```javascript
RemoteFileWatcher.on('add', async event => {
 const ftp = new SftpClient();
 await ftp.connect(options);

const {
        target: { name, path },
      } = event;
});

const p = csvParser({
        delimiter: ',',
        relax_column_count: true,
      });

      p.on('end', async () => {
        app.log.debug(output.length);
        await ftp.end();
      });

      p.on('readable', () => {
        let record;
        while ((record = p.read())) {
          output.push(record);
        }
      });

      p.on('error', err => {
        app.log.error(err);
      });

      ftp.get(join(path, name), p);
});
```

**Comment by theophilusx** [comment] 2020-01-11 00:04
You don't need to do all this low level event handling stuff. The get() method accepts a writeable stream, which is used to pip() the data from the remote file. So what you can do is something like (untested)

```
'use strict';

const SftpClient = require('ssh2-sftp-client');
const parse = require('csv-parse');
const transform = require('stream-transform');


const parser = parse({
  delimiter: ':'
});

// this transformer can do whatever you want to each record
// from the csv file. You don't have to use it if you don't want
// to. 
const transformer = transform(function(record, callback){
  setTimeout(function(){
    callback(null, record.join(' ')+'\n');
  }, 500);
}, {
  parallel: 5
});

// In this pipeline, the parser converts the raw text into a record
// and passes this to the transformer, which in turn just turns the
// record into a line with each item form the record separated by a space.
// It then passes that output to process.stdout, which just displays the
// data on stdout.
const pipeline = parser.pipe(transformer).pipe(process.stdout);

const config = {
  host: 'example.com',
  user: 'fred',
  password: 'secret'
};

const client = new SftpClient();

client.connect(config)
  .then(() => {
    return client.get('/path/to/remote/file.csv', pipeline);
  })
  .then(rslt => {
    console.log(`Get finished: ${rslt}`);
    return client.end();
  })
  .catch(err => {
    console.log(err.message);
  });


```

I do something similar to download gzipped files and have them unzipped. I create a zlib stream which will unzip data passed to it and then pipe that to a file write stream which will write the uncompressed data to the file system. I then just pass the pipeline in as the stream argument and let the pip() method take care of all the event handling. Most of the time, you are far better off using pip() for most things.

**Comment by Zendor18** [comment] 2020-01-11 09:00
It's strange, i get same error even with this implementation:

```javascript
const grabFile = (path) => {
  const client = new SftpClient();
  return client.connect({
    username: 'login',
    password: 'pass',
    host: 'ftp',
  }).then(() => client.get(path, `${Math.random()}.txt`)).then(res => {
    console.log('get finished');
    return client.end();
  });
};

grabFile('path_to_file1').then(() => grabFile('/nnolen/siticard/sad/FL_insurance_sample (copy).csv')).then(_ => console.log('done!'));
```
But it's crashing after 1st file was completely processed, grabFile function never gets called second time.
What could be wrong? Maybe settings of the ftp server or something?

**Comment by Zendor18** [comment] 2020-01-11 09:01
It's strange, i get same error even with this implementation:

```javascript
const grabFile = (path) => {
  const client = new SftpClient();
  return client.connect({
    username: 'login',
    password: 'pass',
    host: 'ftp',
  }).then(() => client.get(path, `${Math.random()}.txt`)).then(res => {
    console.log('get finished');
    return client.end();
  });
};

grabFile('path_to_file_one').then(() => grabFile('path_to_second_file')).then(_ => console.log('done!'));
```
But it's crashing after 1st file was completely processed, grabFile function never gets called second time.
What could be wrong? Maybe settings of the ftp server or something?

**Comment by theophilusx** [comment] 2020-01-11 11:18
No idea. Not seen that error before. 

What version of node are you using, what platform are you running on and do you know what sort of sftp server you are connecting to (platform, type, etc).

**Comment by theophilusx** [comment] 2020-01-11 11:29
have a look in the tools directory of the repository. There is a script called lowlebel-fastget.js. This script just uses the ssh2 module (no ssh2-sftp-client stuff) to perform a fast get on a file multiple times. You can first try running that script and see if it works. If you get the same or similar eror, then the problem is with ssh2 and ssh2streams and an issue will need to be logged against that module upstream or there is a problem with your sftp server. meanwhile, i will knock up a simple lowlebel-get.js script which you can try as well.

**Comment by Zendor18** [comment] 2020-01-11 12:15
lowlebel-fastget.js is worked for me (tried multiple times with big files)! So problem is not with ssh2 i suppose. My node version is v12.10.0, os: Ubuntu 19.10. All i know about ftp server: 215 UNIX Type: L8

**Comment by theophilusx** [comment] 2020-01-11 12:29
OK, now try running the script example/bulk-get.js and see if you get the error. If it works, then the problem is almost certainly in your code and not the ssh2-sftp-client module. If you get the same error, then there is an issue and it will need further investigation.

**Comment by Zendor18** [comment] 2020-01-11 13:10
I tried example/bulk-get.js and it works. I also tried to replace get with fastGet in my code and it worked for me. Maybe there are problem only with get interface?

**Comment by theophilusx** [comment] 2020-01-11 19:38
Zendor18 <notifications@github.com> writes:

> I tried example/bulk-get.js and it works. I also tried to replace get with fastGet in my code and it worked for me. Maybe there are problem only with get interface?


but example/bulk-get.js is using the get interface, so I suspect it is
something else in your code.

**Comment by theophilusx** [comment] 2020-02-11 21:57
Looks  likely this is a server bug and not something ssh2 or ssh2-sftp-client can do much about. Closing for now.

**Closed by theophilusx** 2020-02-11 21:57 UTC
Labels: more info
