### ISSUE TITLE
uncaught exception when sftp.put using non binary data

### ISSUE THREAD

**Issue by Speedkore** [theophilusx/ssh2-sftp-client#197] opened 2019-12-20 20:33 UTC
- If i put an url to a binary like a zip file it works, if i put an url like "http://google.com" (non binary data) throws the exception bellow
- Setting encoding:null seems make no effect
- I can't use a temp intermediary file

Any idea why is throwing this exception, or at least how can i catch it so it doesn't crash the whole app?  

```
const response = await axios.get(url, {headers: { 'token': params.token }, timeout: 30000, responseType: 'stream'});
await sftp.put(response.data, `files/file-${params.timestamp.getTime()}.zip`,  { encoding: null })
```
```
error: uncaughtException: Failure
Error: Failure
    at SFTPStream._transform (/data/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (/data/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SFTPStream.Writable.write (_stream_writable.js:294:11)
    at Channel.ondata (_stream_readable.js:666:20)
    at Channel.emit (events.js:182:13)
    at Channel.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Channel.Readable.push (_stream_readable.js:219:10)
    at SSH2Stream.<anonymous> (/data/node_modules/ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (events.js:182:13)
    at SSH2Stream.EventEmitter.emit (domain.js:441:20)
```

**Comment by theophilusx** [comment] 2019-12-21 06:47
Speedkore <notifications@github.com> writes:

> - If i put an url to a binary like a zip file it works, if i put an url like "http://google.com" (non binary data) throws the exception bellow
> - Setting encoding:null seems make no effect
> - I can't use a temp intermediary file
>
> Any idea why is throwing this exception, or at least how can i catch it so it doesn't crash the whole app?  
>
My guess would be that the response.data isn't a valid stream. I would
try sending (piping) that stream to a local file and see what happens.

With respect to catching the error, it should be catchable with a
try/catch block. However, there was an issue found with some errors
being emitted that were not being correctly cautht and handled that
*might* be the cause. This issue has bene resolved in the
econrest-handling branch. I plan to release a new version that applies
this fix in the next day or so, but in the meantime, you could try using
that branch and see if it helps. 

-- 
Tim Cross

**Comment by Speedkore** [comment] 2019-12-21 08:45
Yeah through a local temporal file it works but i can't use it for other reasons. I will try this econrest-handling branch!

**Comment by theophilusx** [comment] 2019-12-21 23:44
The error returned by ssh2-streams is not very informative, but usually indicates either the stream you are passing into put() or the path you are trying to upload to have issues. My suggestion to pip() the data from response.data to a local file will verify that the value returned in the response object is valid (I don't mean to use that all the time - just for simple test). If that works fine, I would try uploading the temp file to the same destination path and verify that works OK. If it doesn't, I would try to do the same thing using just standard sftp client. 

I have just pushed v4.3.1 to npmjs.com

**Comment by Speedkore** [comment] 2019-12-22 11:14
You were right man `the path you are trying to upload to have issues`, it was a random failure caused by google storage with the  bucket lock policy feature that prevents delete/write a file that is already in the bucket for the period of time you specify. 

Seems that ssh2 is trying to modify in some way the file that was just written and then as it is not able to do so, throws that exception, i was using gcsfuse to mount a folder in the sftp server to the storage bucket as well. Big files were working but little files were causing problems who knows why, anyway many thanks man!

**Closed** 2019-12-22 14:05 UTC
