### ISSUE TITLE
Unhandled 'error' event when calling end()

### ISSUE THREAD

**Issue by rwolthuis** [theophilusx/ssh2-sftp-client#195] opened 2019-12-12 21:24 UTC
Versions:
NodeJS: v12.13.1
ssh2-sftp-client - 4.3.0

As the title already says, everytime I call the client.end() function, the application throws an error which I cannot seem to catch. Note that before I call the end function, I am able to connect, upload a file, list the remote directory and download a file. All of these actions succeed as expected.

The error i'm getting:
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/home/energyio/node_modules/ssh2/lib/client.js:307:10)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}

I tried to catch the error using try/catch blocks and by listening for errors on the sftp client aswell as the ssh 'client' (ssh2 object) inside the sftp object. Neither works.

Maybe it's good to mention that I'm connecting to an Azure SFTP server. I don't have any other SFTP servers to my disposal to test against. The error is thrown using the example code on git aswel as my own implementation.

Did anyone face the same problem or maybe know the solution to this problem?

**Comment by theophilusx** [comment] 2019-12-12 22:07
That error indicates the remote sftp server is resetting the connection. Why it is doing this and raising it as an error when you call end() is a bit of a mystery. 

As part of the end() call, the module does remove all listeners, which may explain why it is an uncaught exception (we remove the listeners to prevent the possible growth/memory leak associated with adding listeners should the client be re-used to open another connection - maybe might need to re-think that strategy as there could be a timing/race condition i.e. module issues end call and removes listeners then remote server raises an error signal which is no longer caught. 

In general, you cannot use try/catch to reliably catch exceptions raised via an 'emit' as the try/catch block has typically ended before the error is emitted (there is a bit about this in the node manual under the events sections). 

things I would try

1. Use just the SSH2 module and see if you can add an error handler to catch the error. If that works, then we will need to look at how we clear handlers after a connection is ended.  If when using just the ssh2 module, we cannot catch/handle the error in a clean way, it may be necessary to raise an issue with the ssh2 author.  There are some example scripts in the tools directory of the repo which shows how you can use just the ssh2 module. 

In the meantime, I'll re-visit the end() method and see if there is something which can be done to improve the situation. I don't have access to azure,, so may need to get you to test anything I tweak to see if it improves the situation or not.

**Comment by theophilusx** [comment] 2019-12-14 05:21
I have created a new branch called 'econreset-handling' which adds some additional logging and slightly modifies the uncaughtException listener. Try this branch out and see if it makes a difference and/or provides some additional information which may help identify the issue. 

I suspect this may be an issue with the Azure sftp server and may be something which needs to be sorted out in the upstream ssh2 module. I have added two scripts which might help verify this. 

The first script is example/bulk-fastget.js. It will connect, download a file multiple times and then disconnect. It uses the ssh2-sftp-client module. The second script is tools/lowlevel-fastget.js, which does the same thing, but only uses the ssh2 module. If you see the same error with that script as you do with the bulk-fastget.js script, then we know the issue is due to the way the error is being imitted in the ssh2 module (and little can be done to 'manage' it in ssh2-sftp-client). 

both scripts take 3 command line arguments 

1. The path to a remote file to use for the download. I uploaded the test/testData/test-file1.txt file for testing as it is a reasonable size. 
2. The path to a local directory where the downloaded files will be stored
3. A repeat count that determines how many times the file should be downloaded. Note that it will keep separate copies for each download, so be aware of space requirements if you do large numbers. 

In your case, you probably don't need to do large numbers of downloads as your issue arises when you disconnect. A repeat of 2 or 5 should be sufficient. 

Try out the scripts and even try running the main client version and see how it goes. You should still get the error, but it will be logged rather than leading to the script exiting.

**Comment by rwolthuis** [comment] 2019-12-14 20:40
Thanks for your extensive replies and effort theophilusx!

I haven't had the time to test the branch, i'll come back to that later. I did however tried removing the utils.removeListeners functions from the index.js in the src folder and commented out line 914 (your build-in error listner) for testing purpuses. Now I am able to catch the error myself using either:

var sftp = new Client;
sftp.on('error', ...
- or -
sftp.client.on('error', ...

I think your theory about timing/racing conditions might be right. The error is most likely being thrown after the error listners are removed.

Looking at the [https://github.com/mscdex/ssh2-streams/](url) library that the SSH2 library uses, it seems to send a disconnect package to the server. My guesses are that the Azure server will instantly kill the connection upon receiving such disconnect package, causing the error. See [https://github.com/mscdex/ssh2-streams/blob/master/lib/ssh.js#L829](url).

I'm out of idea's on how you could realiablely remove the listners after the connection is closed.

**Comment by theophilusx** [comment] 2019-12-15 22:09
I have updated the econreset-handling branch which I think should fix
your issue and allow you to have your own end or close listeners.

- Updated end() method to move both removeListeners() and resolve() call
  into a close listener. As the close event is the last event raised
  when a connection terminates, this should address the race condition.

- Modified end listener to only log an error and don't throw any
  exception. Leave it to the client to decide if they want to take
  action on an end event via custom listener.


-- 
Tim Cross

**Comment by theophilusx** [comment] 2019-12-20 14:29
Other testing has shown that the error event is now successfully handled by the promise and can now be caught in normal try/catch. Therefore, recommend using the econreset-handling branch until a merge it into master and release a new version.

**Comment by theophilusx** [comment] 2019-12-21 23:51
Version 4.3.1 has been pushed to npmjs.com. I expect it has resolved the issue with errors causing uncaught exception issues. However, if Azure is causing ssh2 or ssh2streams to throw an error when ending a connection, there is not much I can do about that (you would need to handle/ignore that error in your code).

**Comment by rwolthuis** [comment] 2019-12-23 14:44
Thanks for your help theophilusx!

I've updated to 4.3.1, used the same code but unfortunally I'm still unable to catch errors using either the .catch(err or sftp.on('error'... methods, which causes the process to stop. See the attached test.txt file for the code i'm using.

If, however, I comment out [line 1017 in the index.js file](https://github.com/theophilusx/ssh2-sftp-client/blob/master/src/index.js#L1017) the error that is emitted is being caught by line 12 in my test.txt file and the process continues.

Attached: [test.txt](https://github.com/theophilusx/ssh2-sftp-client/files/3995294/test.txt)

**Comment by theophilusx** [comment] 2019-12-23 15:58
The real problem here is that your remote sftp server is causing an
error to be raised when the connection is being closed. I believe this
is an issue with the azure sftp server.

The reason commenting out that line works is that it prevents your error
handler from being removed (we setup special connection error handlers
and just remove all of them after a connection is established - probably
shouldn't do that and should just remove the handlers we have
added). Unfortunately, just commenting out that line causes other
problems and cannot be used as a solution. (If you add your handler
after connecting, it should work fine).

There are a couple of other changes I'm currently testing wrt error
handling outside of a promise e.g. when a econnreset occures between
calls to various methods.

for your specific issue, I think the best solution is to add a special
error handler for the end() call which will just ignore any errors which
are raised during the disconnect process. Bottom line, if we have called
end() we really don't care if the remote server raises an error - we are
done with the connection and don't really care as long as the connection
is ended. I'll just log the error to console.error. This should prevent
the uncaughtException issue and allow the connection to close and exit.

I'll let you know when I've made the change and the name of the branch
you can try.


--
Tim Cross

**Comment by theophilusx** [comment] 2020-01-14 22:39
This issue should now be resolved in the release-5.0.0 branch of the repository.

**Comment by theophilusx** [comment] 2020-01-16 07:29
Closing this issue as the original problem of error events being trigged when end() is called by azure sftp has been resolved in current version. Any errors raised once end() is called are ignored.  the error is logged to console.out().

**Closed by theophilusx** 2020-01-16 07:29 UTC
Labels: more info, test

**Comment by builtbylane** [comment] 2020-04-13 21:32
Hi @theophilusx Thanks for all your work on this. 

We're experiencing a similar issue with an FTP server when we call `.end()`. It happens on node v11 - 13 on linux and mac. We haven't found a way to resolve it or hide the error. 

Do you have any suggestions on how to resolve, or how to describe the issue to the FTP provider? 

```bash
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
CLIENT[sftp]: Removing listener from error
DEBUG: Outgoing: Writing CHANNEL_CLOSE (0)

CLIENT[sftp]: Removing listener from error
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (***/node_modules/ssh2/lib/client.js:307:10)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}```

**Comment by theophilusx** [comment] 2020-04-13 23:08
Can you verify you are using v5.2.1 of ssh2-sftp-client?

thanks.

**Comment by builtbylane** [comment] 2020-04-14 02:50
@theophilusx Yes, using v5.1.2

**Comment by theophilusx** [comment] 2020-04-14 23:42
OK, I've made a minor tweak tot he end() method which *might* help. This
has been pushed to the master branch.

It seems there are some SFTP servers - notably Azure's sftp, which raise
an error after receiving an end request. This is not standard behaviour
and is difficult to deal with reliably.

The tweak I've made should help and provided your end() call is inside a
try/catch block, it should be possible to catch the error in your
script. Please test with the current git repository version (master
branch) and see if that helps.

If you are still getting an uncaught error exception, all I can suggest
is that you add your own error handler using the on() method. If you do
this, you will need to ensure you manage that handler i.e. if you re-use
the client object, be aware that if you add an error handler every time,
it will eventually exceed the limit and you will get the warning about
possible memory leaks (node tracks the number of handlers on a signal
and raises a possible memory leak error if an event has more than 10
handlers).

Let me know how your testing goes. If it helps, I'll release a new version.

**Comment by builtbylane** [comment] 2020-04-15 02:49
Thank you @theophilusx for this attempt. The error has not changed, there was just one fewer line in the debug output:

~`DEBUG: Outgoing: Writing CHANNEL_CLOSE (0)`~

otherwise the output was the same:

```bash
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
CLIENT[sftp]: Removing listener from error
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (***/node_modules/ssh2/lib/client.js:307:10)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
```
We will try adding the custom error handler in the meantime and report back with any fix. 

We'll also work on getting the FTP host configuration to include here for future reference.

Thanks again, and let us know if you think of any other potential fixes.

**Comment by theophilusx** [comment] 2020-04-15 03:16
I was worried it wouldn't help much, but had to have a try.

If your able to put together a minimal script which generates the error,
that would be handy in helping test/reproduce the issue. Also, any
details on the remote FTP server would be good as I test against a few
different servers and cannot reproduce the issue. Knowing exactly what
the remote server software is may help.

**Comment by builtbylane** [comment] 2020-04-15 18:53
The server that is giving us trouble is running *Open SSH 7.9p1* on *Windows Server 2016 - Datacenter*

**Comment by theophilusx** [comment] 2020-04-15 21:50
Hmmm, I certainly cannot reproduce that issue on other platforms with
openSSH and I will freely admit I'm way out of my depth when it comes to
Windows. I do have a virtualbox VM running w10 with openSSH on it and
cannot reproduce that issue. What does the 'Datacenter' bit refer to? A
virtual on premise (VMWare) server or something else, like virtual
running in Azure?

**Comment by builtbylane** [comment] 2020-04-17 13:57
Confirmed, the FTP server is running on Azure.

**Comment by theophilusx** [comment] 2020-04-18 04:36
So this seems to be an issue specific to Azure. For some reason, after
receiving a disconnect (end()) request, Azure is sending a connection
reset by peer error. It must also be sending that event after the client
end() promise has run and resolved, which would be why the error handler
in that method does not catch and handle the event.

I don't want to add a 'global' error handler as this could have adverse
impact on the client in other environments, potentially hiding error
events which need to be seen, leading to silent failure which users
might find confusing. However, you could try this in your environment.
Adding something like (untested off top of head!)

const client = new SftpClient();

client.on('error', e => {
  if (e.code !== 'ECONNRESET') {
    throw e
  }
});

which should effectively ignore any ECONNRESET error events while the
listener is active. As the listener has 'handled' the event, you should
not see any unhandled exception errors. If your concerned this may hide
issues, you could add a console.log when the error is ECONNRESET. This
will created noise in your logs, but some would prefer noisy logs over
missing information.

**Comment by builtbylane** [comment] 2020-04-20 19:07
thank you @theophilusx. agreed, it's not worth updating the library for this edge case. We're ignoring the error just as you suggested. We just wait to attach the error handler until right before ending the connection so that there's no other side-effects. 

```javascript
function end() {
  sftp.on('error', error => {
    if (error.code !== 'ECONNRESET') throw error;
    // else console.log('👋  Ending connection (ignoring error)');
  });
  return sftp.end();
}
