### ISSUE TITLE
100% reproducible bug that results in node process crash when using promises (bug in promise reject)

### ISSUE THREAD

**Issue by chubbob** [theophilusx/ssh2-sftp-client#453] opened 2022-12-09 05:23 UTC
Version: 9.0.4
Node: v18.12.0
OS: Mac OS 12.1

Problem manifests itself if network becomes inaccessible after Client.connect was already successfully executed but before Client.put method is called.

Code Snippet:

```
let Client = require('ssh2-sftp-client');
let sftp = new Client();

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

async function run() {
  const startTime = Date.now();
  const filename = `random-file-name-${startTime}`;

  const fileData = Buffer.from('TRACER FILE');
  const remotePath = `incoming/${filename}`;

  try {
    console.log(`---- Before connect ----- `);

    await sftp.connect({
      host: '1.1.1.1',
      port: 22,
      username: 'user',
      password: 'password',
    });

    console.log(`---- After connect ----- `);
    
    console.log(`---- Sleep for 20s ----- `);

    // !!!!!!!   BREAK CONNECTION HERE while sleeping
    await sleep(20000);

    console.log(`---- Before put ----- `);
    const result = await sftp.put(fileData, remotePath);
    console.log(`---- After put ----- `);
    console.log(`SFTP put result: ${result}`);
    sftp.end();
  } catch (err) {
    console.error(`Error: ${err.message}`);
  }

  await sleep(7000);

  console.log('The End');
}

run();
```

Log from the run that completes successfully:

```
---- Before connect ----- 
---- After connect ----- 
---- Sleep for 20s ----- 
---- Before put ----- 
---- After put ----- 
SFTP put result: Uploaded data stream to incoming/random-file-name-1670562812521
The End
```

Log from the run that crashes with disconnect during sleep(20000):

```---- Before connect ----- 
---- After connect ----- 
---- Sleep for 20s ----- 
---- Before put ----- 
/project/node_modules/ssh2-sftp-client/src/utils.js:25
      throw newError;
      ^

Error: put: read ETIMEDOUT
    at Client.fn (/project/node_modules/ssh2-sftp-client/src/utils.js:20:22)
    at Client.emit (node:events:525:35)
    at Socket.<anonymous> (/project/node_modules/ssh2/lib/client.js:745:12)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ETIMEDOUT'
}

Node.js v18.12.0
```

It looks that for some reason in this use-case `errorListener` method in `utils.js` is invoked with `reject` parameter set to `undefined` resulting in exception vs promise reject.

How to break connection for MacOS:
```
# PF should be started: sudo pfctl -E
# Check current ruleset: sudo pfctl -sr
# To Apply this ruleset file: sudo pfctl -f ./pf-block-ip.conf
# To Flush (all) rulesets: sudo pfctl -F rules

# Block incoming traffic from some IP
block in quick from 1.1.1.1
```

**Comment by theophilusx** [comment] 2022-12-09 06:51
I haven't got time to look at this in any detail right now. However, it
looks to me as if it is behaving as expected. I'm a little confused as
to why you state it is crashing node - from what I can see, the error is
caught by your catch handler. What is your expectation here? Howe should
this behave?

**Comment by chubbob** [comment] 2022-12-09 13:44
No, the error is not caught and is not propagated to any of my try/catch blocks up the stack. Node process just crashes.

**Comment by chubbob** [comment] 2022-12-09 14:26
The error 100% reproducible. Looking at the code of `put` method it seems there's an issue with how `errorListener` is set up. But none of catch blocks are executed.

**Comment by chubbob** [comment] 2022-12-10 01:53
> I haven't got time to look at this in any detail right now. However, it looks to me as if it is behaving as expected. I'm a little confused as to why you state it is crashing node - from what I can see, the error is caught by your catch handler. What is your expectation here? Howe should this behave?

I believe in case of error `.put` method should resolve with rejected promise and should not crash node process.

**Comment by theophilusx** [comment] 2022-12-10 02:52
The odd thing is that the put() method is raising an error as can be
seen by the 'put:' in the error message i.e.

Error: put: read ETIMEDOUT

The put() method is an async method, which means that if an error is
thrown it will return a rejected promise. This seems to be happening and
from your log output, we can see that nothing is executed after the
error is raised.

What isn't clear is why your catch is not catching that error. Put is
raising the error, but catch is not catching it?

Two things you should try

1. Add a debug printer to the connect options i.e.

sftp.connect({
   ....
   debug: (msg) => console.log(msg)
 })

2. Add a catch to the run() chain. It is an error to have a top level
promise without a catch handler. As run() is async, it returns a
promise, so really it should be

run().catch(e => console.error(e));

The above catch should not really be necessary because you have an inner
try/catch block. However, having it won't do any harm either and just
ensure there isn't something odd going on (or at least highlight it
better if there is).

Oh and also, sftp.end is an async function, so that should also have an
await. Without it, any errors occurring when calling sftp.end are likely
to cause the node process to exit as well because it is possible the
run() function will have completed before the end() has completed and
any rejected promise or thrown errors will end up at the top
level. Actually, I would put the end() call in a finally block so that
it is called even if there are errors - just a good habit to form.

One other thing to try would be to see what happens when you pass in a
stream or a filename rather than a buffer.

**Comment by chubbob** [comment] 2022-12-12 02:25
Tim,

I'd like to emphasize the fact, that this crash is 100% reproducible and not dependent on any variations. You just need to run the snippet I provided, drop connection during the sleep and you'll reproduce the problem, I'm absolutely sure about this. I strongly recommend to run the snippet at least once - you'll instantly see the issue.

Now about points you mentioned:

1. Correct .put is an async method, but if you internally use some IO api based on callbacks, then stack of that callback call is separate from the stack of .put method. Thus any exception raised while processing an internal callback will not bubble up to my try/catch and will result in uncaught exception.

3.  Adding .catch to the run chain won't do much because run() method is an async method meaning that that an exception should be thrown on the same stack as .put method. But if it would do so - I'll catch it in my internal try/catch method.

4. The stack that suppose to run sftp.end method is not executed thus await on this part won't change anything. By the way, many examples published in README do not have await for sftp.end. Is this something critical for .put only? Anyway, I changed that too to no avail.

Just to speed up the investigation I did what proposed with exactly the same result. Here is the snippet of updated code:
```
let Client = require('ssh2-sftp-client');
let sftp = new Client();

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

async function run() {
  const startTime = Date.now();
  const filename = `random-file-name-${startTime}`;

  const fileData = Buffer.from('TRACER FILE');
  const remotePath = `incoming/${filename}`;

  try {
    console.log('---- Before connect ----- ');

    await sftp.connect({
      host: '1.1.1.1',
      port: 22,
      username: 'user',
      password: 'password',
      debug: (msg) => console.log(msg),
    });

    console.log('---- After connect ----- ');
    console.log('---- Sleep for 20s ----- ');

    await sleep(20000);

    console.log('---- Before put ----- ');
    const result = await sftp.put(fileData, remotePath);
    console.log('---- After put ----- ');
    console.log(`SFTP put result: ${result}`);
  } catch (err) {
    console.error('ERROR: internal catch');
    console.error(`Error: ${err.message}`);
  } finally {
    console.log('---- Executing finally for .end() ----- ');
    await sftp.end();
  }

  await sleep(1000);

  console.log('The End');
}

try {
  run()
    .then(() => {
      console.log('Run executed SUCCESSFULLY');
    })
    .catch((err) => {
      console.log('Run FAILED:', err);
    });
} catch (err) {
  console.error('ERROR: external catch');
  console.error(`Error: ${err.message}`);
}
```

And here you can find the entire log from the run (with disconnect during sleep):
```
---- Before connect ----- 
CLIENT[sftp]: connect: Debugging turned on
CLIENT[sftp]: ssh2-sftp-client Version: 9.0.4  {
 "node": "18.12.0",
 "v8": "10.2.154.15-node.12",
 "uv": "1.43.0",
 "zlib": "1.2.11",
 "brotli": "1.0.9",
 "ares": "1.18.1",
 "modules": "108",
 "nghttp2": "1.47.0",
 "napi": "8",
 "llhttp": "6.0.10",
 "openssl": "3.0.5+quic",
 "cldr": "41.0",
 "icu": "71.1",
 "tz": "2022b",
 "unicode": "14.0",
 "ngtcp2": "0.8.1",
 "nghttp3": "0.7.0"
}
CLIENT[sftp]: connect: Connect attempt 1
Custom crypto binding available
Local ident: 'SSH-2.0-ssh2js1.11.0'
Client: Trying 1.1.1.1 on port 22 ...
Socket connected
Remote ident: 'SSH-2.0-Unknown_1.0.0'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
Handshake: KEX algorithm: ecdh-sha2-nistp256
Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Handshake: (remote) Host key format: ssh-dss,ssh-rsa
Handshake: Host key format: ssh-rsa
Handshake: (local) C->S cipher: chacha20-poly1305@openssh.com,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
Handshake: (remote) C->S cipher: blowfish-cbc,3des-cbc,aes128-cbc,aes192-cbc,aes256-cbc,aes128-ctr,aes192-ctr,aes256-ctr
Handshake: C->S Cipher: aes128-ctr
Handshake: (local) S->C cipher: chacha20-poly1305@openssh.com,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
Handshake: (remote) S->C cipher: blowfish-cbc,3des-cbc,aes128-cbc,aes192-cbc,aes256-cbc,aes128-ctr,aes192-ctr,aes256-ctr
Handshake: S->C cipher: aes128-ctr
Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) C->S MAC: hmac-md5,hmac-md5-96,hmac-sha1,hmac-sha1-96,hmac-sha2-256,hmac-sha2-512
Handshake: C->S MAC: hmac-sha2-256
Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) S->C MAC: hmac-md5,hmac-md5-96,hmac-sha1,hmac-sha1-96,hmac-sha2-256,hmac-sha2-512
Handshake: S->C MAC: hmac-sha2-256
Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
Handshake: (remote) C->S compression: none,zlib
Handshake: C->S compression: none
Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
Handshake: (remote) S->C compression: none,zlib
Handshake: S->C compression: none
Outbound: Sending KEXECDH_INIT
Received DH Reply
Host accepted by default (no verification)
Host accepted (verified)
Outbound: Sending NEWKEYS
Inbound: NEWKEYS
Verifying signature ...
Verified signature
Handshake completed
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received SERVICE_ACCEPT (ssh-userauth)
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_BANNER
Inbound: Received USERAUTH_FAILURE (password)
Client: none auth failed
Outbound: Sending USERAUTH_REQUEST (password)
Inbound: Received USERAUTH_SUCCESS
CLIENT[sftp]: getConnection ready listener: got connection - promise resolved
Outbound: Sending CHANNEL_OPEN (r:0, session)
Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
Inbound: CHANNEL_WINDOW_ADJUST (r:0, 27)
Inbound: CHANNEL_SUCCESS (r:0)
Outbound: Sending CHANNEL_DATA (r:0, 9)
Inbound: CHANNEL_DATA (r:0, 9)
SFTP: Inbound: Received VERSION (v3)
CLIENT[sftp]: getSftpChannel: SFTP channel established
---- After connect ----- 
---- Sleep for 20s ----- 
---- Before put ----- 
Outbound: Sending CHANNEL_DATA (r:0, 71)
SFTP: Outbound: Buffered OPEN
CLIENT[sftp]: put source is a buffer
Socket error: read ETIMEDOUT
/project/node_modules/ssh2-sftp-client/src/utils.js:25
      throw newError;
      ^

Error: put: read ETIMEDOUT
    at Client.fn (/project/node_modules/ssh2-sftp-client/src/utils.js:20:22)
    at Client.emit (node:events:525:35)
    at Socket.<anonymous> (/project/node_modules/ssh2/lib/client.js:745:12)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ETIMEDOUT'
}

Node.js v18.12.0
```

**Comment by theophilusx** [comment] 2022-12-12 04:36
> Tim,
>
> I'd like to emphasize the fact, that this crash is 100% reproducible and not dependent on any variations. You just need to run the snippet I
> provided, drop connection during the sleep and you'll reproduce the problem, I'm absolutely sure about this. I strongly recommend to run the
> snippet at least once - you'll instantly see the issue.
>

I"m not questioning the fact it crashes. However, I'm not sure your
conclusion is correct. As I stated before, I won't have time to look at
this in any detail until after the new year.  

If you can diagnose further or if you want to provide a PR, that would
be great, otherwise, you will have to wait until I get to it.

**Comment by chubbob** [comment] 2022-12-12 19:35
Sounds good.

The reason why exception is not bubbling up to my try/catch is identical to the issue with the code below. This code will result in unhandled exception as well:

```
async function run2() {
  try {
    setTimeout(() => {
      throw new Error('this is a test message');
    }, 10);
  } catch (err) {
    console.log('ERROR');
  }
}

try {
  run2()
    .then(() => {
      console.log('Run executed SUCCESSFULLY');
    })
    .catch((err) => {
      console.log('Run FAILED:', err);
    });
} catch (err) {
  console.error('ERROR: external catch');
  console.error(`Error: ${err.message}`);
}
```

**Comment by chubbob** [comment] 2023-01-13 03:21
@theophilusx: Greetings. Is there any news on this issue? I tried to dive into the code myself, but unfortunately I got lost after a while. I'm not fully follow the logic that coverts callback events into promise rejections. Any help is highly appreciated.

**Comment by theophilusx** [comment] 2023-01-13 04:19
Unfortunately I've not had time yet. My other task I need to finish
first has run over and until it is completed, I cannot allocate time to
this issue. With luck, I should be able to get to it in a couple of
weeks time.

**Comment by madkarlsson** [comment] 2023-02-08 13:53
Just randomly passed through here. That behaviour is not strange if you look at how this is structured:

```
try {
    setTimeout(() => {
      throw new Error('this is a test message');
    }, 10);
  } catch (err) {
    console.log('ERROR');
  }
```

setTimout is run outside of the context of the try catch (it's asynchronous, the code goes on and finishes without it).

You need to put the try inside of a setTimeout for that specific catch to happen, but if you have more complex flows, [wrap in a promise](https://stackoverflow.com/questions/54186748/how-to-handle-catch-error-with-settimeout)

**Comment by chubbob** [comment] 2023-02-08 18:29
You don't need to convince me. That's exactly what I'm trying to explain here. It's just an example. However internal logic of this lib is not that obvious to fix it.

**Comment by theophilusx** [comment] 2023-02-08 22:51
Michael Karlsson ***@***.***> writes:

> setTimout is run outside of the context of the try catch (it's asynchronous, the code goes on and finishes
> without it).
>

While you are correct with respect to the use of try/catch and events,
this issue here is not that straight forward.

- Adding setTimeout calls around all the library calls to ssh2 in this
  module would degrade performance to an unacceptable level

- The calls to the ssh2 API area already all wrapped in promises.

The logic involved here is complicated and finding a fix which does not
have significant negative impact on all other operations is
difficult.

It is important to remember that this is an extremely rare error which
can only be triggered by suddenly and permanently disabling the network
stack while in the middle of a file transfer. In over 6 years of
extensive and heavy use, this issue has never been seen by me and never
reported by anyone until now. It is quite possible this may end up being
a known problem which client code will need to defend against if it is
an issue for them - I don't know, I've only just started looking at this
in detail in the last day or so.

**Comment by chubbob** [comment] 2023-02-09 14:17
Just for information - this crash happened to us 4 times during the last 2 days only. So this issue is not so rare.

**Comment by theophilusx** [comment] 2023-02-10 00:21
Well I would suggest that you really need to look into why your network infrastructure is so unreliable. While I will try to find a way to avoid the crashing, it is really a symptom of a far more fundamental issue in your environment. As I said, your the only one encountering this issue (or at least the only one reporting it). 

At present, I'm still finding it hard to find a reliable method to simulate the same network failure. I don't have a mac anymore and my attempts with linux iptables have yet to yield the desired error (so far I get connection refused, connection reset or host unreachable errors, but no timeout error. All of these errors are handled and caught as expected). 

I have made some minor changes to error messages which might help a little, so while I try to reproduce this issue locally, would be good if you can run using head of git master and send the results (including debug logging).

**Comment by chubbob** [comment] 2023-02-10 00:45
Thanks a lot. I will definitely do that and test master ASAP.

**Comment by theophilusx** [comment] 2023-02-10 02:29
BTW given the lack of stability in your network, I would highly recommend adding the keepaliveInterval property to the config object. I would try a keepaliveInterval: 1000. This will ensure that ssh2 sends pings every second to verify the remote server is still responding. This will have two benefits. Firstly, it means that it is highly likely that the lost connection will be detected before attempting to transfer the data (this generates a catchable error) and the second advantage is that the system will fail much faster than it does waiting for a timeout (On default Linux servers, that timeout is VERY long).

**Comment by theophilusx** [comment] 2023-02-10 06:49
OK I have figured out what is going on and can fix it. However, this is a real PITA and it is going to take a lot of work, so I'm afraid you won't see this resolved quickly.  If this is something you require now, my suggestion would be to use just ssh2 or perhaps there is another module you can use instead of this one.

**Comment by chubbob** [comment] 2023-02-10 14:42
Thank you very much for you effort! I understand the complexity of the issue - I'd fix it myself if that would be easy. We'll look into other options too. Thanks for the hint.

**Comment by theabuitendyk** [comment] 2023-03-22 19:52
@chubbob I'm running into a similar issue. Did you end up finding a fix or way around it?

**Comment by chubbob** [comment] 2023-03-22 19:55
@theabuitendyk : we have worked around it in our business logic, but bug is still present.

**Comment by theophilusx** [comment] 2023-04-25 03:44
I am no longer able to reproduce this error using current head of the master branch. Will be releasing new version this week, so closing this issue.

**Closed by theophilusx** 2023-04-25 03:44 UTC

**Comment by chubbob** [comment] 2023-04-26 20:35
Great! Looking forward for 9.1.0 release! Can you please just tag us here in this thread when it's published?

**Comment by theophilusx** [comment] 2023-05-02 23:25
9.1.0 pushed to npmjs
