### ISSUE TITLE
MaxListenersExceededWarning after more than 10 GETS

### ISSUE THREAD

**Issue by tibistibi** [theophilusx/ssh2-sftp-client#539] opened 2024-06-20 18:36 UTC
Hi have a list of files which i all want to GET but after 10 i get MaxListenersExceededWarning error

I have a Lambda on AWS with nodjes20 code. It opens a connection and does a list to get a list of filenames.
For every file a do a GET. It looks like this:

```
    const sftp = new Client();
    await sftp.connect({
      host: '******,
      port: 22,
      username: credentials.username,
      password: credentials.password,
    });

    const directoryList = await sftp.list('/OUT');
    const namesList = directoryList.map(item => item.name);
    await Promise.all(namesList.map(name => sendFileToBacSftp(name)));

async function sendFileToBacSftp(fileName){
  const stream = await sftp.get(`/OUT/${fileName}`);

}
```

ERROR	(node:8) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Client]. 
ERROR	(node:8) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Client]. 
ERROR	(node:8) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Client]. 

Should I clear end, close and error from the stream or sftp after every GET?

It is a warning so the code works but i would like to avoid error messages.

**Comment by theophilusx** [comment] 2024-06-20 22:43
Node has a built-in warning limit for the number of event listeners
which are active at any moment. The default is usually 10. As ssh2 is an
event based library (ssh2-sftp-client wraps ssh2 to add the promise
API), each time you interact with a remote sftp server, you are
interacting with an event emitter which uses listeners to manage the
interaction. There are, for example, an error listener, a close
listener, end listeners etc involved in every interaction with the
remote system.

The ssh2-sftp-client library manages these listeners (creates, listens,
removes) for each API call i.e. sftp.get(), sftp.list(), sftp.put,
etc. However, if you execute these commands concurrently, the total
number of listeners will exceed the warning limit once you reach a
certain point. This is because node has this heuristic warning message
which is triggered as soon as the total number of listeners exceed the
default number. Note that the warning doesn't mean there is a memory
leak, only that node is concerned this may be an indicator of one.

There are two ways of handling this -

1. Execute your sftp.get() calls sequentially. Note that often people
think this will be a lot slower, but you will be surprised how small a
difference it makes in most cases. Often, the real performance 
bottleneck is in the overhead of initiating the get() (or other
command) and additional overheads involved in context switching as node
has to switch between different promises. This is the easiest way to
avoid the issue you are seeing. Suggest you benchmark a version which
executes multiple get requests concurrently (using promise.all) and one
which uses just a for loop and executes them sequentially (note that the
array comprehension methods like .map, .forEach etc are NOT await/async
safe, so just use a standard for loop).

2. The second approach (which is what I use in downloadDir and
uploadDir) is to ensure that you only execute a set number of concurrent
promises at a time, avoiding the warning. You could look at the code in
these methods to see how to do it yourself.

3. Just use downlodDir(). You can pass it a filter so that only files in
the top directory are considered for download if you don't want it to
recursively traverse down the directory tree. You would just pass it a
path of '/OUT' and a filter to exclude anything which is a directory and
it would download all the files in that directory.

4. It is possible to either change the node warning limit i.e. increase
it to a higher number or disable it. Not a recommended solution as
1. what number should it be reset to and 2. what if there is a real
memory leak?

**Comment by theophilusx** [comment] 2024-07-06 08:35
There has been no further activity on this issue and based on available info, the issue is caused by client code and needs to be resolved there. Therefore closing this issue.

**Closed by theophilusx** 2024-07-06 08:35 UTC
