### ISSUE TITLE
MaxListenersExceededWarning when using downloadDir with many files (thousounds of files, over 400GB in total)

### ISSUE THREAD

**Issue by BennyAlex** [theophilusx/ssh2-sftp-client#495] opened 2023-08-06 07:42 UTC
When I try to download the complete remote storage I get MaxListenersExceededWarning in Node 18.
Listing all files works fine when I set addListeners to false. Since downloadDir will call sftp.list inside with addListeners to true, the error does occure.

// works fine
const list = await sftp.list('/', null, false);
 console.log(list); // returns 700 items, just in the root dir
    
// error
await sftp.downloadDir('/', './backup');

```
(node:11348) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11348) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(node:11348) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
```

A solution could be either increase the emitter limit with emitter.setMaxListeners() or allow to disable limiters for each function or on a global level.

**Comment by theophilusx** [comment] 2023-08-09 11:14
This is a known issue which has arisen after adopting Promise.all to speed up downloads. What you have observed is just the tip of a more complicated issue which is being worked on. Unfortunately, I am travelling for the next couple of months and won’’t be in a position To look at this until late October. My recommendation would be to not use downloadDir or uploadDir and implement that functionality yourself with the existing get/put or FastGet/fastPut. Much easier to implement for a specific use case than the general use case.Sent from my iPadOn 6 Aug 2023, at 3:42 pm, Benajmin Franz ***@***.***> wrote:﻿
When I try to download the complete remote storage I get MaxListenersExceededWarning in Node 18.
Listing all files works fine when I set addListeners to false. Since downloadDir will call sftp.list inside with addListeners to true, the error does occure.
// works fine
const list = await sftp.list('/', null, false);
console.log(list); // returns 700 items, just in the root dir
// error
await sftp.downloadDir('/', './backup');
A solution could be either increase the emitter limit with emitter.setMaxListeners() or allow to disable limiters for each function or on a global level.

**Comment by anthonytoorie** [comment] 2023-08-30 14:56
implement that functionality yourself with the existing get/put or FastGet/fastPut -> will not work. Tried it. Unless you await on each promise one by one, which is not feasible for larger directories with big files.

sftp.client.setMaxListeners(n) works to remove the warning that node will give you, but it's hacky at best.

It seems the underlying problem is not with Promise.all, but the individual fastPut, put, get, and fastGet.. at least thus far.

**Comment by theophilusx** [comment] 2023-09-06 00:36
No, I disagree. The downloadDir/uploadDir functionality is implemented using the low level get/put and/or fastGet/fastPut, which know nothing about promises (the ssh2 library is only event based, this is where most of the complexity which causes the problem comes from). 

The maxListeners warning is largely irrelevant and more a syumptom of the problem rather than the cause. 

Even if you disable the maxListenres warning or increase the level at which the warning will occur, at some point, for large enough directories, you will run into resource imitations as node tries to create too many promises at the same time. 

The correct fix is to add a parameter to the donwloadDir/uploadDir to limit the number of concurrent promises to a number which is acceptable for the available resources on the client and which defaults to something resonable. The donloadDir/uploadDir would then break the donwload/upload into groups of concurrent promises untill all the files have been transferred i.e. would do the transfer in blocks of concurrent promises which do not trigger either resource limit issues or max listener issues. 

I have not had time to do this work as it is a substantial amount to implement in a general way. However, implementing it for a single use case would not bee too difficult, which is why I suggest implement yuour own version of downloadDir/uploadDir which meets your needs using just the low level get/put or fastGet/fastPut functions (or just roll your own using pure ssh2). 

It will be some time before I have the space to work on this. I do have some pull requests to review which may improve things a little, but have not had time to do that yet.

**Comment by theophilusx** [comment] 2023-09-06 00:55
This is related to and a duplicate of #481 Marking as duplicate and closing.

**Closed** 2023-09-06 00:56 UTC
Labels: duplicate

**Comment by anthonytoorie** [comment] 2023-09-06 21:20
That’s fine to disagree. I tried limiting the number of concurrent promises and was not successful in that regard. It would be helpful if you could help us understand how you achieved a working solution with an example.

**Comment by ajithk-one** [comment] 2024-04-23 12:56
You have mentioned here as 
`A solution could be either increase the emitter limit with emitter.setMaxListeners() or allow to disable limiters for each function or on a global level.`

How to handle globally by not adding event listeners for each function like 
`await sftp.list('/', null, false);`

In code i can't see for `exists`, `stat` etc public methods.

**Comment by theophilusx** [comment] 2024-04-23 13:20
You just need to limit the number of calls you are running concurrently. i.e. don't create too large an array of promises and pass it to promise.all() expecting it to just work. You ahve to manage these resources. See how it is handled in downloadDir/uploadDir to get an idea on how you can break your list of actions up into groups of promises.
