### ISSUE TITLE
Pausing after "Received DH GEX Group"

### ISSUE THREAD

**Issue by Humphaz** [theophilusx/ssh2-sftp-client#351] opened 2021-09-16 20:36 UTC
Hi,

I know this is a bug that has been tackled, and I read a number of posts about it.

I'm still getting the same issue. I've updated to the lastest versions of everything, V7.0.4 of ssh2-sftp-client using V1.4.0 of ssh.

`Socket connected`
`Remote ident: 'SSH-2.0-7.9.0.0_openssh GlobalSCAPE'`
`Outbound: Sending KEXINIT`
`Inbound: Handshake in progress`
`Handshake: (local) KEX method: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1`
`Handshake: (remote) KEX method: diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1`
`Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256`
`Handshake: (local) Host key format: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521`
`Handshake: (remote) Host key format: ssh-rsa`
`Handshake: Host key format: ssh-rsa`
`Handshake: (local) C->S cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com`
`Handshake: (remote) C->S cipher: aes256-cbc,aes256-ctr,3des-cbc,aes128-cbc,aes128-ctr`
`Handshake: C->S Cipher: aes128-ctr`
`Handshake: (local) S->C cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com`
`Handshake: (remote) S->C cipher: aes256-cbc,aes256-ctr,3des-cbc,aes128-cbc,aes128-ctr`
`Handshake: S->C cipher: aes128-ctr`
`Handshake: (local) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1`
`Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96`
`Handshake: C->S MAC: hmac-sha2-256`
`Handshake: (local) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1`
`Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96`
`Handshake: S->C MAC: hmac-sha2-256`
`Handshake: (local) C->S compression: none,zlib@openssh.com,zlib`
`Handshake: (remote) C->S compression: zlib,none`
`Handshake: C->S compression: none`
`Handshake: (local) S->C compression: none,zlib@openssh.com,zlib`
`Handshake: (remote) S->C compression: zlib,none`
`Handshake: S->C compression: none`
`Outbound: Sending KEXDH_GEX_REQUEST`
`Received DH GEX Group`

The wait is usually around 16 seconds, and then it progresses. Its on a small VM (2xVCPU 4gb), but I wouldn't have thought it would have been an issue.

I'm now just testing going to double the size to see what happens. No difference, so I'm assuming its a single thread and the extra memory and IOPS isn't helping either. (time to go back down to the smaller VM again).

As I'm doing a LIST, then a (GET and a DELETE) x LIST size, it means I'm waiting for over 30 seconds for every transfer that takes about a second.

**Comment by theophilusx** [comment] 2021-09-16 21:30
Sounds like your making a new connection for each request (because the
kex stuff only happens once per connection). Establishing the ssh
connection is the slowest part of the protocol, so you need to structure
your code to minimise that i.e. make a connection -> call list(), get(),
delete() (for each file of interest) -> disconnect() after all work
completed.

**Comment by Humphaz** [comment] 2021-09-17 12:36
It is, it's being used in a Node Red system. I can write update the Node to ensure it doesn't close off the connection so it could be reused, it was my plan anyway, simply because, as you say, it is the bit that takes the most time. 

However, this is WAY to long, its not handshaking, I think its still an issue with Calculating the Prime. Which is a pain, because if it wasn't, I would simply be able to do 20 at the same time and all the delays would be overlapped, but its not delay, its execution peak in a single thread.

This means that it can only be improved by improving the code.

Currently I can use the command line to have connected and sent everything 10 times by the time it connects once, so something isn't optimimum.

I can't get around this issue, I can only hide it away, which is yuckity.

**Comment by theophilusx** [comment] 2021-09-17 22:07
There isn't much (anything?) which can be done at the ssh2-sftp-client
level. It might be possible to get faster results by using different
ciphers for the handshake (i.e. exclude ones known to be slower), but
that will depend on what is supported by the remote server. I don't see
the amount of delay your seeing, but suspect that is because different
ciphers are being used. 

All of this is handled by either the ssh2 module or built-in node
internals. You could try raising an issue with the ssh2 maintainer to
see if you can get some work-around or improvement. My gut feeling is
there is not a lot that can be done and all you can really do is ensure
you are making as few connections as possible and performing as much
work over a connection as possible when you do have one.

**Comment by theophilusx** [comment] 2021-09-20 01:39
As this is an ssh2/node issue, I'm closing this question because there is nothing which can be done at the ssh2-sftp-client layer.

**Closed by theophilusx** 2021-09-20 01:39 UTC

**Comment by rpawlaszek** [comment] 2022-09-15 08:56
Hi all. Tinkering around I found that adding this piece of configuration to in `connect` enabled me to resolve this:

```
algorithms: {
            serverHostKey: ['ssh-rsa'],
            cipher: ['aes128-ctr'],
            kex: ['diffie-hellman-group14-sha1']
        }
```

As for now I haven't dug deeper to identify the root cause, but maybe it's helpful for others to move forward.

**Comment by rpawlaszek** [comment] 2022-09-15 09:29
Okay, I had a *hidden* step that enabled that. I installed `ssh2` explicitly as a dependency in my project. Without it I still hit the original issue.

**Comment by rpawlaszek** [comment] 2022-09-15 10:05
So to go through the issue: in the debug information you have the possible client and server key formats, ciphers, and KEX algorithms. If you hit this issue, do go through the available pairs one-by-one, because in my case it was that the library was unable to handle properly the `diffie-hellman-group-exchange-sha256` algorithm, but as it was the first match - it got selected without trying any other combination.

**Comment by theophilusx** [comment] 2022-09-15 13:23
This is a known problem which some users will run into due to variations
in server configuraitons/types. Strictly speaking, it is an ssh2 thing
and you will find more information and examples in the ssh2 repository
documentation and issues.

What I tend to do when I encounter an issue like this is to use openSSH
CLI with the -vvv switch (increase debugging output) and connect to the
target sftp server. This will show you which ciphers and algorithms are
being used so you can configure them in the connect options object.

Feel free to submit a PR to extend the README documentation if you feel
that would help (probably best in the trouble shooting section).

**Comment by rpawlaszek** [comment] 2022-09-15 19:01
Thanks @theophilusx for the response. I rather saw this thread *sort of* unfinished and as this is indeed an issue that is not with this great library - it is where it has been showing. So my intention after getting this working - share it as a workaround that can help users move forward and not being stuck with this. And this GH issue is the first thing that showed up in my search results when trying to find something about the issue, so even though not directly related - it is in my opinion good to have it here.

> What I tend to do when I encounter an issue like this is to use openSSH
CLI with the -vvv switch

What I did (as @Humphaz here) was to set

```
debug: console.log.bind(console)
```

in the `connect` and then one can read what's going on during the handshake. So there is enough information to take action.

> Feel free to submit a PR to extend the README documentation if you feel
that would help (probably best in the trouble shooting section).

Yes, I think it might be valuable as a workaround for a known, related issue that sometimes hits the users.
