### ISSUE TITLE
Issue when uploading (put) a file with zero bytes

### ISSUE THREAD

**Issue by ugobey** [theophilusx/ssh2-sftp-client#204] opened 2020-01-14 09:24 UTC
I had to use this great module to upload files to Adobe's FTP servers and they expect that for every CSV file uploaded that it has another file of the same name but with a .fin extension and zero bytes in size. This is so they know when the CSV file is completed uploading so they can start processing it.

I noticed that when running a synchronous loop to upload files for each customer that if we add sftp.end() to the loop then the .fin file did not get uploaded as it didnt appear to wait until it completed the upload. I proved this by simply adding one letter to the .fin file and then it worked without issue as the file was not zero bytes anymore. Another way to work around it was to add a setTimeout of 50ms and then it worked fine too.

I guess when you developed this you didnt consider uploading a zero byte file in the promises.

Please add that ability so I can remove my workarounds. I am sure others may have this too.

![image](https://user-images.githubusercontent.com/54430605/72331204-7737fc80-36c0-11ea-8e79-456abf35f1e4.png)

**Comment by theophilusx** [comment] 2020-01-14 13:28
I cannot reproduce this issue. I used the following script

```
'use strict';

// Issue #204 reported that you cannot upload (put) files with
// a zero length. This script tries to replicate this issue

const path = require('path');
const SftpClient = require('../src/index');

const dotenvPath = path.join(__dirname, '..', '.env');
require('dotenv').config({path: dotenvPath});

const config = {
  host: process.env.SFTP_SERVER,
  username: process.env.SFTP_USER,
  password: process.env.SFTP_PASSWORD,
  port: process.env.SFTP_PORT || 22
};

async function putFiles(client, src, dst) {
  try {
    for (let f of ['file1', 'file2']) {
      await client.put(
        path.join(src, `${f}.txt`),
        `${dst}${client.remotePathSep}${f}.txt`
      );
      await client.put(
        path.join(src, 'empty-file.txt'),
        `${dst}${client.remotePathSep}${f}.fin`
      );
    }
    console.log('Files uploaded');
  } catch (err) {
    console.error(err.message);
  }
}

async function main() {
  const client = new SftpClient();

  try {
    let srcDir = process.argv[2];
    let dstDir = process.argv[3];
    await client.connect(config);
    await putFiles(client, srcDir, dstDir);
  } catch (err) {
    console.error(err.message);
  } finally {
    await client.end();
  }
}

main().then(() => {
  console.log('script complete');
});
```

Using a test directory with the following files 

````
╭─tim@tim-desktop ~/git/ssh2-sftp-client/example  ‹release-5.0.0*› 
╰─➤  ls -l /tmp/test-data 
total 13624
-rw-rw-r-- 1 tim tim       0 Jan 15 00:16 empty-file.txt
-rw-rw-r-- 1 tim tim 6973257 Jan 15 00:16 file1.txt
-rw-rw-r-- 1 tim tim 6973257 Jan 15 00:16 file2.txt
╭─tim@tim-desktop ~/git/ssh2-sftp-client/example  ‹release-5.0.0*› 
╰─➤ 
````

and got the following on the remote SFTP server

````
➜  test-dir ls -l
total 13624
-rw-rw-rw- 1 tim users       0 Jan 15 00:26 file1.fin
-rw-rw-rw- 1 tim users 6973257 Jan 15 00:26 file1.txt
-rw-r--r-- 1 tim users       0 Jan 15 00:26 file2.fin
-rw-rw-rw- 1 tim users 6973257 Jan 15 00:26 file2.txt
➜  test-dir                   
````

Are you sure your script is waiting until the promises are all resolved before it calls end()?

**Comment by theophilusx** [comment] 2020-01-14 13:41
I also verified fastPut() works as well. This was tested using the release-5.0.0 branch of the repository as I will be releasing this version in the next couple of days. If ou are still having problems, try to put together a minimal example and send it through and I'll have a look.

**Comment by theophilusx** [comment] 2020-01-20 21:41
As I could not reproduce this issue and was able to upload files with 0 bytes successfully, I'm closing this issue. It can be reopened if further information is forthcoming.

**Closed by theophilusx** 2020-01-20 21:41 UTC
Labels: more info

**Comment by ugobey** [comment] 2020-01-21 07:51
Hi,



Sorry I was away and got back now.



Is it possible that I can show you in a screenshare?



*From:* Tim Cross <notifications@github.com>
*Sent:* Monday, January 20, 2020 11:42 PM
*To:* theophilusx/ssh2-sftp-client <ssh2-sftp-client@noreply.github.com>
*Cc:* Uri Gobey <uri.gobey@contentsquare.com>; Author <
author@noreply.github.com>
*Subject:* Re: [theophilusx/ssh2-sftp-client] Issue when uploading (put) a
file with zero bytes (#204)



As I could not reproduce this issue and was able to upload files with 0
bytes successfully, I'm closing this issue. It can be reopened if further
information is forthcoming.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/theophilusx/ssh2-sftp-client/issues/204?email_source=notifications&email_token=AM7IXDPVIFHOGVPZPAU6N6DQ6YLCDA5CNFSM4KGPVKOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJN4BUA#issuecomment-576438480>,
or unsubscribe

**Comment by theophilusx** [comment] 2020-01-21 10:39
A screenshare probably won't help much. What would be useful is if you
can send a minimal script which reproduces the issue for you. I can then
test it against my test environments and see if I can reproduce it.

Also need to know what platform your running the script on and the node
version. Also, if you know, what platform the sftp server is running on
and any other details you may know (there are reported issues with some
servers, such as BrikFTP/files.com). 

There is nothing in the module itself which looks at or tests the file
size. There are some tests to ensure the file is accessible (valid path,
can be read etc) and tests to verify the destination path is valid, but
nothing which considers the size of the file. Likewise, there is nothing
which looks at number of bytes transferred. 

This doens't mean that the underlying ssh2 or ssh2streams library
doesn't, but I've had no issues with zero length files.

If we can reproduce the issue, I can then write other tests to determine
if the issue is with ssh2-sftp-client or with the underlying
ssh2/sshstreams modules. If it is with the latter, then we need to log
an issue with the author of those packages.
