### ISSUE TITLE
Corrupt file on the SFTP

### ISSUE THREAD

**Issue by arcovoltaico** [theophilusx/ssh2-sftp-client#45] opened 2018-01-10 17:38 UTC
The 99% of the mp3 files I'm uploading to my SFTP are uploaded ok. But some of them, although they have the same bytes as the originals, the uploaded file won't play normal if downloaded again.
Chrome will skip some parts of the tracks ... I have checked the mscdex/ssh2 and maybe the solution would be to enable the INPCK Terminal mode for checking of parity errors. https://github.com/mscdex/ssh2#terminal-modes  
How can it be done and solved?  (A workaround would be using md5 for instance ) Thanks

**Comment by leontastic** [comment] 2018-01-23 14:41
Have you tried setting the `encoding` parameter on `sftp.get`? I encountered a similar issue with corrupted ZIP files – it turns out `ssh2-sftp-client` uses `utf8` encoding by default for file streams, whereas you probably want `binary`, which you can get by passing `null` into the `encoding` param:

```javascript
sftp.get('path/to/file.mp3', null, null)
```

**Comment by theophilusx** [comment] 2019-08-22 08:06
Has this been resolved? There have been significant changes to the module since this issue was logged (including defaulting to null for encoding rather than utf-8) so I expect the issue is no longer valid. Will close this in a few days if there are no objections.

**Closed** 2019-08-28 01:56 UTC
Labels: more info
