### ISSUE TITLE
Module parse failed: Identifier directly after number

### ISSUE THREAD

**Issue by 89am89** [theophilusx/ssh2-sftp-client#412] opened 2022-05-13 09:14 UTC
Hi,

when I add the line `const Client = require('ssh2-sftp-client')` my React project doesn't compile anymore and I get this error message:

`./node_modules/ssh2/lib/protocol/keyParser.js 169:61`
`Module parse failed: Identifier directly after number (169:61)`
`You may need an appropriate loader to handle this file type.`
`|   return function genOpenSSLRSAPriv(n, e, d, iqmp, p, q) {`
`|     var bn_d = bigIntFromBuffer(d);`
`>     var dmp1 = bigIntToBuffer(bn_d % (bigIntFromBuffer(p) - 1n));`
`|     var dmq1 = bigIntToBuffer(bn_d % (bigIntFromBuffer(q) - 1n));`
`|     return makePEM('RSA PRIVATE', genRSAASN1Buf(n, e, d, p, q, dmp1, dmq1, iqmp));`

**Comment by theophilusx** [comment] 2022-05-13 12:04
This is most likely some configuration error in your build chain. I
would be looking at yhour project definition as something is definitly
messed up with your environment. 

I would try just creating a simple node script and loading
ssh2-sftp-client. Either it will load fine (which tells you it is
something in your project definition which is messed up or it will give
you more information which can b eused to track down the issue. There is
nothing 'special' about ssh2-sftp-client - it is just a standard node
module which loads a class. 

What version of node? 
what version of ssh2-sftp-client?
what platform are you running on?

**Comment by theophilusx** [comment] 2022-05-13 12:56
The first 'error' is actually a warning about an optional dependency. It does not prevent ssh2-sftp-client from working. 

This is an issue being caused by react/react-scripts. I notice you are running old versions of both. The error you are getting also seems similar to errors I've seen with misconfigured typscript configurations. 

Bottom line, this is an error being caused by the way react is setting up the environment. You need to debug this in terms of react and its environment. I would look at separating out your sftp and other node stuff from the react stuff. React is all about browser/mobile javascript while ssh2-sftp-client is all about node and unrelated to the browser. Best to keep browser javascript and node javascript separate. It could easily be that your trying to load ssh2-sftp-client in a javascript file which is supposed to be rendered in the browser and that of course  will not work.

**Comment by theophilusx** [comment] 2022-05-17 08:54
As this issue cannot be reproduced and I suspect it is a client environment configuration error and as a new ssh2-sftp-client version has just been pushed out, I'm closing this issue. If a clear reproducible recipe can be identified which does not involve react, we can re-open later.

**Closed as completed by theophilusx** 2022-05-17 08:54 UTC
Labels: client Error

**Comment by KEMBL** [comment] 2022-08-12 16:24
I had the same problem with `cpu-features` and the error message was the same when I used `yarn` while `npm install` worked without errors.
node: 16.15.0
"ssh2": "^1.11.0"

**Comment by theophilusx** [comment] 2022-08-13 00:30
If you are getting the exact same error message as the OP, then it is almost certainly a local configuration issue relating to react. As stated above, the error relating to cpu-features is most often a warning and not an error and won't impact functionality (it is an optional dependency that is not needed). The other errors reported by the OP seem to have been from something react does which impacts on ssh2. To get this resolved, you will need to create an ssh2 only script which reproduces the error and then report it, together with the script, to the ssh2 project. There is nothing I can do from the ssh2-sftp-client level. 

It should be noted that the ssh2 module sees a lot of downloads every week. The ssh2-sftp-client sees a lot less, but even it gets around 250,000 downloads per week. This is only the second report of this issue which I have not been able to reproduce. Therefore, very likely this is an issue being caused by something very local to your environment.  This means you will need to track down the local cause in order to have any chance of the issue being resolved as it has to be reproducible first.
