### ISSUE TITLE
try catch doesn't prevent uncaught exception

### ISSUE THREAD

**Issue by rafipiccolo** [theophilusx/ssh2-sftp-client#334] opened 2021-07-17 21:11 UTC
i have a script which is working on many hosts.
But I have this host (B) which is refusing connections from host A and this package is dealing with errors in a strange way.

When i use this package to connect from A to B i get an uncaught exception : Connection lost before handshake
shouldn't the "try catch" get the error onstead of killing the app ?
i even tried to do a sftp.on('error") to double catch it, but same story.

```
let Client = require('ssh2-sftp-client');
(async () => {
    try {
        let sftp = new Client();

        // when i add this line, i get this other error before the other and the process is still killed.
        sftp.on('error', (err) => { console.log('strange', err); });
        //
        // strange Error: read ECONNRESET
        //     at TCP.onStreamRead (node:internal/stream_base_commons:211:20) {
        //   errno: -104,
        //   code: 'ECONNRESET',
        //   syscall: 'read',
        //   level: 'client-socket'
        // }

        await sftp.connect({
            host: '',
            port: '',
            username: '',
            password: '',
        });

        let result = await sftp.list(`/`);

        await sftp.end();
    } catch (err) {
        console.log('catch', err)
    }
})()
```

and here is the error

```
/root/docker/test/node_modules/ssh2-sftp-client/src/index.js:56
        throw fmtError(
        ^

Error: sftp: global error handler: Unexpected error: Connection lost before handshake
    at fmtError (/root/docker/test/node_modules/ssh2-sftp-client/src/utils.js:53:18)
    at Client.<anonymous> (/root/docker/test/node_modules/ssh2-sftp-client/src/index.js:56:15)
    at Client.emit (node:events:406:35)
    at /root/docker/test/node_modules/ssh2/lib/client.js:674:16
    at Socket.<anonymous> (/root/docker/test/node_modules/ssh2/lib/client.js:734:7)
    at Socket.emit (node:events:394:28)
    at TCP.<anonymous> (node:net:672:12) {
  code: 'ERR_GENERIC_CLIENT',
  custom: true
}
```

**Comment by theophilusx** [comment] 2021-07-18 00:33
What version of ssh2-sftp-client and node?

There are a couple of things going on here. It is a little
complicated, but I will try to explain.

Firstly, the error you are getting is because your remote SFTP server is
closing the connection unexpectedly in-between calls to the ssh2 API.

The reason it seems 'weird' and is not being caught in a try/catch is
because the error is from an event. You cannot reliably catch event
based errors with a try/catch block because they are thrown outside the
normal execution context of the try/catch. This means the error event
can fire before or after the try/catch block has executed. Essentially,
there is no block to catch it.

The situation is being made more complex because the module is
attempting to provide a Promise based API around a library which is
event based. Again, this is related to execution contexts. When the
promise is created, it defines a block of code which calls the ssh2 API
to perform some action. At the start of the promise block, some event
listeners are added to catch any events fired while the promise block is
executing. The promise block also checks for any errors returned from
the API call. If either an event fires or an error is thrown, the
'reject' function is called and the promise is fulfilled with a reject
state. If no event fires and no errors are returned, the resolve
function is called and the promise is fulfilled with a resolved status.
When the promise is fulfilled, the event listeners are removed (they
have to be removed to prevent a memory leak and because they reference
the 'reject' method of the enclosing promise block, which will no longer
exist after the promise has been fulfilled.

The problem is, an event might fire outside any promise block. When this
occurs, there are no event handlers defined and you will get an uncaught
exception. To try and deal with this case, a 'global' generic error
handler is defined, which currently throws an exception if no other
error handler has dealt with the error already. This is what is handling
the error in your case.

I'm not 100% sure why the error being thrown by the global error handler
is not being caught in your try/catch, but I suspect it is because you
have defined that as an anonymous async block (which means it is running
in a different execution context) while the global event handler is
throwing the error in the main execution context (this is assuming you
are running version 7.0.0 of the library).

Try modifying your custom event handler to be

sftp.on('error', (err) => {
  sftp.errorHandled = true;
  console.log('custom error handler', err);
};

Note that this handler needs to be setup early (as you have it now) to
ensure it runs before the global handler. Setting 'errorHandled' to true
will tell the global error handler that you have handled the error and
it does not need to throw it again. This should prevent your script from
terminating due to an unhandled error. Of course, in production, you
will need to do something with the error (which could be just reporting
it and exiting or something else).

The critical thing here is that your custom error handler must run
before the global one. I might have to consider changing the 'on' method
to use prepend to ensure any custom error handlers are added to the beginning of
the handler array. 

The other thing you could try doing is define your code as a 'main'
function rather than as an anonymous async function and then call that
inside a try/catch block. This *might* make it easier to catch the
thrown error as the outer try/catch will still be running when the event fires.

**Comment by rafipiccolo** [comment] 2021-07-18 00:55
thanks for you detailed answer.
node v16.4.2
ssh2-sftp-client v7.0.0

using your sftp.on + declaring a main function and running it helped :)
But i still occasionally see Error: read ECONNRESET
followed by
Error: Connection lost before handshake
followed by the data


```
let Client = require('ssh2-sftp-client');

async function main() {
    try {
        let sftp = new Client();

        sftp.on('error', (err) => {
            sftp.errorHandled = true;
            console.log('custom error handler', err);
        });

        await sftp.connect({
            host: 'xx',
            port: 'xx',
            username: 'xxxx',
            password: 'xxx',
        });

        let result = await sftp.list(`/`);

        console.log(result);

        await sftp.end();
    } catch (err) {
        console.log('catch', err)
    }
}

main();

process.on('uncaughtException', (err) => {
    console.log('uncaught', err);
    process.exit(0);
})

```

returns

```
custom error handler Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:211:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
custom error handler Error: Connection lost before handshake
    at makeError (/root/docker/test/node_modules/ssh2/lib/protocol/utils.js:142:15)
    at /root/docker/test/node_modules/ssh2/lib/client.js:673:13
    at Socket.<anonymous> (/root/docker/test/node_modules/ssh2/lib/client.js:734:7)
    at Socket.emit (node:events:394:28)
    at TCP.<anonymous> (node:net:672:12) {
  level: 'protocol',
  fatal: true
}
[
  {
    type: 'd',
    name: 'xxxx',
    size: 45056,
    modifyTime: 1626562819000,
    accessTime: 1626567906000,
    rights: { user: 'rwx', group: 'rx', other: 'rx' },
    owner: 400,
    group: 400
  }
]
```

**Comment by theophilusx** [comment] 2021-07-18 02:16
It looks to me like 2 errors are being fired, but both are being caught
by your custom error handler. I don't see any unhandled exception in the
sample output you have provided. 

your remote SFTP server is resetting the connection unexpectedly,
This is occurring outside calls to the API. In your case, it looks like
it might be happening after the call to list() and before the call to
end() or possibly after the call to end(). So you need to find out why
the remote sftp server is unexpectedly closing the connection. This
could also be a bug in the remote sftp server - I recall issues with
sftp under Azure where the sftp server would throw an error after a
legitimate end() call.

I would try using openSSH's sftp CLI to connect to the same server and
see if you also get remote connection reset errors. I would use the -v
(verbose) flag to get more debugging info to see what is going on. 

Looking at the output, it looks like the remote server is generating 2
errors - a connect reset error and a connection lost before handshake
error. Both appear to be getting caught by your custom event handler, so
there should not be any uncaught exception - there doesn't appear to be
one in the sample output you provided.

There was a bug in ssh2 where an error caused 2 errors to be reported
(this was with respect to connect()) - it is possible the same thing is
happening here (does not explain why you are getting an error, but might
explain why there is 2). If this is the case, it may be necessary to
reproduce the issue using just ssh2 and logging an issue against that
module. There are example ssh2 scripts in the 'validations' directory of
the ssh2-sftp-client repository which show how you could use just ssh2.

You might also try adding a debug function - this will generate quite a lot
of output, but might help clarify the sequence of events and help track
down the problem. A simple debug function could be just


>         await sftp.connect({
>             host: 'xx',
>             port: 'xx',
>             username: 'xxxx',
>             password: 'xxx',
>             debug: (msg) => console.log(msg)
>         });

although I tend to do something a little fancier to filter out messages
I'm not interested in. Start with something simple like the above and
then refine as needed.

Note also that you appear to be using docker - this problem could be
related to docker networking issues as well (not the remote sftp
server).

It looks to me like there are two problems here. One is the network/sftp
connection error. This is something you will need to track down in your
environment. It isn't being caused by ssh2-sftp-client (or ssh2). The
second problem is cleanly handling that error. Your custom error handler
seems to be doing that. However, if you are still getting uncaught error
exceptions, it means the error is being raised when your custom error
handler is not in place. You could try something like


> let Client = require('ssh2-sftp-client');
>
> const sftp = new Client();
>
> sftp.on('error', (err) => {
>   sftp.errorHandled = true;
>   console.log('custom error handler', err);
> });
>
> process.on('uncaughtException', (err) => {
>     console.log('uncaught', err);
>     process.exit(0);
> })
>
> async function main() {
>     try {
>         await sftp.connect({
>             host: 'xx',
>             port: 'xx',
>             username: 'xxxx',
>             password: 'xxx',
>         });
>
>         let result = await sftp.list(`/`);
>
>         console.log(result);
>
>         await sftp.end();
>     } catch (err) {
>         console.log('catch', err)
>     }
> }

> main().then(() => console.log('Script complete');
>

which shold ensure your custom error handler and sftp object are in
scope for the whole of the script lifetime. The then() call will ensure
the script does not exit until the main() function has completed.

**Comment by rafipiccolo** [comment] 2021-07-25 21:24
Hello,

i've had a response from the customer service. The server is indeed blacklisting me for 4H after X successive calls... so the connection lost error is normal. They are being very restrictive, (as if if they were not paid on a count basis :p)

I was just curious about the proper way to not crash my app, and thanks to your advices it now works even when im blacklisted.
ps: This code was succesfully preventing cashes : https://github.com/theophilusx/ssh2-sftp-client/issues/334#issuecomment-881980227
i also added a rate limiter to be sure not to trigger the errors at all.

i hope your solution will stay valid in next versions of this package :)
Should it be added to the readme that someone can handle bad server behaviors like this :
could save a lot of time :)

```
        sftp.on('error', (err) => {
            sftp.errorHandled = true;
            console.log('custom error handler', err);
        });
```

**Closed** 2021-07-27 01:11 UTC
