### ISSUE TITLE
upgrade from 6.0.1 to 7.2.1 brings up "fastPut: Handling error: Malformed STATUS packet"

### ISSUE THREAD

**Issue by sbulheller** [theophilusx/ssh2-sftp-client#373] opened 2021-12-23 17:22 UTC
when using 7.2.1 the fastPut doesn't work for me anymore. fastPut brings up an "Handling error: Malformed STATUS packet:"

> CLIENT[sftp]: connect: Debugging turned on
> CLIENT[sftp]: connect: Connect attempt 1
> CLIENT[sftp]: getConnection: Adding temp event listeners
> CLIENT[sftp]: getConnection: created promise
> CLIENT[sftp]: Adding listener to ready event
> Custom crypto binding available
> Local ident: 'SSH-2.0-ssh2js1.5.0'
> Client: Trying netfiles.de on port 3333 ...
> Socket connected
> Remote ident: 'SSH-2.0-OpenSSH_8.2p1'
> Outbound: Sending KEXINIT
> Inbound: Handshake in progress
> Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
> Handshake: (remote) KEX method: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
> Handshake: KEX algorithm: curve25519-sha256@libssh.org
> Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
> Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ssh-rsa
> Handshake: Host key format: rsa-sha2-512
> Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,chacha20-poly1305@openssh.com,aes256-ctr
> Handshake: (remote) C->S cipher: aes256-ctr,aes256-gcm@openssh.com
> Handshake: C->S Cipher: aes256-gcm@openssh.com
> Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,chacha20-poly1305@openssh.com,aes256-ctr
> Handshake: (remote) S->C cipher: aes256-ctr,aes256-gcm@openssh.com
> Handshake: S->C cipher: aes256-gcm@openssh.com
> Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
> Handshake: (remote) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
> Handshake: C->S MAC: <implicit>
> Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
> Handshake: (remote) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
> Handshake: S->C MAC: <implicit>
> Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
> Handshake: (remote) C->S compression: none,zlib@openssh.com
> Handshake: C->S compression: none
> Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
> Handshake: (remote) S->C compression: none,zlib@openssh.com
> Handshake: S->C compression: none
> Outbound: Sending KEXECDH_INIT
> Received DH Reply
> Host accepted by default (no verification)
> Host accepted (verified)
> Outbound: Sending NEWKEYS
> Inbound: NEWKEYS
> Verifying signature ...
> Verified signature
> Handshake completed
> Outbound: Sending SERVICE_REQUEST (ssh-userauth)
> Inbound: Received SERVICE_ACCEPT (ssh-userauth)
> Outbound: Sending USERAUTH_REQUEST (none)
> Inbound: Received USERAUTH_FAILURE (publickey,password)
> Client: none auth failed
> Outbound: Sending USERAUTH_REQUEST (password)
> Inbound: Received USERAUTH_SUCCESS
> CLIENT[sftp]: getConnection: got connection - promise resolved
> CLIENT[sftp]: getConnection: finally clause fired
> Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
> Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
> Inbound: REQUEST_SUCCESS
> CLIENT[sftp]: Removing listener from ready event
> CLIENT[sftp]: getConnection: Removing temp event listeners
> CLIENT[sftp]: getSftpChannel: Adding temp event listeners
> CLIENT[sftp]: getSftpChannel: created promise
> Outbound: Sending CHANNEL_OPEN (r:0, session)
> Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
> Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
> Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
> Inbound: CHANNEL_SUCCESS (r:0)
> Outbound: Sending CHANNEL_DATA (r:0, 9)
> Inbound: CHANNEL_DATA (r:0, 42)
> SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com)
> CLIENT[sftp]: getSftpChannel: SFTP channel established
> CLIENT[sftp]: getSftpChannel: finally clause fired
> CLIENT[sftp]: getSftpChannel: Removing temp event listeners
> CLIENT[sftp]: fastPut -> local ./test.txt remote /xxx/projectfiles/test.txt
> CLIENT[sftp]: fastPut -> local: ./test.txt remote: /xxx/projectfiles/test.txt opts: undefined
> CLIENT[sftp]: fastPut: Adding temp event listeners
> Outbound: Sending CHANNEL_DATA (r:0, 58)
> SFTP: Outbound: Buffered OPEN
> Inbound: CHANNEL_DATA (r:0, 17)
> SFTP: Inbound: Received HANDLE (id:0)
> Outbound: Sending CHANNEL_DATA (r:0, 51)
> SFTP: Outbound: Sent WRITE (id:1)
> Inbound: CHANNEL_DATA (r:0, 13)
> SFTP: Inbound: Malformed STATUS packet
> CLIENT[sftp]: fastPut: Handling error: Malformed STATUS packet
> CLIENT[sftp]: fastPut: handled error with reject
> CLIENT[sftp]: Global: Ignoring handled error
> CLIENT[sftp]: fastPut: Removing temp event listeners
> fastPut: Malformed STATUS packet
> CLIENT[sftp]: end: Adding temp event listeners
> CLIENT[sftp]: Adding listener to close event
> CLIENT[sftp]: end: Have connection - calling end()
> Socket ended
> CLIENT[sftp]: end: Ignoring expected end event
> CLIENT[sftp]: Global: Ignoring hanlded end event
> Socket closed
> CLIENT[sftp]: end: Connection closed
> CLIENT[sftp]: end: ignoring expected close event
> CLIENT[sftp]: Global: Ignoring handled close event
> CLIENT[sftp]: end: finally clause fired
> CLIENT[sftp]: end: Removing temp event listeners
> CLIENT[sftp]: Removing listener from close event

with 6.0.1 and the same code the upload works:
> CLIENT[sftp]: Removing listener from ready
> CLIENT[sftp]: fastPut -> local ./test.txt remote /xxx/projectfiles/test.txt
> CLIENT[sftp]: fastPut <- localStatus -
> CLIENT[sftp]: fastPut source access ok
> CLIENT[sftp]: fastPut -> local: ./test.txt remote: /xxx/projectfiles/test.txt opts: undefined
> DEBUG[SFTP]: Outgoing: Writing OPEN
> DEBUG: Outgoing: Writing CHANNEL_DATA (0)
> DEBUG: Parser: IN_PACKET
> DEBUG: Parser: Decrypting
> DEBUG: Parser: pktLen:44,padLen:17,remainLen:32
> DEBUG: Parser: IN_PACKETDATA
> DEBUG: Parser: Decrypting
> DEBUG: Parser: HMAC size:32
> DEBUG: Parser: IN_PACKETDATAVERIFY
> DEBUG: Parser: Verifying MAC
> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
> DEBUG[SFTP]: Parser: Response: HANDLE
> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
> DEBUG[SFTP]: Outgoing: Writing WRITE
> DEBUG: Outgoing: Writing CHANNEL_DATA (0)
> DEBUG: Parser: IN_PACKET
> DEBUG: Parser: Decrypting
> DEBUG: Parser: pktLen:28,padLen:5,remainLen:16
> DEBUG: Parser: IN_PACKETDATA
> DEBUG: Parser: Decrypting
> DEBUG: Parser: HMAC size:32
> DEBUG: Parser: IN_PACKETDATAVERIFY
> DEBUG: Parser: Verifying MAC
> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
> DEBUG[SFTP]: Parser: Response: STATUS
> DEBUG[SFTP]: Outgoing: Writing CLOSE
> DEBUG: Outgoing: Writing CHANNEL_DATA (0)
> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
> DEBUG: Parser: IN_PACKET
> DEBUG: Parser: Decrypting
> DEBUG: Parser: pktLen:28,padLen:5,remainLen:16
> DEBUG: Parser: IN_PACKETDATA
> DEBUG: Parser: Decrypting
> DEBUG: Parser: HMAC size:32
> DEBUG: Parser: IN_PACKETDATAVERIFY
> DEBUG: Parser: Verifying MAC
> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
> DEBUG[SFTP]: Parser: Response: STATUS
> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
> CLIENT[sftp]: fastPut file transferred
> transfer done: ./test.txt -> /xxx/projectfiles/test.txt
> CLIENT[sftp]: Adding listener to close
> CLIENT[sftp]: Have connection - calling end()
> DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
> CLIENT[sftp]: Handled end event for end
> CLIENT[sftp]: handled close event for end
> DEBUG: Outgoing: Writing CHANNEL_CLOSE (0)
> CLIENT[sftp]: Removing listener from close

this is the code i am using:
```
async function transferFile ({file, sftpConfig}) {
  let sftpClient = new SshSftpClient()
  const filename = path.basename(file)
  try {
    await sftpClient.connect(sftpConfig)
    let dir = sftpConfig.folder ?? '/upload/'
    const target = path.normalize(dir + '/' + filename)
    await sftpClient.fastPut(file, target)
    console.log(`transfer done: ${file} -> ${target}`)
  } catch (e) {
    console.error(e.message)
  } finally {
    await sftpClient.end()
  }
}

transferFile({file, sftpConfig})
```

does anyone have a suggestion what this could be?

**Comment by theophilusx** [comment] 2021-12-23 23:06
This looks very much like an ssh2 error and will therefore need to be
reported upstream at the ssh2 project. However, to get traction there,
we will need to demonstrate it is an ssh2 issue and not something
introduced by ssh2-sftp-client. It is unlikely to be something
ssh2-sftp-client introduces as it is essentially a promise based API
wrapper around ssh2 with a little convenience sugar sprinkled on top.

In the validate directory of the ssh2-sftp-client repository are scripts
which perform simple operations using only ssh2, no ssh2-sftp-client.
Can you adapt one of these scripts and use it to reproduce the issue
using same node version, platform and target sftp server? If you can,
then please log an issue with the ssh2 project, including the log file
and relevant node version etc. Would be worth noting that it works with
the previous version of ssh2 (0.8.9?) as ssh2 was completely re-written
between 0.8.9 and 1.0.0 (ssh2-sftp-client v6.x is based on old ssh2 and
v7.x the new version).

If you cannot reproduce the issue just using the ssh2 only scripts,
please let me know as this would indicate an issue with
ssh2-sftp-client and I will need to debug further.

BTW one of the reasons for the ssh2 re-write was due to incompatibility
in ssh2 0.8.9 and node versions > v14.3. That incompatibility was rulled
back in v15.x of node because it caused issues for a number of network
based libraries. However, that incompatibility also produced significant
network performance improvements, so I suspect it will be re-introduced
at some future date. This means for future proofing, it is important to
sort out this issue with ssh2 1.5.0. You may also be able to work around
your problem using put rather than fastPut. While fastPut can be faster,
the underlying mechanism it uses is not supported by all sftp servers.
As the put mechanism is more standard, it will sometimes work when
fastPut does not.

**Comment by sbulheller** [comment] 2022-01-02 11:32
@theophilusx : thank you for your really fast response.

i had tried it before with put instead of fastput, but the error is the same. Now I tried to reproduce the error with the script validation/put.js and the error is the same:

> Custom crypto binding not available
> Local ident: 'SSH-2.0-ssh2js1.5.0'
> Client: Trying netfiles.de on port 3333 ...
> Socket connected
> Remote ident: 'SSH-2.0-OpenSSH_8.2p1'
> Outbound: Sending KEXINIT
> Inbound: Handshake in progress
> Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
> Handshake: (remote) KEX method: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
> Handshake: KEX algorithm: curve25519-sha256@libssh.org
> Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
> Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ssh-rsa
> Handshake: Host key format: rsa-sha2-512
> Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
> Handshake: (remote) C->S cipher: aes256-ctr,aes256-gcm@openssh.com
> Handshake: C->S Cipher: aes256-gcm@openssh.com
> Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
> Handshake: (remote) S->C cipher: aes256-ctr,aes256-gcm@openssh.com
> Handshake: S->C cipher: aes256-gcm@openssh.com
> Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
> Handshake: (remote) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
> Handshake: C->S MAC: <implicit>
> Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
> Handshake: (remote) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
> Handshake: S->C MAC: <implicit>
> Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
> Handshake: (remote) C->S compression: none,zlib@openssh.com
> Handshake: C->S compression: none
> Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
> Handshake: (remote) S->C compression: none,zlib@openssh.com
> Handshake: S->C compression: none
> Outbound: Sending KEXECDH_INIT
> Received DH Reply
> Host accepted by default (no verification)
> Host accepted (verified)
> Outbound: Sending NEWKEYS
> Inbound: NEWKEYS
> Verifying signature ...
> Verified signature
> Handshake completed
> Outbound: Sending SERVICE_REQUEST (ssh-userauth)
> Inbound: Received SERVICE_ACCEPT (ssh-userauth)
> Outbound: Sending USERAUTH_REQUEST (none)
> Inbound: Received USERAUTH_FAILURE (publickey,password)
> Client: none auth failed
> Outbound: Sending USERAUTH_REQUEST (password)
> Inbound: Received USERAUTH_SUCCESS
> Outbound: Sending CHANNEL_OPEN (r:0, session)
> Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
> Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
> Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
> Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
> Inbound: REQUEST_SUCCESS
> Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
> Inbound: CHANNEL_SUCCESS (r:0)
> Outbound: Sending CHANNEL_DATA (r:0, 9)
> Inbound: CHANNEL_DATA (r:0, 42)
> SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com)
> Sending ./test.txt to /xxx/projectfiles/test.txt
> Outbound: Sending CHANNEL_DATA (r:0, 62)
> SFTP: Outbound: Buffered OPEN
> Inbound: CHANNEL_DATA (r:0, 17)
> SFTP: Inbound: Received HANDLE (id:0)
> Outbound: Sending CHANNEL_DATA (r:0, 25)
> SFTP: Outbound: Buffered FSETSTAT
> Inbound: CHANNEL_DATA (r:0, 13)
> SFTP: Inbound: Malformed STATUS packet
> Malformed STATUS packet
> Socket ended
> Socket closed

i will try to file a bug in the ssh2 project.

**Comment by sbulheller** [comment] 2022-01-03 08:20
the issue was resolved in https://github.com/mscdex/ssh2/commit/bf454519e090034386bc20ac128daa6093c49782

**Comment by theophilusx** [comment] 2022-01-03 08:42
Thanks for letting me know. As soon as a new version of ssh2 is
released, I'll push out an updated ssh2-sftp-client. Glad your issue is
fixed.

**Comment by sbulheller** [comment] 2022-01-03 08:58
@theophilusx : thank you very much for the support!

**Comment by theophilusx** [comment] 2022-01-31 07:17
Just about to push out 7.2.2, which is based on ssh2 1.6.0, which I believe has addressed your issue, so closing this.

**Closed by theophilusx** 2022-01-31 07:17 UTC

**Comment by sbulheller** [comment] 2022-01-31 09:47
@theophilusx : seems to work now. Thank you for your efforts!
