### ISSUE TITLE
Does Not Recognise Filepath in Google Cloud Functions

### ISSUE THREAD

**Issue by axwaxw** [theophilusx/ssh2-sftp-client#304] opened 2021-03-06 20:16 UTC
I am using this module in a google cloud function (using firebase functions).

In constructing the local filepath I am using the following:

`const local_file = path.resolve(__dirname, '../tmp/${directory_name}/${file_name}')`

alternatively:

`const local_file = path.resolve(__dirname, '..', os.tmpdir(), '/${directory_name}/${file_name}`)`

alternatively:

`const local_file = path.join(__dirname, '..', os.tmpdir(), directory_name, file_name`

In google cloud functions, this resolves to `/workspace/tmp/directory_name/file_name`

In any event, it does not seem to matter how I construct the filepath to the local file, I get an ENOTDIR error like:

`Error: uploadDir: ENOTDIR: not a directory, scandir '/workspace/tmp/directory_name/file_name.txt'`

or

`Error: fastPut: Directory does not exist. Local: /workspace/tmp/directory_name/file_name.txt`

This is true using `fastPut(local_file, remote_file)` or `uploadDir(local_dir, remote_dir) `

I do not think that this is because the local file does not exist, because I **can** read from the same file using `fs`.  Rather, it seems that ssh2-sftp-client does not recognise the filepath.

Any guidance appreciated.

**Comment by theophilusx** [comment] 2021-03-06 21:49
What version of

ssh2-sftp-client

node

thanks

**Comment by axwaxw** [comment] 2021-03-06 22:07
"node": "12"
"ssh2-sftp-client": "^6.0.1"

**Comment by theophilusx** [comment] 2021-03-06 22:46
My guess is that this is something specific to how the google
environment works. At any rate, the first thing to do is see if you get
the same error just using the underlying ssh2 module which
ssh2-sftp-client depends on.

In the repo, there is a directory called 'validation', which has a few
very simple scripts that just use ssh2 to perform basic operations, like
put() or fastput().

Try adapting one of these scripts and see if you get the same error. If
you do, it will need to be reported upstream with the ssh2 maintainer.

My wild guess is that Google does not provide a file system that is
fully POSIX compliant and does not support some of the functions ssh2
uses. I've never used firebase or the google platform, so really can't
provide a lot of help. I would suggest going through the google docs,
especially anything about the javascript environment they provide as my
suspicion is that your not really running on a 'normal' file system, but
instead some form of virtualised file system they use to make their
environment run efficiently.

Note also that the put() and get() functions allow you to pass in a
stream or buffer. You might have more success using a stream or buffer
rather than a file name. Note that fastput() and fastget() only support
file names.

**Comment by axwaxw** [comment] 2021-03-07 06:25
Thanks Tim,
according to the [docs](https://cloud.google.com/functions/docs/concepts/exec#file_system), its possible to read and write to the temp directory:

> The only writeable part of the filesystem is the /tmp directory, which you can use to store temporary files in a function instance. This is a local disk mount point known as a "tmpfs" volume in which data written to the volume is stored in memory. Note that it will consume memory resources provisioned for the function.
> 
> The rest of the file system is read-only and accessible to the function.

However, I think that the problem is that the module can't interpret the filepath.  I have been unable to read from either the /tmp directory, or any other directory accessible to the function.

I'll experiment with the ssh2 module, as you suggest.

The normal put() function definitely works with a buffer / stream, so that is my fallback position.

Thanks again

**Comment by theophilusx** [comment] 2021-03-07 06:52
OK, I suspect you will see the same error from ssh2 and it will be
related to how the Google platform is presenting the file system.

Make sure when you try the ssh2 module you use the current 0.8.x version
and not the current ssh2 master version from the repository. The ssh2
maintainer is doing a complete re-write of the ssh2 module to address
some design limitations and some issues introduced by node 14.x (and
rolled back in node 15.3.x). That version is not ready for production
use - last time I tested it there were a number of problems.

the stream approach works pretty well in my experience. I use it for a
site where all the files need to be gzipped, so I pipe the file stream
through zlib, which zipps/unzipps the file 'on the fly' with put/get.

fastput/fastget is convenient when you just want upload/download of
files and because it is able to transfer them in parallel chunks, it can
be much faster for larger files. However, it does depend on the sftp
server supporting that capability and not all servers do (and I would be
suspicious of the Google environment). Many of the 'cloud' environments
do have some limitations, especially when it comes to storage, due to
efforts to keep performance up, but running costs down. I seem to recall
someone having some issues with AWS and Azure throws additional error
events when closing connections that are 'spurious'. so no surprise if
Google has some of it's own idiosyncrasies.

If you are able to reproduce the same error just using ssh2 (which I
suspect you will), you could log an issue with the ssh2 maintainer. If
you can provide a minimal reproducible example, he might look at it and
might provide a fix (though I suspect due to the re-write work being
done, he won't backport any fixes to the 0.8.x version). It might even
be worthwhile checking the issues in ssh2 as someone else may have run
into the same issue. Might provide some background or a work-around.
There is quite a lot of useful info in the ssh2 issue logs.

**Comment by theophilusx** [comment] 2021-03-30 05:24
Have you been able to make any progress on this?

Should I keep this issue open or close it?

**Closed** 2021-04-05 23:42 UTC
