### ISSUE TITLE
Probe fails while upload of larger file using connect in K8 [PP/PROD]

### ISSUE THREAD

**Issue by prabhatmishra33** [theophilusx/ssh2-sftp-client#444] opened 2022-10-05 14:32 UTC
Dear Team,

Past 1 week, we are trying to debug an issue related to container restart after calling of upload. method of the package.  Whenever a large file calls the upload method after ~20sec the probe starts failing as in the container freezes and doesn't responds to the probes, this leads to container restart by K8. While small files do not get into these issues. while running of the services. we have also checked the cpu memory usage, but the usage remains within the requested limits.

Please find below the code, how we use  the package.

        export const uploadFileToFtpServer = async (logger: LogWrapper, filePath: string, fileData: Buffer) => {
          try {
            let sftp = new Client();

            await sftp.connect({
              host: <host>,
              port: <port>,
              user: <ftp-user>,
              password: <ftp-pwd>,
              algorithms,
              debug: (log: any) => {
                logger.info(log);
                },
            });
            await sftp.put(fileData, filePath);
            sftp.end();
          } catch (err) {
            util.handleAppError(err, {}, 'uploadFileToServer');
            }
        };

I also tried to replicate the issue in my local system but everything works fine in the local.

Please find below the resources that we use.

ssh2-sftp-client : "version": "8.1.0"
Container Image: node:16.13.2-alpine
container cpu and memory : 3Gi and 2Gi

Please let us know,  if any other info is needed. As this is the production issue we request an immediate help from maintainers.

Thanks for building this package.

**Comment by theophilusx** [comment] 2022-10-05 19:54
This sounds similar to issues I have heard about with other container
architectures using for example docker. In each case, the problem was
due to the networking configuration of the container and nothing to do
with ssh2 or ssh2-sftp-client. Often, it was due to bad MTU settings.

I notice you are using an old version of ssh2-sftp-client. That version
is using a version of ssh2 which has some known problems (but none
relating to what you are seeing). The first thing I would do is upgrade
to ssh2-sftp-client 9.0.4. I would also add an await for the call to sftp.end()

The next thing I would do is focus on the network interface of your
container. Pretty sure that is where you will find the issue and not in
ssh2-sftp-client. I suspect it isn't that your container isn't being
responsive, but rather it isn't getting any network traffic.

**Comment by prabhatmishra33** [comment] 2022-10-06 13:35
Hello @theophilusx 
I have integrated your suggestions into our codebase but there is no improvement in the behaviour, again the container restarts on export of a large file. May i know, what do you mean by  "bad MTU settings".

**Comment by prabhatmishra33** [comment] 2022-10-06 15:28
Investigated with the DevOpsteam, we have found that the containers are getting terminated due to `Exit Code:    137`. No sure how it is even possible as the APM provides usage around some Mbs and we have requested the resources in Gbs. Do you recommend to look into something else @theophilusx ?

**Comment by theophilusx** [comment] 2022-10-06 21:56
MTU is part of the network stack on all systems which implement
TCP/IP. It stands for maximum transmission unit.

There has been many times when (Windows based systems in particular)
will have various network failures because the MTU is too large for
their network stack. The default is usually 1500.

This is almost certainly a docker issue. I don't use containers and
therefore am unable to help further. However, I would focus attention at
the docker level and not at the node/ssh2-sftp-client level. 

I would try setting the MTU on the system hosting the container to 1450
or 1400 and see if that helps.

**Comment by theophilusx** [comment] 2022-10-06 22:18
The only other thing to look at is the node image itself. I seem to
recall some mention of docker node images not being 100% compliant due
to being linked with different libraries than the standard node
binary. I cannot recall the precise details. Perhaps search to see if
other users of that specific docker image have reported
unusual/unexpected container exits when using the nodejs image.

I can tell you that I use ssh2-sftp-client to transfer large (20+Gb)
files regularly with no issues. There have been no reports of problems
with large files with current versions of ssh2-sftp-client or the
underlying ssh2 library (there were issues back with ssh2 0.8.9 and node
v14, but the symptoms were different - the connection would just hang
indefinitely. This was due to a combination of both ssh2 and changes in
node 14. Since then ssh2 has had a complete re-write and nodejs rolled
back those changes).

**Comment by prabhatmishra33** [comment] 2022-10-07 08:49
@theophilusx we tried turning off the live and readiness probes for container for a file upload and this just worked fine.

**Comment by theophilusx** [comment] 2022-10-10 03:37
One of my replies doesn't seem  to have made it into this thread, so adding it for completeness. 

I think you should change your code to use streams instead of a buffer to pass the data in. The buffer will be as large as your data, so if you have a lot of data (a large file) you could easily run into out of memory errors. On the other hand, if you use a stream, the memory usage will be constant regardless of the size of the files your transferring. 

Buffers are really only suitable for small amounts of data. For larger data sizes, streams and piping is much more efficient and reliable.

**Comment by prabhatmishra33** [comment] 2022-10-11 05:29
Hello @theophilusx ,
we tried with streams but it didn't make any difference, still the pod crashed.

    import bufferToStream from 'buffer-to-stream';

    const uploadFileData = bufferToStream(fileData);
    await sftp.put(uploadFileData, filePath);

**Comment by theophilusx** [comment] 2022-10-11 07:07
What size are the files your having trouble with?

I note your still processing via a buffer. The same issue will exist
i.e. the buffer still needs to be the size of your largest amount of
data. All that you are now doing is going from buffer to stream. What
I'm suggesting is avoid using a buffer completely. 

Where is the 'fileData' data from (i.e. a file, a network socket, some
other process, etc)?

**Comment by prabhatmishra33** [comment] 2022-10-11 07:23
What size are the files your having trouble with?

It should be less than 15MB

Where is the 'fileData' data from (i.e. a file, a network socket, some
other process, etc)?

The file data is the json value.

Sure! We will remove the buffer part.

**Comment by theophilusx** [comment] 2022-10-11 08:09
A 15Mb file is not very large. While using streams would still be more
efficient and likely faster, those sort of sizes are unlikely to be a
big issue with buffers.

Certainly not an unusual or large size for ssh2 to handle. My suspicion
is the issue is still with either docker or the node docker image your
using. I don't believe this is anything related to ssh2 or
ssh2-sftp-client. Both of these packages have large user numbers and any
issues along these lines would trigger a lot of issue reports. Yours is
the only such report.

In the past, all docker related issues I've seen have been to do with
the network stack. I still suspect this is where your issue will be.

**Comment by theophilusx** [comment] 2022-10-11 09:21
Out of interest, how large are the files your trying to transfer?

I just noticed you are using a buffer to transfer your data. This is a
very inefficient approach and the buffer will need to be as large as
your file. As buffers will use your RAM, if your files are large enough,
you are probably just running out of memory (which would explain the 137
error).

I would change the code to use a stream instead of a buffer. This will
be much faster and more efficient as it doesn't require reading all the
data into a buffer. Buffers are really only appropriate with small
amounts of data.

**Comment by theophilusx** [comment] 2023-02-06 01:34
I have tested against multiple different platforms and cannot reproduce anything similar to the problem you are experiencing. I suspect it is specific to the container you are using. From your description, I suspect it is related to the network stack. As mentioned before, as an example, I've seen containers running under windows failing due to MTU problems - reducing the MTU fixed the problem in that case. 

I don't htink there is anything I can do form the ssh2-sftp-client side. THis is something you need to debug in your container environment and almost certainly nothing to do with ssh2-sftp-client. I would try using something like wireshark or tcpdump to monitor packets, monitor system log files etc.

**Closed by theophilusx** 2023-02-06 01:34 UTC
